### ISSUE TITLE
frequent ECONNRESET error

### ISSUE THREAD

**Issue by iamcgn** [argon/node-apn#137]
I'm logging this error pretty frequently.  It seems to happen if I haven't sent any notifications for an extended period of time.  When I get this error the push notification that it was attempting to send never gets sent regardless of the notification retry limit value.

**Comment by argon** [comment]
node-apn will now reset after 1 hour of inactivity which should fix this problem.

**Comment by quixoticaxis** [comment]
This issues does manifest itself even on http/2 APNs interface. We're currently facing it on our production environment and I feel like we're out of hotfix options.

#454 #449
