### ISSUE TITLE
Reliable Delivery

### ISSUE THREAD

**Issue by argon** [argon/node-apn#168]
Continued discussion/development of #167.

**Comment by mattberg** [comment]
I know this is an old topic, but I'm curious about the current status/throughput? Currently, I am using Parse, but it has become very slow, so I'm looking for something like this. I have about 500K devices.

**Comment by argon** [comment]
@mattberg perhaps you could elaborate? Are you seeing reliability problems with Parse? node-apn is in use by numerous large apps regularly pushing to >1M devices.

**Comment by mattberg** [comment]
Reliability seems fine with Parse, but now I'm more looking for speed. With 500K devices, it can take 5+ minutes to complete the send. I'm hoping more for around the 1 minute mark maximum.

**Comment by argon** [comment]
That should be possible with node-apn. In testing from my machine over home broadband I have seen ~9000 msg/s

**Comment by argon** [comment]
Superfluous with v2.0.0
