### ISSUE TITLE
Resending notifications on Socket error

### ISSUE THREAD

**Issue by deepakc** [argon/node-apn#182]
If there is a socket error NOT due to transmission error - Broken pipe or Pipe full, node-apn is not trying to send the notifications again (either all or just the cached notifications)

When there is a socket error (not due to transmission error), node-apn is just trying to send the last notification in the cache. But as per Apple's tech note (below) you can possibly send over 500 notifications before the dropped connection make its way from APNS back to server due to latency.

From Apple's technical note:
"It can take a while for the dropped connection to make its way from APNs back to your server just because of normal latency. It's possible to send over 500 notifications before a write fails because of the connection being dropped. Around 1,700 notifications writes can fail just because the pipe is full, so just retry in that case once the stream is ready for writing again."

**Comment by argon** [comment]
Going to close this as #168 is tracking it.
