### ISSUE TITLE
new apn.Connection(options) does not read config parameters

### ISSUE THREAD

**Issue by michaelsanford** [argon/node-apn#188]
At least, it appears not to.

For example, instantiating a `new apn.Connection(options);` with `var options = {}` and a `cert.pem` and `key.pem` in the same location as the file being called works.

But renaming `key.pem` to `server.pem` and instantiating with

```var options = {
   key: "server.pem"
  };```

fails.

*Similarly,* adding `passphrase: "<passphrase>"` to the options does not decrypt the key. However, adding no passphrase element to the options object, I am prompted for one at the command line. (The above example uses a key.pem with the passphrase removed.)

**Comment by 1JasonB** [comment]
I just brought up a new server and I'm seeing a related issue at require('apn). 

node_modules/apn/node_modules/q/q.js:128
                    throw e;
                          ^
Error: ENOENT, open 'cert.pem'

I do not have a default cert.pem or key.pem file. I have renamed them.

My previous config worked fine:
node 0.10.32
apn@1.6.2
 └── q@1.0.1

This one fails
node 0.10.37
apn@1.7.3
 ├── node-forge@0.6.21
 └── q@1.2.0

If I rename my files to the default, I don't see the problem.

**Comment by argon** [comment]
Would you be able to give me as much information as possible about your environment? Specifically OS version

An example of the code you’re using to load the module would be really helpful as nothing i’ve tried has reproduced the problem

Thanks

**Comment by 1JasonB** [comment]
I$B!G(Bm running Ubuntu Server 14.04 on EC2.

To load the module, I'm just doing


    var apn      = require('apn$B!G(B),


I$B!G(Bll put it out of my server and try it in a simpler program in my
environment.

Thanks for your attention.



From:  Andrew Naylor <notifications@github.com>
Reply-To:  argon/node-apn
<reply+0008c56b451f8c8a030eb684d2bf05ea125e2aa154f9885f92cf0000000111205f279
2a169ce023d85b2@reply.github.com>
Date:  Tuesday, March 17, 2015 at 4:31 PM
To:  argon/node-apn <node-apn@noreply.github.com>
Cc:  Jason Brewer <jsnbrwr@gmail.com>
Subject:  Re: [node-apn] new apn.Connection(options) does not read config
parameters (#188)

Would you be able to give me as much information as possible about your
environment? Specifically OS version

An example of the code you$B!G(Bre using to load the module would be really
helpful as nothing i$B!G(Bve tried has reproduced the problem

Thanks

> On 17 Mar 2015, at 21:22, Jason Brewer <notifications@github.com> wrote:
> 
> I just brought up a new server and I'm seeing a related issue at
require('apn).
> 
> node_modules/apn/node_modules/q/q.js:128
> throw e;
> ^
> Error: ENOENT, open 'cert.pem'
> 
> I do not have a default cert.pem or key.pem file. I have renamed them.
> 
> My previous config worked fine:
> node 0.10.32
> apn@1.6.2
> $B(&(!(!(B q@1.0.1
> 
> This one fails
> node 0.10.37
> apn@1.7.3
> $B('(!(!(B node-forge@0.6.21
> $B(&(!(!(B q@1.2.0
> 
> If I rename my files to the default, I don't see the problem.
> 
> $B!=(B
> Reply to this email directly or view it on GitHub
<https://github.com/argon/node-apn/issues/188#issuecomment-82605915>.
> 


$B!=(B
Reply to this email directly or view it on GitHub
<https://github.com/argon/node-apn/issues/188#issuecomment-82608051> .

**Comment by 1JasonB** [comment]
Found the problem while reducing. I was creating a feedback object in my
initialization. I guess in the earlier version, Feedback did not fail when I
did not specify the path to the cert file. I assume this is probably a fix
in APN for something that didn$B!G(Bt impact me before.

Below fails.
----------------
var apn      = require('apn');



var feedback = new apn.Feedback({

    batchFeedback: true,

    interval: 300,

});


Below passes.
----------------------
var apn      = require('apn');



var feedback = new apn.Feedback({

    batchFeedback: true,

    interval: 300,

    cert: 'data/apncert_adhoc.pem',

    key: 'data/apnkey_adhoc.pem',

    production: true,

});



Thanks,
Jason



From:  Andrew Naylor <notifications@github.com>
Reply-To:  argon/node-apn
<reply+0008c56b451f8c8a030eb684d2bf05ea125e2aa154f9885f92cf0000000111205f279
2a169ce023d85b2@reply.github.com>
Date:  Tuesday, March 17, 2015 at 4:31 PM
To:  argon/node-apn <node-apn@noreply.github.com>
Cc:  Jason Brewer <jsnbrwr@gmail.com>
Subject:  Re: [node-apn] new apn.Connection(options) does not read config
parameters (#188)

Would you be able to give me as much information as possible about your
environment? Specifically OS version

An example of the code you$B!G(Bre using to load the module would be really
helpful as nothing i$B!G(Bve tried has reproduced the problem

Thanks

> On 17 Mar 2015, at 21:22, Jason Brewer <notifications@github.com> wrote:
> 
> I just brought up a new server and I'm seeing a related issue at
require('apn).
> 
> node_modules/apn/node_modules/q/q.js:128
> throw e;
> ^
> Error: ENOENT, open 'cert.pem'
> 
> I do not have a default cert.pem or key.pem file. I have renamed them.
> 
> My previous config worked fine:
> node 0.10.32
> apn@1.6.2
> $B(&(!(!(B q@1.0.1
> 
> This one fails
> node 0.10.37
> apn@1.7.3
> $B('(!(!(B node-forge@0.6.21
> $B(&(!(!(B q@1.2.0
> 
> If I rename my files to the default, I don't see the problem.
> 
> $B!=(B
> Reply to this email directly or view it on GitHub
<https://github.com/argon/node-apn/issues/188#issuecomment-82605915>.
> 


$B!=(B
Reply to this email directly or view it on GitHub
<https://github.com/argon/node-apn/issues/188#issuecomment-82608051> .

**Comment by hynese** [comment]
I also get this error:

`Error: ENOENT, open 'cert.pem'`

When I put "cert.pem" and "key.pem" in the same directory as the .js file, everything is file.

I'm trying to do:
```
var production = false;
if(dev_dist == "dist"){
  production = true;
}
var options = {};
options.cert = __dirname + "/" + dev_dist + "/cert.pem";
options.key = __dirname + "/" + dev_dist + "/key.pem";
options.production = production;
```

(i.e. put the dev the dist .pem files in separate directories...)

**Comment by argon** [comment]
I have taken the example you gave above and run it on an EC2 instance. I have been unable to reproduce your problem
You can see the code I used here: https://gist.github.com/argon/b781f31d23eb4c215f70

```
> ubuntu@ip-172-30-0-153:~$ npm install apn
npm http GET https://registry.npmjs.org/apn
npm http 200 https://registry.npmjs.org/apn
npm http GET https://registry.npmjs.org/apn/-/apn-1.7.3.tgz
npm http 200 https://registry.npmjs.org/apn/-/apn-1.7.3.tgz
npm http GET https://registry.npmjs.org/node-forge
npm http GET https://registry.npmjs.org/q
npm http 200 https://registry.npmjs.org/q
npm http 200 https://registry.npmjs.org/node-forge
npm http GET https://registry.npmjs.org/q/-/q-1.2.0.tgz
npm http GET https://registry.npmjs.org/node-forge/-/node-forge-0.6.21.tgz
npm http 200 https://registry.npmjs.org/q/-/q-1.2.0.tgz
npm http 200 https://registry.npmjs.org/node-forge/-/node-forge-0.6.21.tgz
apn@1.7.3 node_modules/apn
├── q@1.2.0
└── node-forge@0.6.21
ubuntu@ip-172-30-0-153:~$ node apn
Dev/Dist:  dev
{ cert: '/home/ubuntu/dev/cert.pem',
  key: '/home/ubuntu/dev/key.pem',
  production: false }
Connected
Transmitted:  { encoding: 'utf8',
  payload: { aps: { alert: 'Hello' } },
  expiry: 0,
  priority: 10,
  retryLimit: -1,
  device: undefined,
  alert: 'Hello',
  badge: undefined,
  sound: undefined,
  newsstandAvailable: undefined,
  contentAvailable: undefined,
  mdm: undefined,
  compiled: '{"aps":{"alert":"Hello"}}',
  truncateAtWordEnd: false,
  urlArgs: undefined,
  category: undefined }
Completed!
ubuntu@ip-172-30-0-153:~$ vim apn.js
ubuntu@ip-172-30-0-153:~$ node apn
Dev/Dist:  dist
{ cert: '/home/ubuntu/dist/cert.pem',
  key: '/home/ubuntu/dist/key.pem',
  production: true }
Connected
Transmitted:  { encoding: 'utf8',
  payload: { aps: { alert: 'Hello' } },
  expiry: 0,
  priority: 10,
  retryLimit: -1,
  device: undefined,
  alert: 'Hello',
  badge: undefined,
  sound: undefined,
  newsstandAvailable: undefined,
  contentAvailable: undefined,
  mdm: undefined,
  compiled: '{"aps":{"alert":"Hello"}}',
  truncateAtWordEnd: false,
  urlArgs: undefined,
  category: undefined }
Completed!
Transmission Error 8
ubuntu@ip-172-30-0-153:~$
```

```
ubuntu@ip-172-30-0-153:~$ tree
.
|____apn.js
|____dev
| |____cert.pem
| |____key.pem
|____dist
| |____cert.pem
| |____key.pem
```

**Comment by hynese** [comment]
Hello,

Thank you for investigating this in detail. I just had a look at your gist. I successfully managed to run the code on node.js v0.12.0.

When I tried it originally, I had just set up nvm - I suspect there might have been some incorrect environment variables lingering around? There might have been some system conflict with Ubuntu's default "nodejs"? Though I can't be certain of this.

Sorry if I wasted your time. Though I really appreciate you investigating.

**Comment by argon** [comment]
It did seem like an unusual error to see, on the other hand it has been mentioned a couple of times so I will continue to look into it.

Thanks for your feedback. I'm always looking to improve the module further so if you get any ideas please open an issue.

**Comment by swapgo20** [comment]
Getting the same issue on start of application.

Here is my configuration.

var options = {
  "cert": __dirname + '/credentials' +'/cert.pem' ,
  "key":  __dirname + '/credentials' +'/key.pem' ,
  "production" : true,
  "passphrase": "asdfgh",
  "gateway": "gateway.sandbox.push.apple.com",
  "port": 2195,
  "enhanced": true,
  "cacheLength": 5
};

apnConnection = new apn.Connection(options);

This is the error.
/node_modules/apn/node_modules/q/q.js:155
                throw e;
                      ^
Error: ENOENT, open 'cert.pem'
    at Error (native)

But, when I comment line 155 i.e. throw e
Error goes away and push notifications work fine. 

Need help in resolving this.

**Comment by arturkiulian** [comment]
Also experiencing this issue. MacOS Yosemite. Options simply don't rewrite default path.

This is what I see from doing console.log throughout the connection.js file:
```javascript
default options: { cert: 'cert.pem',
  key: 'key.pem',
  ca: null,
  pfx: null,
  passphrase: null,
  production: false,
  voip: false,
  address: null,
  port: 2195,
  rejectUnauthorized: true,
  cacheLength: 1000,
  autoAdjustCache: true,
  maxConnections: 1,
  connectTimeout: 10000,
  connectionTimeout: 3600000,
  connectionRetryLimit: 10,
  buffersNotifications: true,
  fastMode: false,
  disableNagle: false,
  disableEPIPEFix: false }

passed in options: { cert: '/Users/artur/bitbucket/capitanapi/lib/credentials/cert.pem',
  key: 'stage_key.pem',
  passphrase: 'CPTN!APNS28',
  gateway: 'gateway.sandbox.push.apple.com',
  port: 2195,
  enhanced: true,
  cacheLength: 5,
  errorCallback: [Function] }

new options: { cert: 'cert.pem',
  key: 'key.pem',
  ca: null,
  pfx: null,
  passphrase: null,
  production: false,
  voip: false,
  address: null,
  port: 2195,
  rejectUnauthorized: true,
  cacheLength: 1000,
  autoAdjustCache: true,
  maxConnections: 1,
  connectTimeout: 10000,
  connectionTimeout: 3600000,
  connectionRetryLimit: 10,
  buffersNotifications: true,
  fastMode: false,
  disableNagle: false,
  disableEPIPEFix: false }

```

```javascript
function Connection (options) {
	if(false === (this instanceof Connection)) {
        return new Connection(options);
    }
	this.options = {
		cert: "cert.pem",
		key: "key.pem",
		ca: null,
		pfx: null,
		passphrase: null,
		production: (process.env.NODE_ENV === "production"),
		voip: false,
		address: null,
		port: 2195,
		rejectUnauthorized: true,
		cacheLength: 1000,
		autoAdjustCache: true,
		maxConnections: 1,
		connectTimeout: 10000,
		connectionTimeout: 3600000,
		connectionRetryLimit: 10,
		buffersNotifications: true,
		fastMode: false,
		disableNagle: false,
		disableEPIPEFix: false
	};
	console.log('\ndefault options:', this.options)
	console.log('\npassed in options:', options)
	for (var key in options) {
		if (options[key] === null || options[key] === undefined) {
			debug("Option [" + key + "] set to null. This may cause unexpected behaviour.");
		}
	}
	console.log('\nnew options:', this.options)
	util.extend(this.options, options);
```

**Comment by argon** [comment]
Please put the "new options" log after "util.extend" (as this is the line where the options are merged) and verify your results again.

―A

**Comment by arturkiulian** [comment]
@argon sorry about previous message, I've edit it right after posting to more relevant log, it indeed merges it after extend but loadCredentials is still using defaults

**Comment by danmusiccode** [comment]
Hi Argon, 

I experienced similar difficulties where using a non-default certificate name or path led to errors when using the default path/names worked just fine. This despite setting cusotm cert, key, ca, and passphrase in the options field for new apn.connection(options).

The problem turned out to be that I needed to set cert, key, ca, passphrase in feedbackOptions as well. I had assumed incorrectly that Feedback would use the same parameters as the apn.Connection which had already been instantiated.

**Comment by argon** [comment]
I have come to realise this is the problem that a lot of people are having. I have 2 tasks to resolve this problem

1. Add extra information to the certificate validation routines to indicate whether the error was caused by Connection or Feedback
2. Update the documentation to make it clearer that the Feedback and Connection configuration is isolated

—A

**Comment by kirrg001** [comment]
i also have this problem with version 1.7.5.
I actually expected that this issue is already solved.

Uncaught Error: ENOENT, open 'cert.pem'

Can you give a small update?

**Comment by argon** [comment]
Can you confirm whether you're passing the correct options to the feedback service? I have yet to see any cases of this problem where `apn.Connection` was actually at fault. It was that `apn.Feedback` was misconfigured and throwing an error but people assumed the error was from `apn.Connection`

**Comment by kirrg001** [comment]
Ha ok maybe its feedback service.
Here is my code:

````
var feedback = new Ios.Feedback({
  'batchFeedback': true,
  'interval': 300
});

feedback.on('feedback', function(devices) {
  ...
});

 __private__.connection = new Ios.Connection({
      cert: pushNotificationSettings.ios.cert,
      key: pushNotificationSettings.ios.key,
      passphrase: pushNotificationSettings.ios.secret,
      production: inProductionMode
});
````

**Comment by argon** [comment]
Yep, that's the problem. You must use the same configuration for feedback. Something like this would work.

````
var feedback = new Ios.Feedback({
  cert: pushNotificationSettings.ios.cert,
  key: pushNotificationSettings.ios.key,
  passphrase: pushNotificationSettings.ios.secret,
  production: inProductionMode,
  batchFeedback: true,
  interval: 300
});

feedback.on('feedback', function(devices) {
  ...
});

 __private__.connection = new Ios.Connection({
  cert: pushNotificationSettings.ios.cert,
  key: pushNotificationSettings.ios.key,
  passphrase: pushNotificationSettings.ios.secret,
  production: inProductionMode
});
````

**Comment by kirrg001** [comment]
Thanks for fast support. It helped!

**Comment by annaelizabeth2019** [comment]
I'm confused about the key.pem option. I have a key.p8, a certificate.cer, an apn-cert.p12, and a AppleWWDRCA.pem and I can get the initial push notification on sign up, but get the "cannot find cert.pem" error on attempting to push a new notification. I went into the module and manually change node_modules/apn/lib/config.js line with "cert.pem" to the cert.pem directory on my system, but since I already have the .p8 in my options: token object, where would I get the key.pem from for apn?
