### ISSUE TITLE
Queue grows indefinitely until server runs out of memory

### ISSUE THREAD

**Issue by bloudermilk** [argon/node-apn#191]
We've recently been running into issues where notifications will suddenly stop sending. In an effort to improve delivery rates, we upgraded from 1.3.x to the latest 1.5.2 and enabled the new `autoAdjustCache` option. Within a few hours after running it seems that notifications stopped being sent like before, but rather than eventually reconnecting the cache just continued to grow until eventually it reached 1,688,735 notifications and the process crashed. While we still have no clues as to why notifications simply stop sending, I figured I'd open this issue to bring this secondary problem to your attention. Perhaps we need a `maxCacheLength` option with some arbitrarily high default (e.g. 25k)?

**Comment by argon** [comment]
The module now has a default connect timeout of 10 seconds to hopefully prevent tls.connect from stalling indefinitely. There is also a limited number of retries possible. When this elapses the module will dump all notifications as undeliverable.
