### ISSUE TITLE
Problems with receiving push notifications over time

### ISSUE THREAD

**Issue by ThucHoang** [argon/node-apn#205]
Hi.

I seem to have some random problems when the push server (node-pushserver (remade with SQL instead) has been online for a while. Once in a while it stops sending notifications (or the more correct thing to say is that I can't receive notifications on the phones (I've tested with 5 different phones with both the app in background and foreground), the weird thing is that the push-server throws no error messages back to me. onFeedback shows no problems nor does onTransmissionError get called. Is there a way to get more information from APN what might be wrong with it?

The other weird thing is that if I try later (without restarting the server) the push message can be received again? Could this be some sort of APN connection error/timeout? Wouldn't onTransmissionError be called if this were to happen?

**Comment by psycotica0** [comment]
Is it possible that this is a TCP Keepalive issue?

**Comment by ThucHoang** [comment]
I forgot about this, my test-bench was turned off months ago! Just restarted now! Will update when I'm able to reproduce again!

**Comment by ThucHoang** [comment]
Seems like I managed to reproduce the timeout problem.

I sent my first push from it yesterday (12:34:08 | 2. Feb), everything was fine.

I tried sending today (10:04:33) which is 21 hours, 30 minutes and 25 seconds later. I'm not sure when this starts happening, but 16 minutes and 59 seconds later I received this from APNS:

```
2015-02-03 10:21:32: Tue, 03 Feb 2015 09:21:32 GMT apn Raising error: { [Error: read ETIMEDOUT] code: 'ETIMEDOU
T', errno: 'ETIMEDOUT', syscall: 'read' } null undefined
Push Timeout-3 (err): Tue, 03 Feb 2015 09:21:32 GMT apn Error occurred with trace: Error: read ETIMEDOUT
Push Timeout-3 (err):     at errnoException (net.js:901:11)
Push Timeout-3 (err):     at TCP.onread (net.js:556:19)
Push Timeout-3 (err): Tue, 03 Feb 2015 09:21:32 GMT apn Destroying connection 0
Push Timeout-3 (err): Tue, 03 Feb 2015 09:21:32 GMT apn Removing socket from pool 0
Push Timeout-3 (err): 2015-02-03 10:21:32: Tue, 03 Feb 2015 09:21:32 GMT apn Socket closed 0
Push Timeout-3 (err): Tue, 03 Feb 2015 09:21:32 GMT apn Removing socket from pool 0
Push Timeout-3 (err): Tue, 03 Feb 2015 09:21:32 GMT apn 0 left to send
```
Seems like it actually might be a TCP issue as mentioned by @psycotica0?

**Comment by argon** [comment]
I'm guessing you don't have the socket timeout configured in node-apn?

I think I will change the default behaviour to automatically shut down the socket after 1hr

—A

**Comment by ThucHoang** [comment]
Yes, that's correct. I created the server without the connectionTimeout parameter in the config. It seems like the socket doesn't turn off automatically. So changing the default behaviour to 1hr wouldn't be so bad :) It might be nice to see when this stale connection actually happens and if 1hr is the sweet spot?

**Comment by argon** [comment]
It seems that Apple is silently dropping connections after an unspecified time. I have never seen reports of this happening in less than 1 hour.

I think 1hour would be quite reasonable without being too aggressive. It could still be configurable.

—A

**Comment by ThucHoang** [comment]
Seems fair, let me run the code for a couple of hours with my implemented cronjob. It will check if the 1 hour is a good time, doesn't hurt to be sure!

**Comment by ThucHoang** [comment]
1 hours just fine! Recieved all push messages in the last 2 days :)
