### ISSUE TITLE
standard error and response interface

### ISSUE THREAD

**Issue by mderazon** [argon/node-apn#208]
the api for raising errors is a little strange, or maybe i'm not getting something right ?

I need to attach the error callback to the options I pass to connect ?
``` js
var config = {};
// ...
config.errorCallback = function(code, notification, recepient) {
// ...
};
var connection = new apns.Connection(config);
// ...
connection.pushNotification({...}, ids); // this is not async
```

This is not node standard way of `callback(err, results)`...

How are we supposed to handle errors or get the responses ?

**Comment by argon** [comment]
Addressed in v2.0.0
