### ISSUE TITLE
Only Dev certificate is working 

### ISSUE THREAD

**Issue by arnelceledonio** [argon/node-apn#216]
Any idea how to fix ..i get no errors using prod certificate ..only Disconnected from APNS 

//checking dev certificate
openssl s_client -connect gateway.sandbox.push.apple.com:2195 -cert key.pem -debug -showcerts -CAfile cert.pem
unable to load certificate
18743:error:0906D06C:PEM routines:PEM_read_bio:no start line:/SourceCache/OpenSSL098/OpenSSL098-52/src/crypto/pem/pem_lib.c:648:Expecting: TRUSTED CERTIFICATE

//checking prod certificate
openssl s_client -connect gateway.push.apple.com:2195 -cert key-prod.pem -debug -showcerts -CAfile cert-prod.pem
unable to load certificate
18801:error:0906D06C:PEM routines:PEM_read_bio:no start line:/SourceCache/OpenSSL098/OpenSSL098-52/src/crypto/pem/pem_lib.c:648:Expecting: TRUSTED CERTIFICATE

**Comment by arnelceledonio** [comment]
sandbox and production behaves differently? is this related to TLSv1? 

using node v0.10.35

openssl s_client -connect gateway.sandbox.push.apple.com:2195 -cert key-dev.pem -debug -showcerts -CAfile cert-dev.pem

New, TLSv1/SSLv3, Cipher is AES256-SHA
Server public key is 2048 bit
Secure Renegotiation IS supported
Compression: NONE
Expansion: NONE
SSL-Session:
    Protocol  : TLSv1
    Cipher    : AES256-SHA
    Session-ID:
    Session-ID-ctx:
    Master-Key: **************
....

================

openssl s_client -connect gateway.push.apple.com:2195 -key key-prod.pem -debug -showcerts -CAfile cert-prod.pem

18426:error:14094410:SSL routines:SSL3_READ_BYTES:sslv3 alert handshake failure:/SourceCache/OpenSSL098/OpenSSL098-52/src/ssl/s3_pkt.c:1125:SSL alert number 40
18426:error:140790E5:SSL routines:SSL23_WRITE:ssl handshake failure:/SourceCache/OpenSSL098/OpenSSL098-52/src/ssl/s23_lib.c:182:

**Comment by argon** [comment]
Did you generate your production and sandbox certificates at the same time? Everyone who has had the error 40 problem has resolved it by recreating the certificate in the provisioning tool.

**Comment by argon** [comment]
Could you please upgrade to v1.7.1 and let me know if you see any errors in this case?

**Comment by oziee** [comment]
i have updated to 1.7.1 and while sandbox was working just fine, production continues to error.. and its error 8 - which is invalid token right? 
but i have downloaded an app from the mac store and tested the certs and token and it works.. it just doesnt work with apn.. i found this thread but im still thinking it must be something im doing, but thought there might be a problem between dev sandbox and production apn

**Comment by argon** [comment]
If you are getting an error from Apple then that means the certificates are correct as you have established a connection successfully.

It sounds like you have a bad production token. I'm not sure I understand the second part of your description. Could you provide more details please?

**Comment by oziee** [comment]
if i delete everything from keychains and from the apple site and create a new production cert, i have done this already but will try again
i used this app https://itunes.apple.com/au/app/easyapn/id685956680?mt=12 and can test the cert and token and send tests.
but there must be something i am doing wrong when creating the PEM files for the production.. I must have done it right for the development cert since APN was sending just fine.. but for production its just giving the error 8 all the time

**Comment by argon** [comment]
If you’re getting error 8 there is unlikely to be anything wrong with the certificates.

The issue you have is an incorrect device token. I would suggest double-checking that you are using the correct token.

As I understand it, that test app successfully sends for both development and production, right?


—A

**Comment by oziee** [comment]
yes.. the app send to the one token for both dev and prod..
does one need to recreate the app archive again if the cert is changed?? i mean if something changes do i need to make the app again - does something change that it will need to know about to work with any new APN certs?

**Comment by argon** [comment]
The app shouldn’t need rebuilding.

Just to check: The tokens will be **different** between dev and prod. One token won’t work for both. Production only works with tokens for apps downloaded from the app store (or apps distributed with an Ad-Hoc certificate)

—A

**Comment by oziee** [comment]
i just deleted everything from apple provisioning and created all new appid and certs and apn certs.. changed the app's id and changed all the build settings.. recreated it and reinstalled to the phone..
tokens are set from the app to the database

all working now:)

thanks Argon
