### ISSUE TITLE
Uncaught exception for connection timeout on 1.6.2

### ISSUE THREAD

**Issue by rv-jsheehy** [argon/node-apn#217]
Seemed there was a connection timeout to APNS, but then the following threw an uncaught and crashed my process:

uncaught exception stack: Error: Connect timed out
    at Connection.<anonymous> (apn/lib/connection.js:193:36)
    at Timer.list.ontimeout (timers.js:101:19)

I didn't override the 10 second default val for connection timeout.

Thx

**Comment by argon** [comment]
@tanis2000 You may be interested to know that v1.7.0 now has a built-in credential validator.

**Comment by tanis2000** [comment]
@argon That's nice @argon! Thanks for your hard work on this project!

**Comment by argon** [comment]
This should be fixed on master and will be in v1.7.2

**Comment by freak4pc** [comment]
When is v1.7.2 out ... ?

**Comment by argon** [comment]
I'm on vacation this week but I'll try to get it out, next week at the latest

**Comment by freak4pc** [comment]
Enjoy your vacation ;) !

**Comment by argon** [comment]
1.7.2 is live.
