### ISSUE TITLE
Failed connection with no "error" listener breaks retry

### ISSUE THREAD

**Issue by androa** [argon/node-apn#219]
Came across a curious case when making a typo that sat connectionTimeout to 10ms. Turns out if the connection attempt fails, the [Promise's fail()-handler is going to emit a "error"-event](https://github.com/argon/node-apn/blob/master/lib/connection.js#L241).

As long as you have actually sat up an "error"-listener this will not be a big problem. However, with no listener, node has a default behaviour of throwing a stack trace and terminating.

The docs for [Class: events.EventEmitter](http://nodejs.org/api/events.html#events_class_events_eventemitter) states:

> When an EventEmitter instance experiences an error, the typical action is to emit an 'error' event. Error events are treated as a special case in node. If there is no listener for it, then the default action is to print a stack trace and exit the program.

As far as I can figure out this results in the code that executes the retry attempts and cleanup is never executed.

**Comment by argon** [comment]
This will be fixed in v1.7.2. Module initialisation errors will immediately emit an "error" and a "socketError". When a retry attempt will be made only a "socketError" will be emitted.

In future "error" events should only be emitted in unrecoverable situations.
