### ISSUE TITLE
Error in a working certificate: error:0906D06C:PEM routines:PEM_read_bio:no start line

### ISSUE THREAD

**Issue by NizarBlond** [argon/node-apn#234]
I'm trying to send push notification to the server using PEM certs that I generated and tested on OPENSSL, but I keep getting exception that crashes my node app.

Certificate Test:
 
	openssl s_client -connect gateway.push.apple.com:2195 -cert certdist.pem -key keydist.pem
	CONNECTED(00000003)

Exception

    Error: error:0906D06C:PEM routines:PEM_read_bio:no start line
   		at Object.exports.createCredentials (crypto.js:129:17)
		at apnSocketLegacy (/app/node_modules/apn/lib/socket.js:40:19)
		at Connection.initialize.spread.fail.terminated (/app/node_modules/apn/lib/connec

		at /app/node_modules/apn/node_modules/q/q.js:1171:26
		at _fulfilled (/app/node_modules/apn/node_modules/q/q.js:794:54)
		at self.promiseDispatch.done (/app/node_modules/apn/node_modules/q/q.js:823:30)
		at Promise.promise.promiseDispatch (/app/node_modules/apn/node_modules/q/q.js:756

		at /app/node_modules/apn/node_modules/q/q.js:516:49
		at flush (/app/node_modules/apn/node_modules/q/q.js:110:17)

This is happening when called from:

        apnConnection.pushNotification(note, tokens);

Ideas?

**Comment by nickw** [comment]
I'm having the same issue on Modulus, and like @NizarBlond running `openssl rsa -text -in` seems to work fine. Any thoughts?

**Comment by nickw** [comment]
Nevermind guys, turned out to be a simple configuration issue for me.

**Comment by argon** [comment]
Could you share what the issue was as I think it might apply to others?

Also, I’m working on providing more useful errors for the certificate/keys so it’d be useful to know what the problem was so I can include it in my testing.

Thanks

—A

**Comment by nickw** [comment]
My app is a Meteor app using the [raix:push](https://github.com/raix/push) which apparently uses your Node package under the hood. Our config file was just pointing to a cert instead of a key.

**Comment by argon** [comment]
Perfect, thanks. That's exactly one of the cases that the new feature will catch. I'll be sure to add a specific test for it as well


—A

**Comment by argon** [comment]
v1.7.0 now has a certificate validator which will catch errors like this.

**Comment by sreenibellamkonda** [comment]
Hi , 
i am trying to install phonegap. but got the error could you please some help on this.
i ran the below command 
npm install -g phonegap

Error:
C:\Users\bellamks>npm install -g phonegap
npm ERR! Windows_NT 6.1.7601
npm ERR! argv "C:\\Program Files\\nodejs\\\\node.exe" "C:\\Program Files\\nodejs
\\node_modules\\npm\\bin\\npm-cli.js" "install" "-g" "phonegap"
npm ERR! node v0.12.7
npm ERR! npm  v2.11.3

npm ERR! error:0906D06C:PEM routines:PEM_read_bio:no start line
npm ERR!
npm ERR! If you need help, you may report this error at:
npm ERR!     <https://github.com/npm/npm/issues>

npm ERR! Please include the following file with any support request:
npm ERR!     C:\Users\bellamks\npm-debug.log

**Comment by sreenibellamkonda** [comment]
Hi , 
i am trying to install phonegap. but got the error could you please some help on this.
i ran the below command 
npm install -g phonegap

Error:
C:\Users\bellamks>npm install -g phonegap
npm ERR! Windows_NT 6.1.7601
npm ERR! argv "C:\\Program Files\\nodejs\\\\node.exe" "C:\\Program Files\\nodejs
\\node_modules\\npm\\bin\\npm-cli.js" "install" "-g" "phonegap"
npm ERR! node v0.12.7
npm ERR! npm  v2.11.3

npm ERR! error:0906D06C:PEM routines:PEM_read_bio:no start line
npm ERR!
npm ERR! If you need help, you may report this error at:
npm ERR!     <https://github.com/npm/npm/issues>

npm ERR! Please include the following file with any support request:
npm ERR!     C:\Users\bellamks\npm-debug.log

**Comment by argon** [comment]
Your problem seems completely unrelated to this project (node-apn) you should probably ask your question in the phonegap community http://phonegap.com/community/

**Comment by umashankardas** [comment]
Hi,
  Pardon me for the noob question, but, I'm not able to generate the key.pem file. It is giving a loading error on validation. I have 2 inputs.
a) .p12 file from keychain access of the Mac. [web.p12]
b) .cer file downloaded from apple developer portal [web.cer]

If someone can give the exact command. It will be very helpful.

**Comment by oliversalzburg** [comment]
@umashankardas From our internal documentation:

    In case you have to convert the APN certificates from the `.cer` to the `.pem` format required by FairManager, use the following command:

        openssl x509 -inform der -in aps_production.cer -outform pem -out aps_production.pem

    In case you have to convert the APN private keys from the `.p12` to the `.pem` format required by FairManager, use the following command:

        openssl pkcs12 -in "eu.fairmanager.mobile Push Production.p12" -out aps_production_key.pem -nodes

**Comment by DanielReid** [comment]
> 
> 
> My app is a Meteor app using the [raix:push](https://github.com/raix/push) package which apparently uses your Node package under the hood. Our config file was just pointing to a cert instead of a key.

Hahaha, thank you so much, this ended up being what I was doing wrong as well. Sometimes it's the simple things.

**Comment by RogerMito** [comment]
What's up guys! I was passing by the same problem after convert a .pfx file to .pem. I'm using the xml-crypto lib to sign a xml document. Then I tried the command reported by you  (`openssl rsa -text -in my_cert.pem`) and after soon, I copied the content from  -----BEGIN RSA PRIVATE KEY----- to -----END RSA PRIVATE KEY----- It worked perfectly! Thanks!
