### ISSUE TITLE
README recommends expiry, not setExpiry

### ISSUE THREAD

**Issue by hypesystem** [argon/node-apn#239]
It seems weird that the README recommends [directly touching internal state of the Notification object](https://github.com/argon/node-apn#sending-a-notification), when there are methods for the same thing (ie. `setExpiry`, etc.).

**Comment by argon** [comment]
The accessors are now secondary to the object properties which are now preferred. The README is correct so I'm going to close this.

**Comment by hypesystem** [comment]
Depending on object properties means that you will have to make a major version bump (breaking release) if you want to change them. This is the advantage of using methods or functions as intermediaries. Depending directly on object state is generally considered bad practice. Be that as it may, yes, the README is correct :)

**Comment by argon** [comment]
If you look at how it is implemented the properties are implemented as getters an setters using underlying ivars which are not touched.

You are right about breaking changes but this merely surfaces Apples' format so the only reason it would change is if Apples format changes and if they do that I would have no choice but to make it a version bump to match.

―A
