### ISSUE TITLE
Silent notifications not consistently working?

### ISSUE THREAD

**Issue by bigthyme** [argon/node-apn#241]
This seems to be more of Apple's fault more than anyone else...but sending the default payload as packaged in this library with no "alert" payload key doesn't not wake up the app.

http://stackoverflow.com/questions/19239737/silent-push-notification-in-ios-7-does-not-work

Is there a better payload we can default to that will ensure silent notifications (i.e. contentAvailable pushes) will be more reliable? 

my current payload
```
# everything else is default node-apn (i.e. priority 10)

aps =  {
    badge = 0;
    "content-available" = 1;
 };

```

**Comment by argon** [comment]
I have not seen this problem previously but I guess things could have changed since. How are you determining whether your app wakes?

**Comment by argon** [comment]
Ah! As specified in the link you posted, background content-available notifications are only permitted with priority 5. (Emphasis mine)

> The notification’s priority. Provide one of the following values:

> 10 The push message is sent immediately.
    
> The push notification must trigger an alert, sound, or badge on the device. **It is an error to use this priority for a push that contains only the content-available key.**

> 5 The push message is sent at a time that conserves power on the device receiving it.
