### ISSUE TITLE
Proxy Support.

### ISSUE THREAD

**Issue by accessdev** [argon/node-apn#242]
I m trying to use the module but I am behind a corporate proxy. is there any option I have to use to make it work behind a proxy?

**Comment by argon** [comment]
This is the next item on my task backlog. Could I ask what kind of proxy you are using? SOCKS, HTTP or other?

Regards

—A

**Comment by accessdev** [comment]
great news :) I m behind a http proxy. let me know if you need help for tests:)

**Comment by argon** [comment]
I'm going to close this as #163 already exists to track this request.

**Comment by anabulsi** [comment]
really amazing library. I can't wait until proxy support is added.
