### ISSUE TITLE
1.7.0 is broken: CERT_UNTRUSTED 

### ISSUE THREAD

**Issue by godspeedelbow** [argon/node-apn#243]
We got certificate issues after upgrading to 1.7.0:

```
Thu, 05 Feb 2015 10:48:48 GMT apn Socket error occurred undefined [Error: CERT_UNTRUSTED]
Thu, 05 Feb 2015 10:48:48 GMT apn Destroying connection undefined
Thu, 05 Feb 2015 10:48:48 GMT apn Removing socket from pool undefined
Thu, 05 Feb 2015 10:48:48 GMT apn Raising error: { [Error: CERT_UNTRUSTED]
```

-----------------------------------

```
Thu, 05 Feb 2015 10:48:48 GMT apn Error occurred with trace: Error: CERT_UNTRUSTED
    at SecurePair.<anonymous> (tls.js:1380:32)
    at SecurePair.emit (events.js:92:17)
    at SecurePair.maybeInitFinished (tls.js:979:10)
    at read (tls.js:471:13)
    at Readable.read (_stream_readable.js:340:10)
    at write (tls.js:368:25)
    at doWrite (_stream_writable.js:225:10)
    at writeOrBuffer (_stream_writable.js:215:5)
    at Writable.write (_stream_writable.js:182:11)
```

```
Error: CERT_UNTRUSTED
  
  - ---------------------------------------------
  
  - connection.js:210 initialize.then.fail.terminated
    [peerby]/[apn]/lib/connection.js:210:15
  
  - q.js:794 _fulfilled
    [peerby]/[apn]/[q]/q.js:794:54
  
  - q.js:823 self.promiseDispatch.done
    [peerby]/[apn]/[q]/q.js:823:30
  
  - q.js:756 Promise.promise.promiseDispatch
    [peerby]/[apn]/[q]/q.js:756:13
  
  - q.js:564 
    [peerby]/[apn]/[q]/q.js:564:44
  
  - q.js:110 flush
    [peerby]/[apn]/[q]/q.js:110:17
  
  - ---------------------------------------------
  
  - q.js:166 requestTick
    [peerby]/[apn]/[q]/q.js:166:21
  
  - q.js:156 Function.nextTick
    [peerby]/[apn]/[q]/q.js:156:13
  
  - q.js:563 
    [peerby]/[apn]/[q]/q.js:563:15
  
  - Array.reduce
  
  - q.js:223 
    [peerby]/[apn]/[q]/q.js:223:21
  
  - q.js:562 become
    [peerby]/[apn]/[q]/q.js:562:9
  
  - q.js:578 deferred.resolve
    [peerby]/[apn]/[q]/q.js:578:9
  
  - q.js:623 
    [peerby]/[apn]/[q]/q.js:623:18
  
```

**Comment by argon** [comment]
Are you running on Mac or Linux?

—A

**Comment by godspeedelbow** [comment]
Linux

**Comment by argon** [comment]
The cert_untrusted error should have happened previously, this isn't something that has changed in node-apn. I will investigate further.

—A

**Comment by godspeedelbow** [comment]
Well, downgrading to `1.6.2` fixed it

**Comment by godspeedelbow** [comment]
Thanks for responding so quickly btw

**Comment by argon** [comment]
Stay on 1.6.2 for now and I'll let you know when I've fixed this.

Which version of node are you running?

Is everything except the apn module version the same?

—A

**Comment by argon** [comment]
I have rolled back to 1.6.2 on npm until I figure out more details about this.

—A

**Comment by godspeedelbow** [comment]
Thanks, will do. We're running on `v0.10.33`

Eelke Boezeman
CTO & co-founder
Peerby.com

Borrow the things you need from people nearby. Sign up now
<http://peerby.com/signup> on peerby.com

e-mail: eelke@peerby.com
twitter: @godspeedelbow <http://twitter.com/godspeedelbow>
phone: *+31 6 52 637 657*
skype: elbowdashizzle

*Peerby BV*
facebook: facebook.com/peerby
twitter: @peerby <http://twitter.com/peerby>

*office*
Herengracht 182
1016 BR Amsterdam
The Netherlands

*mail*
Postbus 11149
1001GC Amsterdam
The Netherlands

**Comment by kas84** [comment]
Same problem here. Experienced the failuer on a mac and Linux.

**Comment by argon** [comment]
Could I ask whether you're seeing this problem in sandbox, production or both?

—A

**Comment by argon** [comment]
I have isolated the problem. Should be able to get 1.7.1 out tonight or tomorrow.

**Comment by godspeedelbow** [comment]
Works! Thanks @argon
