### ISSUE TITLE
Credentials validation still fail even the settings were okay

### ISSUE THREAD

**Issue by itsnotvalid** [argon/node-apn#245]
I upgraded to v1.7.1 from 1.6.2 and 1.7.0 (which was a bad release) with the same production cert from apple. However with 1.7.1, I always get the error thrown for `certificate does not support configured environment, production: false`.

Note that the setup worked with v1.6.2 without any problems.

Env: cygwin-x64, node v0.11/v0.12.

Thanks.

**Comment by argon** [comment]
Would you mind emailing me the certificate (without private key) to the address on my GitHub profile so I can investigate further? I have followed the guidelines provided by Apple so I am surprised there is a problem.

—A

**Comment by itsnotvalid** [comment]
Hello,

I've got away with setting NODE_ENV=production. However I'm not sure why it worked in 1.6.2 but not in 1.7.1 where I didn't set NODE_ENV but only did a connection call like this:
```
new apn.Connection({
    "cert"           : this.cert,
    "key"            : this.key,
    "production"     : true,
    "batchFeedback"  : true,
    "interval"       : 300,
    "maxConnections" : 5,
  });
```
The reason why I could set this is that, the service I used for Apple has only production certs so I use that for both development phase and production. Can "production" bet set by programmable API?
Thanks.

**Comment by argon** [comment]
ah, ok, you can (and should) set the production flag manually. Are you using a VoIP certificate by any chance?

**Comment by argon** [comment]
I will try to add some better tests for these scenarios

**Comment by itsnotvalid** [comment]
@argon I am using a cert from Push Cert Portal (https://identity.apple.com/pushcert/).

**Comment by argon** [comment]
I need some more details here as you have provided conflicting information. Could you please confirm whether setting `production:true`, without `NODE_ENV=production` works?

The production flag should only be affected by the `NODE_ENV` if it is *not* explicitly set in the connection configuration. Your configuration shows you setting `production` directly so `NODE_ENV` should have no effect.

**Comment by cuterajat26** [comment]
I struggled with this issue as well. the problem is sometimes if you start your application with "forever" it does not set NODE_ENV for the node app, even though it is set in the environment(validated by checking echo $NODE_ENV). 

@argon -You have used (process.env.NODE_ENV === "production") in your if conditions, which makes the code fallback to "development" mode if the NODE_ENV is not set(by forever,by developer,by OS etc 's mistake).
It is better to fallback it to "production" mode by using (process.env.NODE_ENV === "development") condition everywhere.

**Comment by argon** [comment]
It is not a good idea to fallback to "production" mode as it is against convention. Express.js will fallback to "development" if `NODE_ENV` is not present, as will Rails and I'm sure many others.

If your system/supervisor is not propagating the environment to the process you're trying to run then you have bigger problems, especially if you're depending on passing more than just NODE_ENV to the system, which some would argue you should.

Finally, it is always possible to overwrite the default behaviour in code. If for instance, you get your process configuration from redis you can set `production = true` explicitly when creating a new `Connection` object.

**Comment by itsnotvalid** [comment]
Hello, the documentation would need to indicate that, in order to use a production certificate, the whole app must be run in NODE_ENV=production (not changeable using flags inside code). However my original reporting was that even though I explicitly set production = true in the Connection object, it somehow lost the setting and raised an Error.

> I need some more details here as you have provided conflicting information. Could you please confirm whether setting production:true, without NODE_ENV=production works?

So, it doesn't work after changing to 1.7+ code.

**Comment by nilskassube** [comment]
You can change it to production by setting the gateway to gateway.push.apple.com in the options. Works for me.

**Comment by argon** [comment]
@itsnotvalid are you referring to the information on the README.md? 

> If you name your certificate and key files appropriately (`cert.pem` and `key.pem`) then the defaults should be suitable to get you up and running. By default the module will connect to the sandbox environment unless the environment variable `NODE_ENV=production` is set. For more information consult the documentation (in doc/apn.markdown).

I can see where the confusion might arise from. I will try to make the phrasing clearer that the `NODE_ENV` behaviour is the _default_ and is overrideable.

I understand you say that it doesn't work after changing to 1.7 code. This part of the code is quite comprehensively tested and all my tests pass. I also have tried to replicate the problem using the information you gave and have been unable to do so.

```js
var apn = require ("apn");

var token = "f932d5b1 7ec33c16 f10bd012 69793f80 f0877f12 014c2eb0 49a7caa1 bd142a78";

var service = new apn.Connection({
    "cert"           : "certificates/cert_production.pem",
    "key"            : "certificates/key_production.pem",
//  "production"     : true,
    "batchFeedback"  : true,
    "interval"       : 300,
    "maxConnections" : 5,
  });

var note = new apn.notification().setAlertText("Hello");
service.pushNotification(note, token);
service.shutdown();
```

* If I run the above code **without** `NODE_ENV` then it will **fail** with the error you gave:
```
○ → NODE_ENV=dev node productionFlag.js
/Users/argon/Projects/node-apn/node_modules/q/q.js:128
                    throw e;
                          ^
Error: certificate does not support configured environment, production: false
    at validateCredentials (/Users/argon/Projects/node-apn/lib/credentials/validate.js:19:10)
    at /Users/argon/Projects/node-apn/lib/connection.js:162:5
    at _fulfilled (/Users/argon/Projects/node-apn/node_modules/q/q.js:794:54)
    at self.promiseDispatch.done (/Users/argon/Projects/node-apn/node_modules/q/q.js:823:30)
    at Promise.promise.promiseDispatch (/Users/argon/Projects/node-apn/node_modules/q/q.js:756:13)
    at /Users/argon/Projects/node-apn/node_modules/q/q.js:564:44
    at flush (/Users/argon/Projects/node-apn/node_modules/q/q.js:110:17)
    at process._tickCallback (node.js:355:11)
```

* If I run it **with** `NODE_ENV=production` then as you say, it works correctly.
* If I uncomment `"production": true` and run it **without** `NODE_ENV` then it also **works correctly**.

I need more details about which configuration options you are passing to the connection so I can identify the missing test cases and fix the problem. Without being able to reproduce the problem there isn't much I can do.

@nilskassube you are correct that gateway can be overriden. That option has been deprecated in favour of the `production` flag which will set the correct address automatically.

**Comment by argon** [comment]
@itsnotvalid have you made any further progress with this?

**Comment by itsnotvalid** [comment]
@argon Tested with 1.7.3 on node v0.12.2 x86_64 windows. Seems no difference. Also "cert" and "key " seems to have problems for some path finding on windows as well. I always compare with 1.6.x series and there was no problem with those versions.

**Comment by argon** [comment]
Thank you for the update.

Unfortunately I have spent hours trying to reproduce this issue and have been unable to do so. Without a reproducible test case/example project this issue is blocked.

If you can supply me with a minimal example project which demonstrates the problem I will be able to move forward, but without that there's not much more I can do

**Comment by ryantmer** [comment]
Hey Andrew,

I've also come across this problem, and the above solutions don't seem to work. I've got a simple example at https://gist.github.com/ryantmer/7eea61d3c5fba1918586 , the output of which is

```
transmissionError 513
error [Error: certificate does not support configured environment, production: false]
socketError [Error: certificate does not support configured environment, production: false]
completed undefined
```

Setting `production: true` in the connection options or setting `NODE_ENV=production` changes `production: false` to `production: true`, but with the same errors. What I find exceptionally odd is that I get the `completed` event happening either way...

Hopefully this example can be useful to figuring out what's going on here!

**Comment by argon** [comment]
Just to clarify, you’re using production certificates with your example code, right?

—A

**Comment by argon** [comment]
@ryantmer 
I have looked into this and so far unable to reproduce but I wonder if you could help me out by providing some crucial info? (tl;dr: see last paragraph)

The error message you have included above indicates that node-apn was configured with `production: false` and that the certificates are not recognised as being valid for that environment. You indicate that setting `production: true` also causes the error but with `production: true` in the message instead of `production: false`. Is that correct?

I think this problem is related to the code I wrote in node-apn to verify certificates. One aspect of this verification is to ensure that the correct certificates are being used.

Apple documents the fact that APNS certificates will have attributes corresponding to the environment which they are provisioned for. i.e. a Production certificate will have one flag set, and Sandbox will have another. node-apn parses the certificate and, among other things, checks for the presence of these flags, comparing them to the environment production flag. It seems to me like the certificate you're using somehow has these flags missing or a variant which is not documented by Apple. 

**Would you be able to email me** (address on my profile) the output from running
`openssl x509 -text -noout -in cert.pem`? It would be incredibly helpful. Feel free to obfuscate any data you consider to be sensitive, but the unedited output would be best. Please do not change anything below `X509v3 extensions:

**Comment by ryantmer** [comment]
@argon, yeah, setting `production: true` or `production: false` seems to just change the the true/false in the error message, but the rest of the message remains the same. I sent an email with the output you requested; hopefully that yields some answers!

**Comment by trevorah** [comment]
@itsnotvalid I had the same issue, but it turned out that the error was being emitted by the Feedback object, which I had forgotten to configure with `production: true`.

I dont suppose you've made the same mistake?

**Comment by ryantmer** [comment]
Turns out in my case, the problem was that the certificate was not a valid Apple certificate. Once I got a new one, the error message was no longer occurring.

**Comment by itsnotvalid** [comment]
@trevorah as it turned out, you're right! I almost forgot that there are options available for the Feedback object as well. I missed that one because I didn't put any options in it.

**Comment by trevorah** [comment]
Cool. I'll send a pull request.

**Comment by argon** [comment]
@itsnotvalid for the default case no options keys are required on the apn object, to get it working in the sandbox environment.

**Comment by itsnotvalid** [comment]
@argon because the way how error messages work with node, it wasn't obvious whether it was connection or feedback object causing the errors. So it took that long for me to discover that.

**Comment by samuelcastro** [comment]
Hi guys, I'm still getting this issue:
"Error: certificate does not support configured environment, production: true'""

My settings:

NODE_ENV=production
var connect_option = {
        gateway            : APN_SERVER,
        key                    : APN_KEY_FILE_PATH,
        cert                    : APN_CERT_FILE_PATH,
        errorCallback     : pushCallbackError,
        //production          : true             //with true/false or uncomment same issue
        batchFeedback  : true,
        interval               : 300,
        maxConnections : 5
    };

node: v0.10.37
node-apn: 1.7.3

Do you have some idea what's happen?

**Comment by argon** [comment]
You are using sandbox certificates

―A

**Comment by samuelcastro** [comment]
I'm using production live certificates.

**Comment by argon** [comment]
In that case they are somehow invalid. Please email the certificate (**not** the key) to the email address on my profile and I will validate the certificate for you.

**Comment by samuelcastro** [comment]
Ok, sent.

**Comment by argon** [comment]
The validation passes on my machine, the certificate is fine and `apn` does not reject it. Double check your configuration. You should remove `gateway: APN_SERVER` from your configuration as that has been deprecated and could break things. Use the `production: true|false` flag only.

**Comment by samuelcastro** [comment]
Still getting this problem:

app-0 (out): 513: 'Transmission Error'
app-0 (out): Error: certificate does not support configured environment, production: true: 'Standard error'

My all settings:

```
var connect_option = {
        key: APN_KEY_FILE_PATH,
        cert: APN_CERT_FILE_PATH,
        production: true,
        errorCallback: pushCallbackError,
        batchFeedback  : true,
        interval       : 300,
        maxConnections : 5
    };

var pushCallbackError = function(errorNum, notification){
        inspect('Push Error is: ' + errorNum);
    };

var connection = new apn.Connection(connect_option);

    connection.on("connected", function() {
        inspect("Connected");
    });

    connection.on("completed", function () {
        inspect("Completed!");
    });

    connection.on("transmitted", function(notification) {
        inspect("Transmitted: ", notification);
    });

    connection.on("socketError", function(err) {
        inspect("Socket error", err.message);
    });

    connection.on('transmissionError', function(err) {
        inspect("Transmission Error", err);
    });

    connection.on("error", function(err) {
        inspect("Standard error", err);
    });

for(var i=0;registrationIds.length > i; i++){
        var device = new apns.Device(registrationIds[i]);
        var notification = new apns.Notification();

        notification.alert = message;
        notification.payload  = {"type":type};
        notification.badge = badge;
        notification.sound = "assets/beep.wav"; //path to your sound

        connection.pushNotification(notification, device);
    }

```

**Comment by samuelcastro** [comment]
@argon Is working now, I just rebuild our server installing ours packages again and just worked. :)

**Comment by harunurhan** [comment]
I have this problem, with production: false, sandbox certificate and key.
