### ISSUE TITLE
Silent Badge Update Not Working

### ISSUE THREAD

**Issue by staffup-dave** [argon/node-apn#249]
Here's my note:

````javascript
var num_new = 5
var length = user.ios_tokens.length
var myDevices = []
for(var i = 0 ; i < length; i++) {
   myDevices.push(new apn.Device(user.ios_tokens[i]))
}

var note = new apn.Notification ();
note.badge = Number(num_new)
apnConnection.pushNotification ( note, myDevices );
````
I'm running with DEBUG=apn and can see the connection being established and getting drained so it appears to be sending. 

My app has badges set to true in the notifications settings.

I can update the badge when sending a message with a complete payload, but not when I only send the badge number.

I've tried the following:
1. dropping the priority to 5 (using note.priority = 5) and that didn't work either.
2. setting alert, sound to null
3. adding an empty payload object
edit: few more things i've tried
4. sound=""

I figured I'd be getting some kind of feedback on failure but I'm not seeing anything - from what I can tell this should be updating the badge.

Closing edit: it looks like my ios developer might not be doing anything with alerts while the app is open - will re-open if the issue is indeed this lib.

**Comment by argon** [comment]
Did you figure out the problem with this?

**Comment by staffup-dave** [comment]
Looks to be iOS side. Will know for sure on Monday. You can delete if you'd like.

**Comment by argon** [comment]
I'd prefer to reopen it if you're happy to provide an update when you confirm one way, or another?

**Comment by staffup-dave** [comment]
Will do!

**Comment by staffup-dave** [comment]
@argon the problem was how the iOS app was handling silent badge updates - your library performed as expected.

Thanks!
