### ISSUE TITLE
how to use debug model?

### ISSUE THREAD

**Issue by chelsh** [argon/node-apn#252]
var service = new apn.connection({ production: false });

process.env.DEBUG=apn;
service.on("connected", function() {
    console.log("Connected");
});

--- it is not ok

**Comment by argon** [comment]
Run your script like this:

`DEBUG=apn node <app script>.js`

If you want to set it in code then the end must be set *before* the call to `require("apn")`

-A

**Comment by chelsh** [comment]
process.env.DEBUG=apn
var apn = require('apn');

var service = new apn.connection({ production: false });


---like this?

**Comment by argon** [comment]
You will need quotes around "apn" where you set the environment, but yes.

\A

**Comment by chelsh** [comment]
Ok,Thank you
