### ISSUE TITLE
Error code 8

### ISSUE THREAD

**Issue by rukumar333** [argon/node-apn#256]
I am trying to send apple push notifications and when I use the debug module and set DEBUG=apn and then run node, I am getting this error message...
  apn Initialising connection +0ms
  apn Initialising module +1ms
  apn 1 left to send +1ms
  apn Connection established +400ms
  apn Socket drained +101ms 0
  apn 0 left to send +1ms
  apn 0 left to send +0ms
  apn Notification 0 caused an error: 8 +123ms
  apn Raising error: +0ms 8 { encoding: 'utf8',
  payload: 
   { messageFrom: 'Travel Bing',
     aps: { badge: 2, alert: '📧 ✉Hello World' } },
  expiry: 0,
  priority: 10,
  retryLimit: -1,
  device: undefined,
  alert: '📧 ✉Hello World',
  badge: 2,
  sound: undefined,
  newsstandAvailable: undefined,
  contentAvailable: undefined,
  mdm: undefined,
  compiled: '{"messageFrom":"Travel Bing","aps":{"badge":2,"alert":"📧 ✉Hello World"}}',
  truncateAtWordEnd: false,
  urlArgs: undefined,
  category: undefined } { token: <Buffer e6 4b 43 28 13 62 bb c7 f6 62 aa 5b 9c 55 9e 09 ce 77 be c4 2f 10 7a 89 5f 32 93 f8 e8 c6 79 61> }
  apn Buffering 0 notifications for resending +2ms
  apn Socket closed +0ms 0
  apn Removing socket from pool +0ms 0
  apn 0 left to send +0ms

What is the issue and what do I need to fix?

**Comment by naartjie** [comment]
@rukumar333 from my experience, the "8" normally means mixing development and production environments, i.e. trying to send through a production environment to a device running on a development provisioning profile, or the other way around.

**Comment by naartjie** [comment]
http://stackoverflow.com/questions/16501519/apns-invalid-token-8

**Comment by rukumar333** [comment]
I think I know what the problem is. The key and certificate I am using were for distribution. When I uploaded the app to an iphone using Xcode, I assumed that was the distribution version of app. Turns out, its actually still development. I will try to see if fixing this up will stop the error and post again.

**Comment by argon** [comment]
Have you resolved this?

**Comment by rukumar333** [comment]
I apologize, I never got back to this post. I think it was a mix up of distribution and development certificates and keys. I am waiting for Apple to approve the new update for my app so I can see if the distribution version works ok.

**Comment by argon** [comment]
I'm closing this now. Reopen it if you still have the problem.
