### ISSUE TITLE
Issue with npm. package.json version of node-forge should be >=0.6.10

### ISSUE THREAD

**Issue by AntonSotirov** [argon/node-apn#265]
getPublicKeyFingerprint method of forge.pki. is not available before version 0.6.10. An error is thrown in ./lib/credentials/APNKey.js:14

**Comment by AntonSotirov** [comment]
It seems to be an issue with npm. The version that I fetch with "npm install" has a "node-forge": "0.6.x " dependency and that seems to be the real issue :/

**Comment by argon** [comment]
Did you successfully resolve this?

**Comment by AntonSotirov** [comment]
Yeah, I cleaned the npm cache, deleted apn folder in node-modules and "npm install apn" successfuly installed the correct version of node-forge.
