### ISSUE TITLE
Question about the use of the debug package

### ISSUE THREAD

**Issue by ruffrey** [argon/node-apn#266]
Thanks for this awesome module. I've enjoyed using it a few times.

Why is debug not a dependency? This forces that you `require` it inside a `try` block, which (if i'm not mistaken) prevents that scope from being fully optimized by v8. I am sure there is a reason for this and want to understand why. thanks!

**Comment by argon** [comment]
This was from a time when I was trying to avoid any dependencies. you're right that it doesn't make sense to keep it now. Having it as a devDependency makes a lot of sense.

―A

**Comment by ruffrey** [comment]
Sounds good. Actually my concern was the performance at (very) high scale when the connection.js module cannot be fully optimized by v8 due to the try/catch being in there.

Since dev dependencies could theoretically be shipped without the production software (`npm i --production` is common), we'd have to keep the try/catch during the `require('debug')`. I guess one way around that is to put the try/catch inside a self executing function. Another way is just to call it a dependency.

The code was a little cleaner in the latter scenario, so I will put that in a PR. Definitely I won't be offended if you decline it though.

`debug` is a normal/non-dev dependency in a lot of highly performant projects (express, etc). It shouldn't really be doing anything unless those `DEBUG=` environment variables are present.
