### ISSUE TITLE
Sending Push Notifications does not work reliably

### ISSUE THREAD

**Issue by akohout** [argon/node-apn#268]
I'm using node-apn in production for our app. In case certain events take place, we'll inform our users about that event via push notification. In addition, they see a message  next time they open the app. So they know when they haven't received a push although they should have. And it seems to happen a lot of times that push notifications do not receive - although there is no error message.

Have any one of you had similar problems with that? 

When starting our API, we do the following to initialize the APN connection:

```
var apnOptions = {
    cert: config.push.certFile,
    key: config.push.keyFile,
    production: config.push.production
};
var apnConn = new apn.Connection(apnOptions);

apnConn.on('transmissionError', function(type, notification, device) {
    var error = underscore.invert(apn.Errors)[type];
    logger.error('Error on sending iOS push notifications: ' + error, device);
});
```

To later send a push we do:
```
var tokens = recipients.map(function (user) {
        return user.push_token;
    });
    if (!tokens.length) {
        return;
    }
    var notification = new apn.Notification();
    notification.expiry = Math.floor(Date.now() / 1000) + config.push.expiresSeconds; // set to 1 day
    notification.badge = 1;
    notification.sound = 'default';
    notification.alert = message;
    apnConn.pushNotification(notification, tokens);
```

I know that Apple does not give feedback whether it was delivered or not, but I hope that we're doing something wrong and the reliability can be improved.

**Comment by argon** [comment]
I can't seen anything obvious wrong there. The only thing i could suggest is adding an event handler for `socketError` just in case there's anything going wrong there.
