### ISSUE TITLE
Crash on lib/connection

### ISSUE THREAD

**Issue by guytuboul** [argon/node-apn#269]
The crash is:

ERR! 2015-05-21T07:13:24.620Z APNS_SOCKET_ERROR {}
ERR! 2015-05-21T07:13:29.082Z APNS_CONNECTED  Open sockets :1
ERR! 2015-05-21T07:13:35.061Z APNS_CONNECTED  Open sockets :2
/media/ephemeral0/glide-server/node_modules/apn/lib/connection.js:202
				this.deferredConnection.resolve();
				                       ^
TypeError: Cannot read property 'resolve' of null
    at Connection. (/media/ephemeral0/glide-server/node_modules/apn/lib/connection.js:202:28)
    at TLSSocket.g (events.js:199:16)
    at TLSSocket.emit (events.js:104:17)
    at TLSSocket. (_tls_wrap.js:950:16)
    at TLSSocket.emit (events.js:104:17)
    at TLSSocket._finishInit (_tls_wrap.js:460:8)

Thank you very much

**Comment by argon** [comment]
Are you able to reliably reproduce the error or was it a one-off occurrence?

**Comment by guytuboul** [comment]
I can't reproduce it, but i saw this crash several times.
Any suggestion?

**Comment by argon** [comment]
I have some ideas, it'll take me a little while to find time to investigate, but I will look into it.

**Comment by guytuboul** [comment]
Thanks :)
