### ISSUE TITLE
Crash by Connection connectTimeout

### ISSUE THREAD

**Issue by sixmen** [argon/node-apn#270]
I saw an error log like this from my server.

```
TypeError: Cannot read property 'end' of undefined
  at Connection.<anonymous> (../node_modules/apn/lib/connection.js:223:15)
```

Line 223 is
```
  if (this.options.connectTimeout > 0) {
    var connectionTimer = setTimeout(function () {
      this.deferredConnection.reject(new Error("Connect timed out"));
      this.socket.end(); // <---- this line
    }.bind(this), this.options.connectTimeout);

    return this.deferredConnection.promise.finally(function() {
      clearTimeout(connectionTimer)
    }); 
  }
```

I don't know what is the real problem, but I hope it does not crash at least.

I think it can happen if initialize() runs longer than options.connectTimeout.

How about adding null-check before calling socket.end()?

**Comment by argon** [comment]
I'm pretty sure this is exactly the same root-cause as #269 and I think you're right. I'll get this sorted asap.
