### ISSUE TITLE
Module not sending push notification

### ISSUE THREAD

**Issue by josebldo** [argon/node-apn#271]
I am trying to send notifications, but they are not being sent. Here is my code:

	var apn = require('apn');
	var options = {
		production: true
	};
	apnConnection = new apn.Connection(options);
	apnConnection.on("connected", function (openSockets) {
		console.log("APN connected: " + openSockets);
		device = new apn.Device('484cfb1ce2e25a8b83a761fe9cebe73e67971c7600494d1e2fedeb33f383b16a');
		note = new apn.Notification();
		note.expiry = Math.floor(Date.now() / 1000) + 3600; // Expires 1 hour from now.
		note.badge = 3;
		note.sound = "ping.aiff";
		note.alert = "\uD83D\uDCE7 \u2709 You have a new message";
		note.payload = {'messageFrom': 'Caroline'};
		apnConnection.pushNotification(note, device);
	});
	apnConnection.connect();

Below is the output I get in debug mode:

    apn Initialising connection +0ms
    apn Initialising module +3ms
    apn Connection established +569ms
    APN connected: 1
    apn 1 left to send +3ms

After that, nothing happens.

**Comment by argon** [comment]
The connect() method should never be called directly.

Create the apn connection then immediately begin sending push notifications, the module takes care of setting up and tearing down the connections.


―A

**Comment by josebldo** [comment]
Thanks, that was it
