### ISSUE TITLE
Error: socket hang up when trying to send a notification

### ISSUE THREAD

**Issue by ricoharisin91** [argon/node-apn#272]
hello

i'm having a problem with this module and i almost give up with it
so i just recently deployed my script to handle a push notification to android and ios
for ios i'm using this module

the strange thing is, it worked perfectly until this morning and then suddenly it doesn't work anymore

here's the error when i use debug

    apn Initialising connection +1s
    apn 2 left to send +0ms
    apn Socket error occurred +772ms undefined { [Error: socket hang up] code: 'ECONNRESET', sslError: undefined }
    apn Destroying connection +1ms undefined
    apn Removing socket from pool +0ms undefined
    apn Socket closed +0ms undefined
    apn Removing socket from pool +0ms undefined
    apn 2 left to send +0ms
    apn Raising error: +1ms { [Error: socket hang up] code: 'ECONNRESET', sslError: undefined } undefined undefined
    apn Error occurred with trace: +0ms Error: socket hang up
    at SecurePair.error (tls.js:1011:23)
    at EncryptedStream.CryptoStream._done (tls.js:703:22)
    at CleartextStream.read [as _read] (tls.js:499:24)
    at CleartextStream.Readable.read (_stream_readable.js:341:10)
    at EncryptedStream.onCryptoStreamFinish (tls.js:304:47)
    at EncryptedStream.g (events.js:180:16)
    at EncryptedStream.emit (events.js:117:20)
    at finishMaybe (_stream_writable.js:360:12)
    at endWritable (_stream_writable.js:367:3)
    at EncryptedStream.Writable.end (_stream_writable.js:345:5)

i already generated a new key and cert but the problem is still there
even i tried to create a new instance server for my script and it's not solved anything!

any thought with it? 

thanks before!

**Comment by argon** [comment]
Are you running the latest version of the module?

―A

**Comment by ricoharisin91** [comment]
yep, i'm using the latest version which is 1.7.3 right?

**Comment by raza2022** [comment]
Error is: Error: socket hang up
Note undefined
am using latest version

**Comment by raza2022** [comment]
am using latest version and follow all steps regarding this module. any suggestion will be gretally welcome

**Comment by ricoharisin91** [comment]
solved already

it's turns out that my NODE_ENV was empty, and when i searching about it, i discovered that if NODE_ENV is empty it will use 'development' instead and i didn't set production flag to true on config because i expected the default flag which is production
