### ISSUE TITLE
Add a `minConnections` property

### ISSUE THREAD

**Issue by argon** [argon/node-apn#273]
If a connection is lost then it can take around 1 second to establish a new connection. If multiple connections are open and one is closed then the others can take up the slack. At present `maxConnections` is supported, but additional connections will only be created if there is a throughput bottleneck. This does not account for dropped connections and the associated latency. There should be a `minConnections` property to force several connections to be maintained simultaneously.

**Comment by guytuboul** [comment]
I will help to do it, and will make a pull request,so you can review.

**Comment by argon** [comment]
That would be great. Let me know if you need any assistance.

―A

**Comment by argon** [comment]
Fixed by #279
