### ISSUE TITLE
Support for new HTTP/2 provider API

### ISSUE THREAD

**Issue by florianreinhart** [argon/node-apn#277]
Apple announced a new provider API for APNs based on HTTP/2 at WWDC 2015. Currently, there is no written documentation, but it should be available in the coming weeks.

See this video starting at 20:50 for an introduction to the new API: https://developer.apple.com/videos/wwdc/2015/?id=720

Also see the slides starting at page 98: http://devstreaming.apple.com/videos/wwdc/2015/720xwbi9nl/720/720_whats_new_in_notifications.pdf?dl=1

**Comment by argon** [comment]
Thanks for opening this Florian, I hadn't got to that video yet. I will definitely be adding support for HTTP/2 and hopefully it should simplify a lot of the module.

―A

**Comment by argon** [comment]
Starting work on this in #278

**Comment by dezinezync** [comment]
If I'm not mistaken, Apple is yet to make the new HTTP/2 based API public?

**Comment by argon** [comment]
Correct, but there is enough information in the WWDC session for me to make a start and adjust it as new information becomes available

**Comment by dezinezync** [comment]
I believe the Feedback API has been removed and now a HTTP/2 push is used instead? Has this been implemented in the http2 branch yet? Or do we continue using the old method for now?

**Comment by florianreinhart** [comment]
That's correct. With the new HTTP/2 API there is no separate feedback service. If you send a notification to a disabled device, you will get an appropriate HTTP response in return.

I don't think the new HTTP/2 API is available yet.

**Comment by dezinezync** [comment]
@florianreinhart  Got it, just wanted to confirm. Thanks.

**Comment by argon** [comment]
The http2 branch is completely broken at the moment as I have ripped out all the old protocol code. I am using it to experiment with how I will build the http2 support going forward but as @florianreinhart says the protocol isn't live yet so I won't be able to do much until then.

―A

**Comment by dezinezync** [comment]
Hi @argon, Apple just made the docs public. 

Doc: https://developer.apple.com/library/ios/documentation/NetworkingInternet/Conceptual/RemoteNotificationsPG/Chapters/APNsProviderAPI.html#//apple_ref/doc/uid/TP40008194-CH101-SW1

**Comment by n3trino** [comment]
Any schedule when this will be released?

**Comment by argon** [comment]
Not yet. I'll do what I can but this is a personal project in my spare time so I can't make any promises about timescale

**Comment by dezinezync** [comment]
@argon You've already done some work on the `http2` branch. If you could tell how the certificates come into play (the only bit I have never managed to figure out), I could probably take a shot at this and if all is good, send a PR.

**Comment by argon** [comment]
The basics of certificate handling should already be in place. I should warn you though that I will be actively developing the HTTP/2 support, I simply can't provide an ETA

—A

**Comment by dezinezync** [comment]
@argon I see. Well then, I'll lend a helping hand where ever I can. Thank you.

**Comment by NoahAndrews** [comment]
Will the API to use this node module be any different for the http2 version?

**Comment by argon** [comment]
There will be at least a few breaking changes as the feedback service will now need to be integrated in the Connection instead of being separate. I will probably deprecate some old API so it may be a 2.0 I haven't decided yet. Any necessary changes should be very minor though. What are your thoughts on this?

**Comment by dezinezync** [comment]
The first thing that comes to my mind is utilizing `EventEmitter`s. 

That way, something like this should be possible and convenient:

```js
service.on("feedback", (evt) => { ... })

service.on("delivered", (evt) => { ... })

service.on("error" (evt) => { ... })

// and so on 
````

**Comment by argon** [comment]
Absolutely, that is similar to how the current version works within the limitations of the APNS protocol. The HTTP/2 protocol is has much better responses so event emitters will be more useful.

**Comment by dezinezync** [comment]
+💯

**Comment by jorisvervuurt** [comment]
FYI:
The HTTP/2 APNs provider API is now up-and running.
Documentation can be found here:
https://developer.apple.com/library/mac/documentation/NetworkingInternet/Conceptual/RemoteNotificationsPG/Chapters/APNsProviderAPI.html#//apple_ref/doc/uid/TP40008194-CH101-SW1

Any ETA as to when we can expect a first version that supports it? :)

**Comment by NoahAndrews** [comment]
@jorisvervuurt That link had already been posted, and just six days ago @argon said he couldn't provide an ETA.

**Comment by n3trino** [comment]
How things going on http2.0 APN?

**Comment by ekristen** [comment]
+1 any updates on this?

**Comment by florianreinhart** [comment]
This will probably take a while. It's turning out to be a complete rewrite. See https://github.com/argon/node-apn/pull/278.

**Comment by argon** [comment]
I am actively working on this. I hope to have something functional soon, with further improvements as fast as I can.

**Comment by argon** [comment]
@ekristen are you sure it's not possible to use a newly issued certificate with the current protocol?

**Comment by argon** [comment]
@ekristen I just created a new certificate in the developer portal. It was able to send a notification via the sandbox service with the current version of `node-apn` (1.7.5)

**Comment by dezinezync** [comment]
@ekristen @argon I can confirm the new certs work for both Sandbox and Production with the current source from the master branch.

**Comment by goldenice** [comment]
How far along are you with implementing the HTTP/2 API? I'm really interested in this :)

**Comment by argon** [comment]
I have the basics working now but it's not ready for production. Still need to add multi connection support and better error handling.

**Comment by goldenice** [comment]
Right, well, I'll be needing a module like this pretty soon for some production code, so if I can be of assistance in any way, let me know :)

**Comment by NasserAlmanji** [comment]
+1

**Comment by pratiknaik** [comment]
+1

**Comment by sveinhal** [comment]
Great work, @argon. It seems you are working alone on this, and everyone is waiting eagerly. Thanks for doing this! But please let us know if there is anything we can do to help! Can the work be split into smaller well-contained tasks, that can be assigned, and we can submit pull requests and review each others code?

**Comment by argon** [comment]
@sveinhal The foundation of the new code is nearly in place. There is much to do but the basics work now. I will be creating new issues for remaining tasks so we can work from there. I hope to make further progress this weekend.

**Comment by henry42** [comment]
I am also waiting, Thanks for doing this!

**Comment by airs0urce** [comment]
I'm waiting for new release too

**Comment by airs0urce** [comment]
@argon I appreciate your work. Have you a clue when HTTP/2 version will be released.

**Comment by ms88privat** [comment]
Keep up the good work 👍

**Comment by n3trino** [comment]
Any update on this one?

**Comment by uronly14me** [comment]
Thanks for working on!

**Comment by argon** [comment]
Released as v2.0.0

**Comment by NasserAlmanji** [comment]
great, thanks :)

**Comment by airs0urce** [comment]
Thank you for this big work you did

**Comment by n3trino** [comment]
You nailed it @argon 👍
