### ISSUE TITLE
content-available flag no longer working in v. 1.7.4

### ISSUE THREAD

**Issue by jeden** [argon/node-apn#280]
I implemented APN on my app, using version 1.7.3, and on my dev machine it worked. A few days ago I installed everything on my staging server, and I couldn't make background notifications to work - of course I thought something was wrong in either my code or the server configuration. Until I figured out that on the server version 1.7.4 was installed - I immediately reverted to the previous version, and everything worked just fine.

If it can help, during my endless debugging sessions, I tried dumping the notification object, and the `contentAvailable` flag was always undefined, even if set in the preceding line. I suspect that this is not the only non-working property... although I haven't tried anything else.

**Comment by argon** [comment]
Could you provide an example case where you're seeing the problem? This code is fully unit tested and I can't see any problems.

**Comment by jeden** [comment]
This is the code I am using to create a `Notification`:
```
APNProvider.prototype.toAppleNotification = function(notification) {
	var message = new apn.Notification();

	message.badge = notification.badge || undefined;
	message.sound = notification.sound || undefined;
	message.alert  = notification.alert || undefined;
	message.payload = notification.payload || undefined;
	message.contentAvailable = notification.backgroundNotification ? 1 : undefined;

	return message;
};
```

and then I use it in this method:

```
APNProvider.prototype.send = function(deviceToken, notification) {
	var device = apn.Device(deviceToken);
	var message = this.toAppleNotification(notification);

	console.log(message.contentAvailable); // This prints 'undefined'
	console.log('Sending push notification: ' + JSON.stringify(message) + ' to device ' + deviceToken);

	this.apnConnection_.pushNotification(message, device);
};
```

During the several debugging sessions I tried several things, like creating a `Notification` in place, setting the `contentAvailable` property only (either using a direct assignment or using the setter), with a `console.log` printing it in the next line - but the output didn't change, still showing `undefined`.

Note that the code as is works with 1.7.3

**Comment by argon** [comment]
I see what is wrong. The `contentAvailable` property should be set to `true`. It is documented as needing true, but the code changed recently to have stricter validation and it doesn’t support `1` now. I realise this probably isn’t good as it goes against the Apple spec for the payload. If you want to fix your code change the 1 to true. I will also add `1` as a valid value for the validation for the next release.
—A

**Comment by jeden** [comment]
Cool thanks - I'll check that out and I'll let you know.

**Comment by argon** [comment]
This should now be fixed on master

**Comment by jeden** [comment]
Thanks - I haven't tried yet cause in the meanwhile I am working on something else, but as soon as I get back to that feature I'll check it out.

**Comment by harryhorn** [comment]
I am using the latest version from nam and true works but 1 doesn't

**Comment by argon** [comment]
This is fixed in master but I have not had time to release a new version as I do this in my spare time. I will try to get something out soon.

**Comment by ronakvora** [comment]
It seems like you also can't set content-available to 0 using either false or 0. 

var device = new apn.Device(token);
  var note = new apn.Notification();
  note.expiry = Math.floor(Date.now() / 1000) + 3600; // Expires 1 hour from now.
  note.sound = "ping.aiff";
  note.alert = alert;
  note.badge = badge;
  note.payload = payload;
  note.category = "quickReplies";
  note.contentAvailable = false;
  console.log(note);
  apnConnection.pushNotification(note, device);

Here's the code. Am I doing something incorrectly?

**Comment by argon** [comment]
This will be fixed in the next version, I will publish soon.

―A

**Comment by ronakvora** [comment]
Awesome, thank you!

**Comment by ronakvora** [comment]
Sorry to spam, but any update on this?

**Comment by lunchbag** [comment]
Ping! Updates?
I have the following:

    note.badge = 1;
    note.sound = "ping.aiff";
    note.alert = prop.message;
    note.priority = 5;
    note.setContentAvailable(true); 
(I've also been trying note.contentAvailable = 1 or true)

on 'notification', I get: {"additionalData":{"analytics":{"platform":"ios"},"content-available":1,"foreground":true},"message":"Testing","count":1,"sound":"ping.aiff"}
which leads me to believe the content-available flag is being set properly.

However, event handler doesn't get hit when the app is backgrounded or my phone is locked. With priority=5, I only get it when my app is open (I read on APN docs that with content-available set to true, priority cannot be 10, which it is by default).

I've tried every combination possible of priority, content-available, as well as blanks/undefined for sound/alert/badge, but I can't seem to get the event handler to get called while the app is backgrounded.

Any insights much appreciated. Thanks!

**Comment by harryhorn** [comment]
@lunchbag this works fine for me with version apn version 1.7.5:
```
    var note = new apn.Notification();
    note.expiry = Math.floor(Date.now() / 1000) + 3600; // Expires 1 hour from now.
		note.contentAvailable = true;

		if (alert) {
	    note.badge = 1;
	    note.sound = "ping.aiff";
	    note.alert = alert;  			// "\uD83D\uDCE7 \u2709 You have a new message";			
			note.priority = 10;		// highest priority for followed by user
		} else {
			note.priority = 5;		// Note: priority 5 instead of 10 needed for contant-available per apple			
		}
		
		if (payload) {
	    note.payload = payload;		// {'messageFrom': 'Caroline'};
		}
```
