### ISSUE TITLE
When app uninstalled, sending notificaition does not fail if the connection is not reset

### ISSUE THREAD

**Issue by minal2709** [argon/node-apn#282]
I installed an app, sent a notification.
 -- Got the notification
 -- No error

I uninstalled the app, sent a notification.
 -- Did not get the notification
 -- **No error** //Unexpected

I restart the server, sent a notification.
 -- Did not get the notification
 -- Got an error

**Comment by argon** [comment]
This is not node-apn behaviour, it is using information passed by Apple so it is not a bug in the module.

―A

**Comment by minal2709** [comment]
But then how are we suppose to distinguish between a failed notif call and successful using this module?

**Comment by argon** [comment]
If there is a problem with the notification Apple will send an error code in response. Apple doesn't give positive confirmation so there's no way to be confident that the message has been successful, this is how Apple designed the protocol. This will change with the iOS 9 release but it has been this way for 5 years.

To detect devices which are uninstalled you must use the feedback service and not rely on error responses when sending payloads to the gateway.

―A

**Comment by minal2709** [comment]
Cool! Thanks
