### ISSUE TITLE
often APNS socketError

### ISSUE THREAD

**Issue by chelsh** [argon/node-apn#283]
Server-API-0 (err): 2015-07-08 16:50 +08:00: APNS socketError&&Error: Connect timed out
Server-API-0 (err): 2015-07-08 16:50 +08:00: APNS socketError&&Error: socket hang up

-------my code:
    service.on("socketError", function(err){
        console.error("APNS socketError&&"+err);
    });

**Comment by chelsh** [comment]
Server-API-0 APNS socketError&&Error: read ECONNRESET
Server-API-0 APNS socketError&&Error: read ECONNRESET

**Comment by chelsh** [comment]
-----my apn version:
  "name": "apn",
  "description": "An interface to the Apple Push Notification service for Node.js",
  "version": "1.7.4",

**Comment by argon** [comment]
Which hosting provider are you using? As the error says: the connection to Apple is timing out so there are likely network problems with your host.

―A

**Comment by chelsh** [comment]
host provider:ucloud in china


```
Which hosting provider are you using? As the error says: the connection to Apple is timing out so there are likely network problems with your host.

```

**Comment by chelsh** [comment]
can it automatic repeat connection  when it appear "Connect timed out"?

**Comment by argon** [comment]
I think by default it does, but only a limited number of times

―A
