### ISSUE TITLE
`transmissionError` event emitted right after `transmitted` event.

### ISSUE THREAD

**Issue by ddoria921** [argon/node-apn#284]
I'm having a problem where the node-apn library is firing off a `transmissionError` event immediately after firing off the `transmitted` event. 

The `transmissionError` is returning error code 8. In Apple's docs it says that error code 8 means I'm sending an invalid token, yet my notification was delivered.

Any thoughts?

**Comment by argon** [comment]
Do you mean the notification was received on the device?

**Comment by haozxuan** [comment]
i have this problem too,but after i restart process,it ok

**Comment by argon** [comment]
So the notification is received on the device and it is also being returned to the server with error code 8?

**Comment by haozxuan** [comment]
no, the notification is not send to device

**Comment by argon** [comment]
Then you are seeing the correct behaviour. Transmitted is sent after the notification has been sent to apple, the error indicates that apple have rejected the notification due to error and therefore it will not be delivered.

―A

**Comment by himasimplisafe** [comment]
> I'm having a problem where the node-apn library is firing off a `transmissionError` event immediately after firing off the `transmitted` event.
> 
> The `transmissionError` is returning error code 8. In Apple's docs it says that error code 8 means I'm sending an invalid token, yet my notification was delivered.
> 
> Any thoughts?

Can you please give Apple docs link where it is talking about error code 8.
