### ISSUE TITLE
Can't use production certificates, not even on the server

### ISSUE THREAD

**Issue by mehulpatel696** [argon/node-apn#286]

**Comment by mehulpatel696** [comment]
I actually got it to stop giving the error (I forgot to change the gateway link from sandbox to regular) , but now it doesn't actually send the notification. It doesn't give an error either.

**Comment by argon** [comment]
It sounds like you have solved the problem. The `gateway` and `address` parameters have been deprecated and you should exclusively use the `production` parameter to specify which environment to connect to as it will enable node-apn to validate your certificates, as you saw. I am aware the error messages aren't the best and I plan to improve them in a coming update.

As for the new problem you're seeing: the production server will only deliver notifications for a copy of the app installed from the App Store. I would have expected you to see an error - code 8. However, I understand there is total parity between the sandbox and production environments so if everything is working in the sandbox then you can switch to production and it will work correctly.

―A
