### ISSUE TITLE
APN retry question

### ISSUE THREAD

**Issue by behrad** [argon/node-apn#287]
I'm using node-apn to send APNS notifications, but can't find much details on APN QOS, so thought I could find some answers if I ask my question here:

I turn my phone offline, and send a push using node-apn (priority is 10), after I turning it on again, I don't receive any notifications, however I'll have caught it if my phone was online.

How can I control apple push server's retry? I'm using sandbox servers, do production servers make any difference on this? How other apps (telegram,viber,...) rely on APNs when their client get online after offline pushes?

P.S. very nice module, thanks guys.

**Comment by argon** [comment]
The QoS as promised by Apple could be described "best effort". The only two parameters available are `priority` and `expiry`. The expiry parameter will determine when Apple stops trying but there are no other ways that I know of to determine how it retries.

The answer about other apps is that they are doing the same thing, I can only assume that the production Apple servers exhibit higher reliability.

―A

**Comment by behrad** [comment]
thank you @argon Then can i use production servers within a development build? or Should I go for a test flight or Enterprise account !?

**Comment by argon** [comment]
You cannot.

I believe the only way to use production is when the app is on the App Store, or perhaps enterprise, but I don't know that for certain.

I don't believe it's worth going to that effort though. The ENTIRE purpose of the sandbox is for you to test your system, it doesn't make any sense that it would work in sandbox and not production. The entire API is the same, if there are any problems it won't be with anything you can change in your implementation so there is no value in production testing.

―A

**Comment by behrad** [comment]
thank you @argon
