### ISSUE TITLE
what you mean <1.7.2:> commit?

### ISSUE THREAD

**Issue by zhhxu2011** [argon/node-apn#288]
Hi, we are using 1.6.4 until now, but I found yesterday in our test environment that a connection to apns disconnected. And for a very long time about more than 1 hours, this connection still disconnected and never recover, so I restart the process. Does 1.6.4 have this problem?

By the way, we are considering your new commit. And i donot understand this changeLog
"1.7.2:
 only emit error when the problem is unrecoverable. Any use of node-apn should have an error listener attached to prevent uncaught exceptions."

Shoud we create a new connection to apns when we caught an "error" event ?

**Comment by argon** [comment]
If there is an `error` event then there is an error which cannot be recovered by creating a new socket.

An `error` event will happen if the certificate / key cannot be found, or there is a problem loading them. Creating a new socket would not solve this problem, therefore error is unrecoverable

**Comment by zhhxu2011** [comment]
ok, I know what you mean. And the other issue may also be illustrated, thanks !
