### ISSUE TITLE
Cannot access cert.pem and key.pem from non-root directory

### ISSUE THREAD

**Issue by yonasstephen** [argon/node-apn#291]
I'm following this tutorial: http://codesamplez.com/development/apple-push-notification-backend-nodejs

Everything works perfectly, until I move the cert.pem and key.pem files to non-root directory. The author also mentioned about this issue, is this really not achievable with node-apn?

Below the options that I changed in order to cater for the new certs location, the rest are the same as the tutorial.

````javascript
var path        = require('path');

var options = {
    "cert": path.join(__dirname, "/certs/cert.pem"),
    "key":  path.join(__dirname, "/certs/key.pem"),
    "passphrase": "***",
    "gateway": "gateway.sandbox.push.apple.com",
    "port": 2195,
    "enhanced": true,
    "cacheLength": 5,
};
````

Below is the error I got:

````
D:\Programming\Projects\cms\node_modules\apn\node_modules\q\q.js:155
                throw e;
                      ^
Error: ENOENT, open 'D:\Programming\Projects\cms\cert.pem'
````

I even console.log the options before init and got the correct directory as shown below:

````
{ cert: 'D:\\Programming\\Projects\\cms\\app\\apns\\certs\\cert.pem',
  key: 'D:\\Programming\\Projects\\cms\\app\\apns\\certs\\key.pem',
  passphrase: '***',
  gateway: 'gateway.sandbox.push.apple.com',
  port: 2195,
  enhanced: true,
  cacheLength: 5,
  errorCallback: [Function] }
````

I am using apn 1.7.4.

**Comment by arturkiulian** [comment]
@argon seems I'm not the only one getting this error...

**Comment by shafdog** [comment]
FWIW, I also have this issue. I tried using using a buffer as `key` and `cert` with no success. You can't even use a different name for `cert.pem` or `key.pem` even if they are in the root.

**Comment by argon** [comment]
Which operating system are you on? I have been using alternative certificate names a lot and never had this problem.

Any information you can share to help me reproduce the problem would be very helpful.

―A

**Comment by shafdog** [comment]
I get the following output after I do a `new Connection(options)`:
```
Error: ENOENT, open 'cert.pem'
  at Error (native)
```

Here are the details on my env:
`node -v`: v0.12.7
`node-apn` version: "1.7.4",
OS: Mac OS X 10.10

I've tried using Buffers, full-qualified paths, etc. for `key` and `cert` attributes, but here is the reduced set of code (in CoffeeScript) showing essentially what we're providing to `node-apn`:
```

  apnInitOptions = 
    gateway: 'gateway.push.apple.com'
    cert: 'push-key.pem'
    key: 'push-cert.pem' 

  apnService = new apn.Connection(apnInitOptions)

```

We've been using your code a while and its been working great. But we used the defaults, `cert.pen` etc in project root director...  But we're trying to implemented switching between production and sandbox cert/key in our code, which means I can't have two files name the same things. 

I did debug into `node-apn` far enough to know that it looks correct at the end of the constructor.

Let me know if there anything else to try, or you'd like to get.

**Comment by shafdog** [comment]
Here is what my debugger showed for the `this` within your `connection.js` at line ~127
 
```
connectionTimer: null
credentialsPromise: null
deferredConnection: null
failureCount: 0
notificationBuffer: Array[0]
notificationsQueued: false
options: Object
address: "gateway.push.apple.com"
autoAdjustCache: true
buffersNotifications: true
ca: null
cacheLength: 1000
cert: "/Users/ammo/src/acs/push-cert.pem"
connectTimeout: 10000
connectionRetryLimit: 10
connectionTimeout: 3600000
disableEPIPEFix: false
disableNagle: false
fastMode: false
gateway: "gateway.push.apple.com"
key: "/Users/ammo/src/acs/push-key.pem"
maxConnections: 1
passphrase: null
pfx: null
port: 2195
production: true
rejectUnauthorized: true
voip: false

```

The exception is un-handled currently so it crashes sometime after this.

**Comment by argon** [comment]
So I created and used the following code with the same versions as you and it works perfectly. The tests load certificates by path name also, could you try `npm test` within the node-apn directly and check that everything passes on your machine?

```js
var apn = require('apn');

var token    = ...; // iPad

var service = new apn.connection({
  cert: "/Users/argon/workspace/dev-node-apn/certificates/cert.pem",
  key:  "certificates/key.pem"
});

service.on("completed",         function()    { console.log("Completed!")});
service.on("connected",         function()    { console.log("Connected"); });
service.on('disconnected',      function()    { console.log("Disconnected", arguments); });
service.on('error',             function(err) { console.log("Standard error", err); });
service.on('socketError',       function(err) { console.log("Socket error", err.message); });
service.on('timeout',           function()    { console.log("Timeout"); });
service.on('transmissionError', function(err) { console.log("Transmission Error", err); });

service.on("transmitted", function(notification) {
    console.log("Transmitted");
});

var note = new apn.notification();
note.badge = 1;

service.pushNotification(note, token);
service.shutdown();
```

**Comment by shafdog** [comment]
Your code worked on my system.

Looked into further... As it turns out, it's the Feedback, not Connection, service was causing the exception to print and app to exit. Providing valid key/cert paths to *both* Feedback and Connection fixed my issues.

The reason why this was tricky to figure out is there is difference between in how Connection and Feedback handled errors that cause my confusion. I didn't construct a specific test case, but did some testing using my code to create failures. Connection seems to fail silently with an invalid path, while the Feedback service prints the error shown above and then exits in my case. I tried put try/catch around my `new apn.Feedback` code, but failed to catch the exception printed (perhaps because a callback function threw within node-apn's promise chains?).

@argon, you might want to try using invalid paths to a Feedback object since the failure mode is seemingly different from the Connection object, and the exception/stack-less output makes it tricky to track down. Obviously my bad for providing nonexistent file to Feedback service, but maybe some of the other bug reports are due to a similar cause. 

Now if you use the right paths, it works great. That a bunch for your help.

**Comment by argon** [comment]
Thanks so much for this investigation and write up. I have an item on my todo list to make errors raised by feedback distinct from the regular gateway and this problem confirms the need for that. I will definitely investigate the errors you suggest also as there probably shouldn't be a hard failure there.

Thanks again

―A

**Comment by guileen** [comment]
same issue, I even don't use a `cert` and `key`, I use `pfx`. I think must be some where load the default certificate error.

**Comment by guileen** [comment]
Fallback to 1.6 fixed.

**Comment by guileen** [comment]
Soryy, 1.6 still error

**Comment by guileen** [comment]
Finally I found the problem, I was misleading by the document:

```
var options = {
    "batchFeedback": true,
    "interval": 300
};

var feedback = new apn.Feedback(options);
feedback.on("feedback", function(devices) {
    devices.forEach(function(item) {
        // Do something with item.device and item.time;
    });
});
```

I used this snippet in README.  I use the same config as apnConnection, problem solved.

**Comment by argon** [comment]
If you encounter this problem please run your application with the environment variable `DEBUG=apn*`, for example:

```
DEBUG=apn* node app.js
```

The extra logging will provide information to identify the problem.

**Comment by ishika112** [comment]
Hi, Please could anyone let me know that how to create cert.pem and key.pem file?
Thanks
