### ISSUE TITLE
Alert set in two places

### ISSUE THREAD

**Issue by richardpenner** [argon/node-apn#294]
I'm creating a push notification with alert text that will occasionally be too long. After setting up the alert I call trim() with either 256 or 2048, depending on the user's iOS version.
I've noticed occasionally that the alert gets truncated unnecessarily, and upon inspecting the JSON, saw this (I've removed some properties for brevity, but the full object does get reduced to exactly 256 bytes):
```
{
    …
    "alert": "JohnQX also commented on Daniel's note: \"This is a test\"",
    "aps": {
        "badge": 4,
        "alert": "JohnQX also commented on D"
    }
}
```

I'm curious why the `alert` property is set in two places. The code that creates this push follows:

```
var myDevice 	= new apn.Device(iOSPushToken);
var note 		= new apn.Notification();

note.expiry 	= Math.floor(Date.now() / 1000) + 3600; // Expires 1 hour from now.
note.badge 		= badge;
note.alert 		= alert;
note.payload 	= payload;
if ( sound )
	note.sound = sound;

var maxLength = 256;
if ( pushTokenInfo.OSVersion && semver.valid(pushTokenInfo.OSVersion) && semver.gte(pushTokenInfo.OSVersion, "8.0.0") )
{
	maxLength = 2048;
}
note.trim( maxLength );

apnsConnection.pushNotification( note, myDevice );	
```

The alert seen by the user in this example is `"JohnQX also commented on D"`

**Comment by argon** [comment]
You don't need to switch between 256 and 2048 byte payloads. The 2KB payload is backwards compatible with older versions, it was a server limitation not OS.

Which version are you running?

**Comment by richardpenner** [comment]
Thanks @argon – I had no idea the limitation was only server-side. I'm running version 1.7.3 which I can see trims to 2048 by default.
I'm still curious, does this JSON having alert in two places make sense to you? Based on the sample dictionary mentioned in README.md it looks like it should only be in the `aps` key.

**Comment by argon** [comment]
I'm not clear on why the multiple payloads is happening at present.

A workaround is to use notification.setAlertText(). Let me know if that doesn't work

—A

**Comment by richardpenner** [comment]
I'll test that and get back to you. I noticed the docs seem to suggest that the larger payload is in fact dependent on client version. From [the docs](https://developer.apple.com/library/ios/documentation/NetworkingInternet/Conceptual/RemoteNotificationsPG/Chapters/ApplePushService.html#//apple_ref/doc/uid/TP40008194-CH100-SW1): 
```In iOS 8 and later, the maximum size allowed for a notification payload is 2 kilobytes; Apple Push Notification service refuses any notification that exceeds this limit. (Prior to iOS 8 and in OS X, the maximum payload size is 256 bytes.)```

**Comment by argon** [comment]
With the new API later this year it will support up to 4KB and apparently that is supported by all iOS versions:
> This year, we are doubling this to 4 kilobytes.
>
> [Applause]
>
> The 4 kilobyte limit will apply to all versions of iOS and OS X.
> 
> So it's not exclusive to iOS 9 or OS X, El Capitan.
>
> It will be part of the new provider API.

Source: http://asciiwwdc.com/2015/sessions/720

**Comment by richardpenner** [comment]
Wow that's really interesting. I just tested this and it does look like iOS 7 is allowing larger payloads, suggesting that they've made the change mentioned at WWDC but have not yet updated the docs.

As an aside, calling setAlertText() still sets the `alert` property in the root of the object as well as in the `aps` object.

**Comment by argon** [comment]
What does your `payload` object look like? If `alert` is set in there it will propagate into the notification

```
> var note = new notification()
undefined
> var alert = "Hello"
undefined
> var badge = 3
undefined
> var note = new notification()
undefined
> note.expiry     = Math.floor(Date.now() / 1000) + 3600; // Expires 1 hour from now.
1439489000
> note.badge      = badge;
3
> note.alert      = alert;
'Hello'
> note.compile()
'{"aps":{"badge":3,"alert":"Hello"}}'
```

**Comment by richardpenner** [comment]
You're right @argon. I have code re-using the payload between both Android and iOS, and I see now that in the Android branch of code an `alert` property is added to the payload, which is also used in the iOS code path and hence gets propagated to the outer object. Thanks for the help.
