### ISSUE TITLE
Timeouts to be expected?

### ISSUE THREAD

**Issue by richardpenner** [argon/node-apn#295]
Are timeouts to be expected when sending push? Since adding a handler for the `timeout` event on my `an.Connection`, I see timeouts quite regularly. From what I can tell, all push notifications are going out as expected. Should connections be closed, or is this just a natural part of a connection pool, and I should ignore these?

**Comment by argon** [comment]
Generally timeouts are not a concern. There have been problems in the past with connections being silently dropped which has resulted in notifications being lost when the OS doesn't pick up on the disconnection quickly enough. As a result node-apn will timeout connections after 1hr (configurable). If you believe all notifications are being sent it's nothing to worry about.

**Comment by richardpenner** [comment]
Thanks
