### ISSUE TITLE
Only one attempt - no retry

### ISSUE THREAD

**Issue by arnthorsnaer** [argon/node-apn#297]
Hi there

I have one issue and two questions. 

I want my apn push only to do one attempt in case of errors.

I've tried setting `connectionRetryLimit : 1`, which as expected causes a single retry in case of errors (in my cave a socket error). I then tried setting it to 0 but after looking at the connections.js code I noticed that the rejectBuffer/shutdown/terminated commands only get executed in cases where connectionRetryLimit > 0. Which makes sense when I thought about it.

I continued my search for disabling the retry on failure functionality. Reading the docs I noticed `buffersNotifications {Boolean} Whether to buffer notifications and resend them after failure.`  This seemed like a good candidate, I'd simply set it to false and there would be no retries on failure. But this did not help me and when thinking about it it does say resend, not retry.

1) Is there a way to not attempt a single retry in case of an error?
2) In the "completed" event, can I check if none, some or all notifications got sent to Apple?

**Comment by argon** [comment]
Hi,

I think I need to understand your reasoning behind not wanting to retry. What is your objective? What did `buffersNotifications: false` do that was inconvenient for you?

-A

**Comment by arnthorsnaer** [comment]
Hi argon and thx for the reply.

I am developing a client where end users will be able to send/push notifications to specific devices. I don't want them to wait for a few seconds. Either the notification is delivered or there is a problem (for example network issues). This is the reasoning for wanting to fail as fast as possible.

In some cases, there is probably a good reason for retrying / resending. I just wanted to get to know the behaviour of my users / APNs etc before creating UI to handle this.

>What did `buffersNotifications: false` do that was inconvenient for you?

Re `buffersNotifications:false`   It is not what it did, it's what it did not do. I thought it would result no retries after the first socketerror. However it had no effect on the retries. I am probably misunderstanding the buffersNotifications functionality.

**Comment by argon** [comment]
First and foremost I would recommend you read Apple's push notification docs carefully to understand what is and is not possible as wel as the recommended guidelines for interfacing with the service.

I can offer a few comments here as I think what you are attempting to do is mostly possible, but you are not approaching the problem correctly.

It sounds like you are trying to establish a connection to Apple every time you send want to send a notification. This is a terrible idea and goes against all of Apples guidelines. So many people make this mistake that I think I need to improve the docs. Regardless, a TLS connection can take ~1s to start whereas it is possible to keep a single connection connection open for long periods of time which could handle ~10000 notifications per second. 

In addition if you scale and you are still opening a new connection for every notification you will find that Apple bans your credentials fairly quickly and you will need to generate new certificates. I discovered this while doing various load tests and it took a while to figure out what had happened.

If you have a single connection that is (nearly) always open you will find that you can fail a lot faster but also that you won't fail very often at all if your application is sending proper notifications to valid devices. As such you definitely want to retry connections to ensure the connection stays open and can always serve your users.

buffersNotifications is probably also a good idea for you to keep enabled. If you send 5 notifications in quick succession and the second one is rejected then while the first will send correctly, 3,4 & 5 will be lost forever. With buffersNotifications enabled 3,4 & 5 will be resent in the time it takes to close and re-establish the connection (~2seconds).

What you probably want, is to disable the retries parameter on the notification object itself. Setting to to 0 will ensure the notification is only sent once.

> I am developing a client where end users will be able to send/push notifications to specific devices. I don't want them to wait for a few seconds. Either the notification is delivered or there is a problem (for example network issues). This is the reasoning for wanting to fail as fast as possible.



In some cases, there is probably a good reason for retrying / resending. I just wanted to get to know the behaviour of my users / APNs etc before creating UI to handle this.

What did buffersNotifications: false do that was inconvenient for you?
Re buffersNotifications:false It is not what it did, it's what it did not do. I thought it would result no retries after the first socketerror. However it had no effect on the retries. I am probably misunderstanding the buffersNotifications functionality.

**Comment by arnthorsnaer** [comment]
Thank you for your reply and your insight into this. I'll have to think about how this applies to my situation and my code. 

>What you probably want, is to disable the retries parameter on the notification object itself. Setting to to 0 will ensure the notification is only sent once.

I thought I had tried that, I'll retry this (pun intended) and get back to you.

**Comment by arnthorsnaer** [comment]
Hi again.

I have been giving it some thought. The thing is that none of my notifications will be triggered by an event or an action, all will be targeted to users and sent by people. So they will be few and far apart. On a busy day there will be perhaps 10 notifications send to 10-1000 recipients. 

Now what you said does make sense, my scaling is not tied to the number of users though. 

If I need to maintain an open connection to Apple / Google, I must have a dedicated service / server on my end to send notifications. Seeing as the notifications are few and far apart I figured that it was more safe to have my API controller action establish the connection as needed instead of maintaining the open connection. 

>you are still opening a new connection for every notification you will find that Apple bans your credentials fairly quickly and you will need to generate new certificates

A great point. I should try to avoid this. Thanks again for your advice on this.
