### ISSUE TITLE
should I create N feedback connections equals the number of Connections?

### ISSUE THREAD

**Issue by zhhxu2011** [argon/node-apn#298]
hi, recently. I have found much memory leaks when use node-apn

I maintain 10 connections with apns, and listen on "connected" event and create a feedback connection each time. And when the connection disconnected, in node-apn it auto maintain 10 connections, so the "connected" event may be more and more than 10, and the number of feedback connections also more than 10. Absolutely this may cause memory leak.

Does one feedback connection is ok? Thanks for your time

**Comment by argon** [comment]
You never want more than one feedback connection.

―A

**Comment by zhhxu2011** [comment]
thanks，and also I want to know whether node-apn have the risk of  memory leak ?

**Comment by argon** [comment]
I haven't heard any reports of memory leaks

—A
