### ISSUE TITLE
connection does not timeout

### ISSUE THREAD

**Issue by adamkalicinscy** [argon/node-apn#299]
Hi, i have problem with connection timeout.

Server is set with connectionTimeout set to 10000. Envirnoment is development sandbox. One message is sent to two devices. First one has fake token (changed last digit) and second has real token. Server starts sending message and after recieving error connection never timeout. When first token is real and second is fake, connection timeout is ok. Why is that 

sending ... [ '6f24d7cf48942f6e9223965664e306c048c5ff468bb49a03b0c74271fb7f3343',
  '6f24d7cf48942f6e9223965664e306c048c5ff468bb49a03b0c74271fb7f3344' ]
  apn Initialising connection +0ms
  apn Loading Credentials +1ms
  apn 2 left to send +2ms
  apn Connection established +3s
apn Connected
  apn Socket drained +108ms 0
Notification transmitted to:6f24d7cf48942f6e9223965664e306c048c5ff468bb49a03b0c74271fb7f3344
  apn 1 left to send +3ms
  apn Socket drained +8ms 0
Notification transmitted to:6f24d7cf48942f6e9223965664e306c048c5ff468bb49a03b0c74271fb7f3343
  apn 0 left to send +2ms
  apn 0 left to send +1ms
  apn Notification 1 caused an error: 8 +411ms
Notification caused error: 8 for device  { token: <Buffer 6f 24 d7 cf 48 94 2f 6e 92 23 96 56 64 e3 06 c0 48 c5 ff 46 8b b4 9a 03
 b0 c7 42 71 fb 7f 33 43> }
  apn Raising error: +5ms 8 { encoding: 'utf8',
  payload: { aps: { alert: 'message content' } },
  expiry: 0,
  priority: 10,
  retryLimit: -1,
  device: undefined,
  compiled: '{"aps":{"alert":"message content"}}',
  truncateAtWordEnd: false,
  _alert: 'message content' } { token: <Buffer 6f 24 d7 cf 48 94 2f 6e 92 23 96 56 64 e3
06 c0 48 c5 ff 46 8b b4 9a 03 b0 c7 42 71 fb 7f 33 43> }
  apn Buffering 0 notifications for resending +2ms
  apn Socket closed +796ms 0
  apn Removing socket from pool +2ms 0
Disconnected from APNS
  apn 0 left to send +2ms
And here server is waiting forever...

In this case when first token is ok timeout is also ok.

sending ... [ '6f24d7cf48942f6e9223965664e306c048c5ff468bb49a03b0c74271fb7f3344',
  '6f24d7cf48942f6e9223965664e306c048c5ff468bb49a03b0c74271fb7f3343' ]
  apn Initialising connection +0ms
  apn Loading Credentials +2ms
  apn 2 left to send +2ms
  apn Connection established +497ms
apn Connected
  apn Socket drained +104ms 0
Notification transmitted to:6f24d7cf48942f6e9223965664e306c048c5ff468bb49a03b0c74271fb7f3343
  apn 1 left to send +3ms
  apn Socket drained +2ms 0
Notification transmitted to:6f24d7cf48942f6e9223965664e306c048c5ff468bb49a03b0c74271fb7f3344
  apn 0 left to send +1ms
  apn 0 left to send +1ms
  apn Notification 0 caused an error: 8 +126ms
Notification caused error: 8 for device  { token: <Buffer 6f 24 d7 cf 48 94 2f 6e 92 23 96 56 64 e3 06 c0 48 c5 ff 46 8b b4 9a 03
 b0 c7 42 71 fb 7f 33 43> }
  apn Raising error: +4ms 8 { encoding: 'utf8',
  payload: { aps: { alert: 'message content' } },
  expiry: 0,
  priority: 10,
  retryLimit: -1,
  device: undefined,
  compiled: '{"aps":{"alert":"message content"}}',
  truncateAtWordEnd: false,
  _alert: 'message content' } { token: <Buffer 6f 24 d7 cf 48 94 2f 6e 92 23 96 56 64 e3 06 c0 48 c5 f
f 46 8b b4 9a 03 b0 c7 42 71 fb 7f 33 43> }
  apn Buffering 1 notifications for resending +2ms
  apn Socket closed +3ms 0
  apn Removing socket from pool +1ms 0
Disconnected from APNS
  apn Initialising connection +1ms
  apn 1 left to send +1ms
  apn Connection established +413ms
apn Connected
  apn Socket drained +102ms 1
Notification transmitted to:6f24d7cf48942f6e9223965664e306c048c5ff468bb49a03b0c74271fb7f3344
  apn 0 left to send +3ms
  apn 0 left to send +1ms
  apn Socket timeout +10s 1
Connection Timeout
info: connection timeout 10000

It is important for me to know when is timeout to end server proces and exit daily cron job. In first case process will never end. I have version 1.7.4

**Comment by argon** [comment]
Call `shutdown()` on the connection after all notifications have been passed to it (regardless of whether they have been transmitted)

―A

**Comment by adamkalicinscy** [comment]
You mean after call pushNotification?
My code is like this:

service.pushNotification(note, tokens);
service.shutdown();

and situation exactly is the same. There is no timeout. Server is waiting.

**Comment by argon** [comment]
The reason the first instance doesn't time out is because the socket has already disconnected (last 4 lines). It is strange that node does not exit. I will investigate.

**Comment by adamkalicinscy** [comment]
Do you know anything more about this? I'm stuck with it and I can not move on with the project.

**Comment by argon** [comment]
I have had this at the top of my todo list for a while but as I support this in my spare time it's difficult. I will do my best to look at it this week.

―A

**Comment by argon** [comment]
I am able to reproduce this problem. I will try to fix it ASAP.

―A

**Comment by argon** [comment]
Could you please try using the code on `master` and verifying that it is fixed for you?

**Comment by adamkalicinscy** [comment]
Yes it works good now. Could you please add it to npm?

**Comment by argon** [comment]
There is an outstanding issue I need to investigate before pushing to npm but I will try to do it soon.

―A

**Comment by adamkalicinscy** [comment]
What kind of error is it?

**Comment by argon** [comment]
I need to investigate #299 to verify everything is working before I can release.

**Comment by kanedauy** [comment]
Any news about this, I have the same issue

**Comment by argon** [comment]
I meant #304 not #299 in the comment above. A new release is now top of my list to get done.

**Comment by adamkalicinscy** [comment]
ok sorry for not responding long time. Everything works ok now. Thank you.
