### ISSUE TITLE
Feedback documentation claims device is a Buffer but in reality it's a Device

### ISSUE THREAD

**Issue by Zenorbi** [argon/node-apn#300]
In `doc/feedback.markdown` at the bottom:

[...] each containing the `time` returned by the server (epoch time) and the `device` a `Buffer` containing the device token [...]

But in reality the property `device` is a `Device` object. Is it a documentation or an implementation error? I'm asking because the pull request made [here](https://github.com/borisyankov/DefinitelyTyped/pull/5400) follows the documentation and I may need to patch the definition file.

**Comment by argon** [comment]
You're right, this is a documentation error, I must have missed it when the change was made.

―A

**Comment by Zenorbi** [comment]
Thank you, I made the appropriate modifications. Also, because the `device` is now a `Device`, the [examples/feedback.js:7](https://github.com/argon/node-apn/blob/355139721d996ebf24ba8ffe0bc98117ee0a5f12/examples/feedback.js#L7) is wrong in saying that to get the hex code of the device, you should call `device.toString("hex")`.
