### ISSUE TITLE
Same code local work, but not on server ?

### ISSUE THREAD

**Issue by Pana** [argon/node-apn#302]
I have write some simple code to send notification to IOS device as the guide, and it work on my local mac machine, but when i upload it to ubuntu server it did not work, the debug log seems nothing wrong, but can not receive the message 

```
apn Initialising connection +0ms
  apn Loading Credentials +3ms
  apn 1 left to send +5ms
  apn Connection established +939ms
Connected
  apn Socket drained +103ms 0
Notification transmitted to:6e6650ass2bafff7bf729ba2bb1337e23fdc7279e004b67dc01c3f4e2b71e0d6
  apn 0 left to send +1ms
  apn 0 left to send +1ms
```

does any body have come across the same issue ?

**Comment by argon** [comment]
Have you ensured that the process is running long enough to check for errors received from Apple?

**Comment by Pana** [comment]
Now i can get the notification, not do any changing, i think maybe there are some issue when we build the app, or one failed notification send has block the later ones.
