### ISSUE TITLE
Not receiving any push notification in iPhone and apns reports no errors

### ISSUE THREAD

**Issue by dkjessn** [argon/node-apn#303]
Not receiving any push notification in iPhone and apns reports no errors neither when establishing a connection nor when sending messages

Please have a look at the url below 

http://stackoverflow.com/questions/32246163/apns-messages-are-delivered-but-not-received-on-ios-device

Thanks in advance

**Comment by argon** [comment]
This doesn't appear to be an issue related to node-apn
