### ISSUE TITLE
RoundRobin no send push

### ISSUE THREAD

**Issue by throrin19** [argon/node-apn#304]
Hi, after your next update, apn does not works. We received the transmitted notification on EventEmitter but phones do not received push.
I rollback the apn version of my project and it works fine.

**Comment by argon** [comment]
Do you mean you tried the code on `master`?

**Comment by throrin19** [comment]
I try the code of the last release in `npm`

**Comment by argon** [comment]
The code in npm worked, right? But the GitHub code does not?

―A

**Comment by argon** [comment]
Several others and myself have been using the latest `master` code without issue. I am going to create a new release, if you continue experiencing problems please open an issue or send me an email and I will help you get it fixed.
