### ISSUE TITLE
APN Update notification

### ISSUE THREAD

**Issue by marcoocram** [argon/node-apn#305]
Hi!

I'm having a problem with apple push notifications, if i send two or more notifications, this is accumulate in the device, its possible to have only one notification on device and if i send another one, update this? (like android does with "notId").

Thanks!!

**Comment by argon** [comment]
This is not something that Remote notifications will handle for you automatically.

You may be able to achieve the same effect by using `UILocalNotification` from within your app. Send your push notification with all the information you need within the payload, but not in the `alert` property and with the `content-available` flag set. This should then load your app in the background. At this point you will receive the payload and can construct a `UILocalNotification` to appear with the payload information.

The next time this happens you can clear any local notifications which will hide them if they are currently being shown.

**Comment by marcoocram** [comment]
Thanks! i will try ;)
