### ISSUE TITLE
Using fastlane PEM getting error

### ISSUE THREAD

**Issue by pieisgood** [argon/node-apn#306]
After creating my pem file with fastlane I try to send a testing notification to my test device. But I keep getting "Error: certificate does not support configured environment, production: false", same for production: true. 

Fastlane generates a .p12, .pem and a .pkey file for APNS certification. I can't get this to work.

**Comment by argon** [comment]
Could you please email me a copy of your certificate PEM without the public key so I can see what might be going wrong.

Thanks

―A

**Comment by pieisgood** [comment]
Things have actually been fixed, changed my env variable to production, removed production val from options and this issue has vanished. Thanks for the fast response though.
