### ISSUE TITLE
set interval to undefined in Feedback.prototype.cancel

### ISSUE THREAD

**Issue by isayme** [argon/node-apn#307]
Since `clearInterval` would not change value of `this.interval`, we should set `this.interval` to `undefined`  manually.

**Comment by argon** [comment]
Could you be a little more specific about the problem here?

**Comment by isayme** [comment]
if someone call `Feedback.prototype.cancel` N times, `clearInterval` will be called N times. because we never set `this.interval` to undefined, so `this.interval !== undefined` will always be true.
