### ISSUE TITLE
node-apn - only last message goes through when sending multiple messages to same device

### ISSUE THREAD

**Issue by ajiratech2** [argon/node-apn#308]
Hello ,

I am testing node-apn on my development server. I was successfully able to send the push message rather quickly. I do need to send messages that may be larger than 2048 bytes and so was planning on building a logic where I break them into chunks of 2K and then run them through a loop and send them out via node-pan. 

But when I do a quick test with a message of size > 2048, it successfully goes through. My app logic is not complete yet so I am not able to see the message in its entirety and am not sure how long a message did I receive.

Can you please point me to towards documentation on how node-apn handles this ? Is there a upper limit of messages that node-apn is able to split 

Thanks in advance.
Pankaj

**Comment by argon** [comment]
Apple doesn't guarantee delivery off all notifications. If two notifications are sent to Apple and the second one is processed before the first one is sent to the device then the first one will be discarded.

The Apple documentation states the quality of service - they offer no guarantees that notifications will be delivered. It sounds like you are building a system which depends on reliable delivery so I think you need to re-evaluate your options.

―A
