### ISSUE TITLE
Multiple notfication success

### ISSUE THREAD

**Issue by minal2709** [argon/node-apn#311]
I have 3 ids registered for my mobile and notificaition to all of them are a success.! Its not throwing error 8 anymore?

**Comment by argon** [comment]
Is there something I can help you with here?

**Comment by minal2709** [comment]
@argon yea.! So for this one device, i had 3 ids. I tried sending notifications to all 3 and i expected to get 2 of them from the feedback service. Since obviously only one id was active. But i got nothing from the feedback service.

**Comment by argon** [comment]
The feedback service can take a little while to start replying with ids. It should happen eventually.

―A
