### ISSUE TITLE
How can I count the number of successful and error sending times?

### ISSUE THREAD

**Issue by KahiroKoo** [argon/node-apn#312]
I can send message to the device I wish by this project, but I have no idea how to count the number of successful or error sending times. I had tried to count it when 'completed' was emited, but coming out the 'transmissionError' was emited later then 'completed' status. Then, I tried to use feedback service as well, but it alwasy return empty array to me.

**Comment by argon** [comment]
"Success" is a very vague term with Push Notifications. Why do you need to count the number of successes and what are you trying to accomplish with those figures?

―A
