### ISSUE TITLE
Success / fail callback?

### ISSUE THREAD

**Issue by liuzhen2008** [argon/node-apn#314]
I see in the code that we can attach a errorCallback to the notification object itself.

But do we have a success callback somewhere? Or is the code running synchronously in connection#pushNotification?

I needed it to wrap the connection#pushNotification into a promise.

**Comment by argon** [comment]
The transmitted event exists on connection, but that does not indicate the notification was successful, only that it was sent to Apple. Apple do not provide indication of success, only failures.

If a notification was sent to Apple but triggers an error, then a transmitted event will occur as well as the errorCallback being called.

―A

**Comment by liuzhen2008** [comment]
I see. And i assumed that the errorCallback will be fired asynchronously.

uh that is annoying to deal with.

**Comment by argon** [comment]
Yeah, the new protocol that Apple announced at WWDC should make for a better API but they haven't released the documentation yer

**Comment by liuzhen2008** [comment]
Cool, I guess i will keep an eye on the updates. Thank you so much for your help!
