### ISSUE TITLE
connont send any notifcation

### ISSUE THREAD

**Issue by MeshalALbshry** [argon/node-apn#316]
I'm following this code https://github.com/argon/node-apn/issues

and i have problem on terminal

<img width="314" alt="screen shot 2015-10-03 at 6 27 56 am" src="https://cloud.githubusercontent.com/assets/6430855/10261279/68415450-6998-11e5-9f83-392d50373ffa.png">
and my code 
<img width="832" alt="screen shot 2015-10-03 at 6 28 23 am" src="https://cloud.githubusercontent.com/assets/6430855/10261281/725fafc2-6998-11e5-80c3-abaa182238a9.png">

**Comment by argon** [comment]
Error code 8 indicates that the token you are using is incorrect.

**Comment by MeshalALbshry** [comment]
i'm sure i get the correct token

<img width="1191" alt="tokeen" src="https://cloud.githubusercontent.com/assets/6430855/10262207/289d983a-69c6-11e5-8cbf-07c618f93a14.png">

**Comment by argon** [comment]
Ensure your certificates are correct and for the correct App ID.

You appear to be generating the device token correctly but it must also match the environment (production true/false) and certificates. If they do not match you will get error 8

**Comment by MeshalALbshry** [comment]
thanks it's works
