### ISSUE TITLE
what is the number of times we can open and close connections to apn in a day??

### ISSUE THREAD

**Issue by vamzz1** [argon/node-apn#317]
Is there any limit to the number of times we can open and close connections to apn, before its considered as denial of service attack by apn ??

**Comment by argon** [comment]
There probably is but Apple don't publish anything. What sort of numbers do you have in mind?

―A

**Comment by vamzz1** [comment]
About 500-1000 times a day, and with each connection to varying number of devices

**Comment by argon** [comment]
I would certainly recommend keeping connections open once you reach that sort of number.

What do you mean "to varying number of devices"? Are you using different certificates?

You only need one connection per certificate which you can keep open and push to any number of devices. You can add more connections as you need to send higher volumes, but there should be no need to close and reopen for different devices.

―A

**Comment by vamzz1** [comment]
Thank you for the information. Ive got some idea on how to proceed.
