### ISSUE TITLE
Multiple pieces of data at the same time push, received multiple messages to the same content will become

### ISSUE THREAD

**Issue by samblabla** [argon/node-apn#319]
![37937779b51328c9642385df46bd7deb](https://cloud.githubusercontent.com/assets/3224632/10449127/066b558a-71c4-11e5-8e5f-dc26ff78f942.png)
<img width="806" alt="2015-10-13 3 30 37" src="https://cloud.githubusercontent.com/assets/3224632/10449128/06925cfc-71c4-11e5-8c98-1a67879b0b42.png">

**Comment by argon** [comment]
could you please explain the problem you're having

**Comment by samblabla** [comment]
@argon  When multiple pieces of information are sent simulataneously, they show as one same piece in the APP.

**Comment by samblabla** [comment]
@argon When using multiple processes when there is "transmission Error" error, the content server push four messages received on the mobile phone will become the same content 4

master.js

var fork = require("child_process").fork;
var cpus = require("os").cpus();
var cpus_num=cpus.length;
var forks={};
for(var i = 0;i<cpus_num;i++){
	forks[i] = fork("./test_worker.js");
}


function sendWorker(message){

							console.log('message:' , message);

							if(token.length >0){
								var step_len = Math.floor( token.length / cpus_num);
								for(var i = 0;i<cpus_num;i++){
									if( i+1 == cpus_num){
										forks[i].send({code:'push',data:message,num:i,tokens:token.slice(i*step_len) })

									}else{
										forks[i].send({code:'push',data:message,num:i,tokens:token.slice(i*step_len,(i+1)*step_len) })
									}

								}
							}
}


test_worker.js

process.on("message",function(m){
	if( m.code == 'push' ){

		var message =  m.data;
		note.alert = message.title;
		note.payload = message.action;


		var token =m.tokens;
		if(token.length >0){
			token.forEach(function (v) {
				try{

					var myDevice = new apn.Device(v);
					apnConnection.pushNotification(note, myDevice);

				}catch( err ){
					console.log(err );
				}


			});
		}
	}
});

**Comment by samblabla** [comment]
When using a single process when there is "transmission Error" error, the content server push four messages in the last one only receive

**Comment by samblabla** [comment]
Have this problem when the program has just started

**Comment by argon** [comment]
Can you explain what you're trying to accomplish with the sendWorker function, the code doesn't make any sense to me.

**Comment by samblabla** [comment]
@argon  How to set the heartbeat?

**Comment by samblabla** [comment]
When multiple notifications simultaneously push, 'socketDrained' push notifications are the same notification

**Comment by argon** [comment]
Are you reusing the same `apn.Notification` object or creating a new one every time?
