### ISSUE TITLE
socketError problem

### ISSUE THREAD

**Issue by haozxuan** [argon/node-apn#320]
![image](https://cloud.githubusercontent.com/assets/8748015/10480405/9f9097ec-729c-11e5-9a15-6d56165b0f31.png)

apn config is default, i have two problem;
1. this problem is about apple push notice server ?
2. apn can recove connection?
:)

**Comment by argon** [comment]
How often are those errors occurring?

—A

**Comment by haozxuan** [comment]
![image](https://cloud.githubusercontent.com/assets/8748015/10481140/5c6e0c10-72a1-11e5-8589-4beff2626a08.png)

**Comment by argon** [comment]
Does it ever work or do you only get those errors?

—A

**Comment by haozxuan** [comment]
yes, it work. but when throw socket error, it doesn't work. beside, i often have a lot of transmissionError. like that:
![image](https://cloud.githubusercontent.com/assets/8748015/10482355/25ae7d96-72aa-11e5-89d4-fce1712b429d.png)

**Comment by argon** [comment]
Transmission error 8 means the device token is invalid and Apple will then disconnect. The module will reconnect if there are more notifications to send. If it is working properly then the errors are for information only. You should use the feedback service to reduce the number of expired tokens and cut down "8" errors

—A

**Comment by haozxuan** [comment]
i will add feedback and cut invalid token, try again.
BTW,this is my push logic demo.
![image](https://cloud.githubusercontent.com/assets/8748015/10502795/435338a0-7322-11e5-9756-219b3b16d5b5.png)

i want to know the module can reconnect in my way ?

**Comment by argon** [comment]
That looks as though it should work correctly.

**Comment by haozxuan** [comment]
yeah, but not work well.  it block after send three notices, so i change to like that.
![image](https://cloud.githubusercontent.com/assets/8748015/10506160/5b805a3c-7347-11e5-8df3-9a3bea512a6f.png)

**Comment by argon** [comment]
Ok, and does it work now?

You're not giving me much explanation to work with.

**Comment by haozxuan** [comment]
yes, it work well. Thanks a lot for you :+1:
