### ISSUE TITLE
Possible to use without key file? My pem file allready with key data inside

### ISSUE THREAD

**Issue by omnicode** [argon/node-apn#321]
Hi. I have only one pem file without key. It's possible to send push without it? Thank you.

**Comment by argon** [comment]
No, the connection will not be established without the key as that it what proves your identity to Apple. Are you sure the PEM file doesn't contain the key also? It's possible for PEM files to contain more than one entity.

**Comment by omnicode** [comment]
Yes it's inside pem file. Not sure how to export it to additional file. Try to copy "RSA PRIVATE KEY" did't work out.

**Comment by argon** [comment]
You should be able to point node-apn at the same file for both `cert` and `key` options and it will pick the correct values.

**Comment by omnicode** [comment]
Already try it

node_modules/apn/node_modules/q/q.js:155
                throw e;
                ^

Error: error:0906A068:PEM routines:PEM_do_header:bad password read...
=======
Certificate are good, it work fine in php script.

**Comment by argon** [comment]
That error indicates the key has a passphrase associated with it or at least OpenSSL thinks it does. It would be best to extract the key and see if that fixes it:

openssl rsa -in cert.pem -out key.pem

**Comment by omnicode** [comment]
It's work. A little strange, because i am allready try to export key the same way. Maybe mistake in command like. Thanks :)
