### ISSUE TITLE
iOS push notifications stop working after 15 minutes on Azure VMs

### ISSUE THREAD

**Issue by MattiusMatt** [argon/node-apn#322]
Hi, I am running node-pushserver (which I have updated to use the latest node-apn version) on Ubuntu 14.04.3 LTS. After about 10-15 minutes push notifications just stop working. There are no errors in the console and the apn console messages suggest the message has been sent.

Further to that running from webstorm on windows never stops working, so I cant even recreate it to debug it!

Apart from this issue this is perfect for the app I am launching near Christmas, any insight would be greatly appreciated!

**Comment by dhatawesomedude** [comment]
Do you have an onError event listener?

**Comment by MattiusMatt** [comment]
There is an apnConnection.on('transmissionError', onTransmissionError); handler, should I add an 'onError' handler too?

The project and code I am using that uses node-apn is here...

https://github.com/Smile-SA/node-pushserver/blob/master/lib/APNPusher.js

However I have slightly tweaked a local copy to be more in line with the node-apn documentation!

**Comment by MattiusMatt** [comment]
I have now added the additional logging as seen in this example...

https://github.com/argon/node-apn/blob/master/examples/sending-to-multiple-devices.js

I'm hoping this might shed some light on the issue :)

**Comment by dhatawesomedude** [comment]
I had transmission error and I realised I could only get the error code. onError lets me print stack trace, sheds more light. What error message do you get?

     ios_connection.on('error', function(error) {
    console.log(error, error.stack);
  });

**Comment by MattiusMatt** [comment]
I've added the world of logging (including yours)... I'll let you know when it stops working (roughly about 15 minutes in)!

**Comment by MattiusMatt** [comment]
Its stopped... nothing logged any different to successful sends... Here is my entire log...

  apn:socket Using legacy socket API +0ms
  express:application booting in development mode +0ms
  connect:dispatcher use / query +5ms
  connect:dispatcher use / expressInit +1ms
  connect:dispatcher use / compress +2ms
  connect:dispatcher use / bodyParser +13ms
  connect:dispatcher use / static +2ms
  connect:dispatcher use / anonymous +0ms
  connect:dispatcher use / router +0ms
  express:router defined post /* +1ms
  express:router defined post /subscribe +1ms
  express:router defined post /unsubscribe +0ms
  express:router defined post /send +0ms
  express:router defined post /sendBatch +1ms
  express:router defined get /users/:user/associations +0ms
  express:router defined get /users +0ms
  express:router defined delete /users/:user +1ms
Listening on port 8000...
  connect:dispatcher query +16s
  connect:dispatcher expressInit +0ms
  connect:dispatcher compress +1ms
  connect:dispatcher bodyParser +1ms
  connect:dispatcher static +4ms
  connect:dispatcher anonymous +0ms
  connect:dispatcher router +1ms
  express:router dispatching POST /send (/send) +0ms
  express:router matched post /* +1ms
  express:router matched post /send +1ms
  apnfb Starting feedback service +17s
  apnfb Cancelling feedback interval +0ms
  apnfb Feedback service interval set at: 3600 +0ms
  apnfb Performing feedback request +1ms
  apnfb Initialising connection +1ms
  apnfb Loading Credentials +0ms
  apn Initialising connection +5ms
  apn Loading Credentials +0ms
  apn 2 left to send +2ms
  apn:socket connecting to:  +96ms feedback.sandbox.push.apple.com:2196
  apn:socket connecting to:  +13ms gateway.sandbox.push.apple.com:2195
  apn Connection established +716ms
Connected
  apnfb Connection established +7ms
  apnfb Resetting connection +2ms
  apnfb Emitting 0 feedback tokens +1ms
Feedback service, number of devices to remove: 0
Device Infos: []
  apn:trace connection established +92ms 1
  apn:trace create completed +0ms 1
  apn Socket drained +2ms 0
Notification transmitted to:312c5e4c1b42fc20832aca2a1c30a3f4ffadf9bc7812a6c2948ef3fa9374056b
  apn 1 left to send +1ms
  apn Socket drained +1ms 0
Notification transmitted to:16a8a6420218730151e2c273669d802cde5670d4d07156a71468c7fa3b520d09
  apn 0 left to send +1ms
  apn 0 left to send +0ms
  connect:dispatcher query +2m
  connect:dispatcher expressInit +0ms
  connect:dispatcher compress +1ms
  connect:dispatcher bodyParser +0ms
  connect:dispatcher static +2ms
  connect:dispatcher anonymous +0ms
  connect:dispatcher router +0ms
  express:router dispatching POST /send (/send) +0ms
  express:router matched post /* +1ms
  express:router matched post /send +0ms
  apn Socket drained +2m 0
Notification transmitted to:312c5e4c1b42fc20832aca2a1c30a3f4ffadf9bc7812a6c2948ef3fa9374056b
  apn 1 left to send +0ms
  apn Socket drained +5ms 0
Notification transmitted to:16a8a6420218730151e2c273669d802cde5670d4d07156a71468c7fa3b520d09
  apn 0 left to send +1ms
  apn 0 left to send +1ms
  connect:dispatcher query +2m
  connect:dispatcher expressInit +0ms
  connect:dispatcher compress +0ms
  connect:dispatcher bodyParser +0ms
  connect:dispatcher static +1ms
  connect:dispatcher anonymous +0ms
  connect:dispatcher router +1ms
  express:router dispatching POST /send (/send) +0ms
  express:router matched post /* +0ms
  express:router matched post /send +1ms
  apn Socket drained +2m 0
Notification transmitted to:312c5e4c1b42fc20832aca2a1c30a3f4ffadf9bc7812a6c2948ef3fa9374056b
  apn 1 left to send +1ms
  apn Socket drained +5ms 0
Notification transmitted to:16a8a6420218730151e2c273669d802cde5670d4d07156a71468c7fa3b520d09
  apn 0 left to send +47ms
  apn 0 left to send +2ms
  connect:dispatcher query +5m
  connect:dispatcher expressInit +0ms
  connect:dispatcher compress +1ms
  connect:dispatcher bodyParser +0ms
  connect:dispatcher static +1ms
  connect:dispatcher anonymous +0ms
  connect:dispatcher router +1ms
  express:router dispatching POST /send (/send) +0ms
  express:router matched post /* +0ms
  express:router matched post /send +1ms
  apn Socket drained +5m 0
Notification transmitted to:312c5e4c1b42fc20832aca2a1c30a3f4ffadf9bc7812a6c2948ef3fa9374056b
  apn 1 left to send +1ms
  apn Socket drained +5ms 0
Notification transmitted to:16a8a6420218730151e2c273669d802cde5670d4d07156a71468c7fa3b520d09
  apn 0 left to send +1ms
  apn 0 left to send +3ms
  connect:dispatcher query +19s
  connect:dispatcher expressInit +1ms
  connect:dispatcher compress +0ms
  connect:dispatcher bodyParser +0ms
  connect:dispatcher static +0ms
  connect:dispatcher anonymous +1ms
  connect:dispatcher router +0ms
  express:router dispatching POST /send (/send) +0ms
  express:router matched post /* +0ms
  express:router matched post /send +1ms
  apn Socket drained +19s 0
Notification transmitted to:312c5e4c1b42fc20832aca2a1c30a3f4ffadf9bc7812a6c2948ef3fa9374056b
  apn 1 left to send +1ms
  apn Socket drained +3ms 0
Notification transmitted to:16a8a6420218730151e2c273669d802cde5670d4d07156a71468c7fa3b520d09
  apn 0 left to send +0ms
  apn 0 left to send +1ms

**Comment by MattiusMatt** [comment]
The last two messages yielded nothing on my iPhone, everything else worked! Am I missing something?

**Comment by MattiusMatt** [comment]
Hold the phone!!! I left it running and I've just had this...

  apn Socket error occurred +6m 0 { [Error: read ETIMEDOUT] code: 'ETIMEDOUT', errno: 'ETIMEDOUT', syscall: 'read' }
{ [Error: read ETIMEDOUT] code: 'ETIMEDOUT', errno: 'ETIMEDOUT', syscall: 'read' }
  apn Raising error: +3ms { [Error: read ETIMEDOUT] code: 'ETIMEDOUT', errno: 'ETIMEDOUT', syscall: 'read' } null undefined
  apn Error occurred with trace: +1ms Error: read ETIMEDOUT
    at errnoException (net.js:901:11)
    at TCP.onread (net.js:556:19)
  apn Destroying connection +0ms 0
  apn Removing socket from pool +1ms 0
  apn Initialising connection +0ms
  apn:socket connecting to:  +2ms gateway.sandbox.push.apple.com:2195
  apn Socket closed +2ms 0
  apn Removing socket from pool +0ms 0
Disconnected from APNS
  apn 0 left to send +1ms
  apn Connection established +434ms
Connected
  apn:trace connection established +102ms 2
  apn:trace create completed +0ms 1
  apn 0 left to send +1ms

**Comment by MattiusMatt** [comment]
hmmmm... I think this issue might be to do with the "connectionTimeout": 600000 I added, I was hoping this would at least cause the server to reestablish a working connection, but it still doesn't work even after the timeout! code has ran. Once this thing stops sending to my iPhone... that's it until I kill the process and run it again!

**Comment by MattiusMatt** [comment]
I have now implemented the apn module directly in my application based on the git page... same problem! So its nothing to do with the node_pushserver wrapper module!

The apn module just doesn't seem to work on Ubuntu! :(

**Comment by argon** [comment]
I'm happy to investigate but it won't be until next week as I have no net access this weekend.

—A

**Comment by MattiusMatt** [comment]
That would be awesome :)

I could potentially give you access to my server where the issue is happening! It's just odd there are no clues about this issue from the logs!

**Comment by argon** [comment]
I'll get back to you next week and we can arrange access if necessary

—A

**Comment by argon** [comment]
From my investigations so far it appears as though Azure aggressively closes idle sockets in their network infrastructure which does not get detected by the VM until much later on. I was able to reproduce your problem and when I attempted to set the timeout to 600s (10 minutes) I see the same ETIMEDOUT and subsequent notifications were delivered. However I think Azure drops connections in less than 10 minutes so notifications can still be lost. 

@MattiusMatt Could you try setting the `connectionTimeout` to 60000 (1 minute) and see if that helps? It resolved the problem in my testing.

I should also point out that the project being used in this case https://github.com/Smile-SA/node-pushserver depends on a very old version of node-apn (1.3.8). When I updated that to the latest (1.7.5) it seemed to resolve the problem, but not for everyone apparently.

It seems as though the connection timeout is the offender in this case.

**Comment by MattiusMatt** [comment]
Hi,

I'm using V0.10.25 on my version of Ubuntu as that's what it installed from
the apt-get. I have tried various timeouts but I don't think I ever tried
as low as a minute 😊 I will update my config tomorrow and let you know how
I get on! I will also try and change the timeouts in Azure!

Thanks for investigating, this library is really easy to use and if I can
nail this issue perfect for our server!

**Comment by argon** [comment]
Did you manage to get anywhere with this?

**Comment by MattiusMatt** [comment]
Yes, I managed to set it up last night! I removed my code to kill and
restart the server after every message and replaced it with the one minute
timeout.

It appears to have fixed the problem! Thanks for your help on this issue 😊
well don Azure for silently killing connections and causing all these
problems for me!!

Your help was very much appreciated!

Mattius
