### ISSUE TITLE
Push doesn't wake up screen

### ISSUE THREAD

**Issue by richardpenner** [argon/node-apn#323]
I'm seeing a strange push issue where, although the push notification arrives successfully on my phone, it doesn't wake up my phone screen. When I wake my screen I see the push exactly as expected. My phone is not in Do Not Disturb mode, and push notifications from other apps do wake up the screen as expected.
I've added logging to the various APN connection events, and the logs show this:
```
2015-10-16T18:35:06.593Z - trace: Connected to APN
2015-10-16T18:35:06.695Z - trace: Transmitted push notification
2015-10-16T18:35:06.695Z - trace: Completed push notification
```
Which is what I'd expect. The payload is simple:
```
{
    "aps": {
        "badge": 3,
        "alert": "test at 2:35"
    }
}
```
Lastly, to help debug, as described in Tech Note 2265 I've installed the APN debugging configuration profile, but the only thing logged when I send a push notification is this curious error:
```
Oct 16 14:35:07 Richards-iPhone-6 SpringBoard[61] <Warning>: No image found for recordID 2015-10-16 18:35:06 +000002dd82169145ba3b5 yet we're being asked for a scale
```
which happens every time I send the push. I have experienced this for the past few months, and only with my own app. Any ideas?

**Comment by argon** [comment]
Could it be a missing small app icon which is normally shown on the alert?

—A

**Comment by richardpenner** [comment]
The app icon is there and shows up beside the push text. Worth noting too is that other devices I test show the push (with app icon) and light up the screen as expected.

**Comment by argon** [comment]
There's nothing in the notification which could affect that as far as I'm aware, it sounds like something has happened to your phone specifically.

—A

**Comment by richardpenner** [comment]
I'll close this, and post back here if I get to the source of the problem. Thanks @argon.
