### ISSUE TITLE
512 Error gets raised when retryLimit = 0 and a transmitError occurred on a batch with more than one notifications

### ISSUE THREAD

**Issue by liuzhen2008** [argon/node-apn#325]
In my framework, i have a retrying system myself.

Each time i push a notification, i set the retryLimit on the notification object to be 0. If somehow there is an error, couple minutes after I will generate another notification object with same content and retry 0 to be sent again.

Recently we made a mistake on the server certificate. So pretty much all the notifications we sent (to the sandbox) will get an invalid token error.

Looking at the logs, I am seeing a lot of 512 errors logged by the connection#errorCallback..

So my question is.. does that mean if there is any error that triggers connection#bufferNotification for a notification with retryLimit = 0, a 512 error will be raised by connection?

**Comment by argon** [comment]
Error 512 indicates that the retry limit was exceeded.

**Comment by liuzhen2008** [comment]
@argon But I set the retryLimit to be 0. So it will still attempt to retry? What is the difference between setting it as 0 or -1 ?

In the document it says that -1 will disable retry. So it is equivalent to 0 retry?

**Comment by argon** [comment]
You are right, there is some undocumented behaviour here. In this case the disabled behaviour is working in an unexpected way. retryLimit: 0 indicates it will retry 0 times. This has the same overall effect as disabling except the errors are still emitted. You can work around this by ignoring 512 errors in your code as it is apparently meaningless for you anyway.

Feel free to issue a pull request to fix the behaviour or edit the title of this issue to reflect the problem.

—A

**Comment by liuzhen2008** [comment]
@argon Do you know if retryLimit = -1 will ever get into an infinitely loop? I guess if it is safe to do I will just use that instead of my own retry.

**Comment by argon** [comment]
I don't understand your question.

**Comment by liuzhen2008** [comment]
Question 1:

From what I understand from the code, retryLimit = -1 will keep trying to send the notifications when there is a transmissionError.

I wonder if it is possible that a notification which can cause a transmissionError may get sent again if it has a retryLimit of -1.

Question 2:

Will one notification be sent twice in case an error occurred?
When a transmissionError does occur when we are sending more than one notifications, will APNs ignore all the notifications sent in the batch? Because it looks like all the notifications in the apnCachedNotifications are retried.

Sorry for all the questions... I'm really new to these things.

**Comment by argon** [comment]
1. Notifications which have a transmissionError will never be retried. The retryLimit applies to notifications sent after a failed notification which Apple discard and therefore will need to be resent. 

A retry limit of -1 will allow a notification to be resent an infinite number of times to ensure that it is sent, regardless of how many notifications before it fail.
A retry limit of 1 would mean that if 1 notification before it fails then it will be resent, but if a second notification before it fails then it will be discarded after that second failure.

2. As mentioned above, any notifications sent after a failed notification are discarded so they need to be sent a second time. There shouldn't be any duplicates with this method.

I'm not a huge fan of the retryLimit behaviour, it's kind of weird, but I received a number of requests for it. I would recommend leaving the retryLimit as the default and let the module take care of sending after failure.
