### ISSUE TITLE
Getting Socket error and socket hangup

### ISSUE THREAD

**Issue by Sriram-27727** [argon/node-apn#327]
Hi, 
I am getting error in the console like

Socket error socket hang up
Socket error Connect timed out
Disconnected  { '0': 0 }
and some times i got transmission Error 515
 
I can't find where the problem is. Here below my code

  var certPem = fs.readFileSync(__dirname + '/certificates/cert.pem');
  var keyPem = fs.readFileSync(__dirname + '/certificates/key.pem');
  var ca = fs.readFileSync(__dirname + '/certificates/entrust_2048_ca.cer');
  var options = {
    cert: certPem,
    key: keyPem,
    ca:ca,
    production: true

  };
  var apnConnection = new apn.Connection(options);

  apnConnection.on("completed", function() {
  console.log("Completed !!");
  });
  apnConnection.on('disconnected', function() {
     console.log("Disconnected !", arguments);
  });
  apnConnection.on('error', function(err) {
   console.log("Standard error !", err);
  });
  apnConnection.on('socketError', function(err) {
    console.log("Socket error!", err.message);
  });
  apnConnection.on('timeout', function() {
    console.log("Timeout!");
  });
  apnConnection.on('transmissionError', function(err) {
    console.log("Transmission Error!", err);
  });

  setInterval(function() {
          var myDevice = new apn.Device("0e21f86bdac8802f7e78832e81e3f571f45b7fee54234962e7642047bffd354d64");
          var note = new apn.Notification();

          note.expiry = Math.floor(Date.now() / 1000) + 3600; // Expires 1 hour from now.
          note.badge = 3;
          note.alert = {
            title: "title",
            body: "The traffic is busy in this route. Please take another"
          };

          apnConnection.pushNotification(note, myDevice);

  }, 60000);

Please can anybody help me.

**Comment by argon** [comment]
Where are you hosting this code? It appears to be a network problem

**Comment by Sriram-27727** [comment]
We hosted in Amazon Web Server. SomeTimes Notifications are firing. But Most of the times getting socket error, socket hangup, timedout ,disconnected and later getting Transmission Error 515 and Transmission Error 514

**Comment by argon** [comment]
Is there any pattern to when notifications fire? If you restart the app and the notification works will they continue working, or do they stop sending while the app is running?

**Comment by Sriram-27727** [comment]
I am sending push notification for every two minutes for testing purpose, Initially it is showing socket errors after some (1 or 2 hours) time notifications are sending to the device fine but Later if  restart the server for any reason  it again shows the same socket errors most of the time
.

**Comment by argon** [comment]
That definitely sounds like a network problem to me.

**Comment by Sriram-27727** [comment]
We are doing it on aws instance. How about tryig the same in a fresh instance? Will that work?

**Comment by argon** [comment]
You could try that, which region are you hosting in?

**Comment by Sriram-27727** [comment]
Asia's Pacific, Singapore

**Comment by Sriram-27727** [comment]
I Have one more doubt, For the first time It's getting connected(fires connected event).Then It works fine. If any server restart happens it's not reconnecting again and i am getting errors.So I commented (disable) certificate files and after restart as usual it shows error like
========================================================
Transmission Error! 513
Standard error ! { [Error: ENOENT, open 'cert.pem'] errno: 34, code: 'ENOENT', path: 'cert.pem' }
1
Socket error! ENOENT, open 'cert.pem'
Completed!!
=========================================================
 Later I'm recommenting (enabling the certificates) the  certificaticate files. Then only it is connecting.

**Comment by argon** [comment]
How often are you establishing a connection to Apple?

**Comment by Sriram-27727** [comment]
Hi argon, Finally we found that issue is with server instance we have deployed, So after we deployed with instance notifications are coming, without errors thanks.

**Comment by RahulSarkar1992** [comment]
Hi Sriram, I am also getting the same error, can you please tell me how I can solve it?

**Comment by Sriram277** [comment]
HI @RahulSarkar1992 , It was the problem with the AWSinstance which we created. After we changed that it works without issues.
