### ISSUE TITLE
Error 10

### ISSUE THREAD

**Issue by haozxuan** [argon/node-apn#328]
hi argon 

  I'm glad you can pay attention to this issue, i catch a error ,code 10. i fond "apnsShutdown": 10 in lib/error.js ,but i don't quite understand this mean. is apns shut down server? or other mean?

**Comment by argon** [comment]
It indicates that the APN gateway is shutting down and needs to close the connection. To continue sending notifications node-apn needs to reconnect. It is not an error which you usually need to worry about.

**Comment by haozxuan** [comment]
thank you again, will node-apn can reconnect by itself? should i need do something? or ,i have to do like this:
apnConnection.on("transmissionError", function (errorCode, notification, device) {
    console.error('[job server] transmissionError is ', errorCode, notification, device);
    //目前只能对无效token进行有效过滤
    if (errorCode === 8) {
        var token = device.toString().replace(/(.{8})(?=.{8})/g, "$1 ");
        MongodbClient.updateIosPushToken(mg4, [token], function (err, num) {
            if (err) {
                console.error('update token false. err is', err);
                return false;
            }
            console.log('update %d invalidToken success.', num);
        });
    } else if (errorCode === 8) {
        process.kill(process.pid);
    }
});then, pm2 can restart push process.

**Comment by haozxuan** [comment]
thank you again, will node-apn can reconnect by itself? should i need do something? or ,i have to do like this:
apnConnection.on("transmissionError", function (errorCode, notification, device) {
    console.error('[job server] transmissionError is ', errorCode, notification, device);
    //目前只能对无效token进行有效过滤
    if (errorCode === 8) {
        var token = device.toString().replace(/(.{8})(?=.{8})/g, "$1 ");
        MongodbClient.updateIosPushToken(mg4, [token], function (err, num) {
            if (err) {
                console.error('update token false. err is', err);
                return false;
            }
            console.log('update %d invalidToken success.', num);
        });
    } else if (errorCode === 8) {
        process.kill(process.pid);
    }
});then, pm2 can restart push process.

**Comment by argon** [comment]
node-apn will always reconnect when a transmissionError occurs.

If you kill the process like that you will lose notifications.

**Comment by haozxuan** [comment]
node-apn have retry times? because my process is blocked. is this Restart exceed the upper limit?

**Comment by argon** [comment]
Could you please provide more explanation, I don't understand your question.

**Comment by haozxuan** [comment]
of course, i use node-apn send notice for ios, i received some transmissionError, for example, code = 8, or code = 10. when code = 8, i deal invalidToken and the process continue work well. but when code = 10, i find the process can't continue work and blocked.  when apn shut down, can node-apn reconnect? or need myself. to do something ?

**Comment by argon** [comment]
Error 10 is treated in exactly the same way as error 8. If error 8 reconnects correctly there is no reason an error 10 would not. Could you share more of your code showing

1. How you are creating the apn Connection
2. How you are now handling the errors

**Comment by haozxuan** [comment]
```
/**
 * Created by 10000489 on 2015/7/20.
 */
'use strict';

var apn = require('apn');
var async = require('async');
var MongodbClient = require('../connect/mongodb');
var redisConnect = require('../connect/redis');
var brain = require('../tool/brain');
var conf = require('../conf/config');
var Key = require('../conf/configKey');
var mg2 = conf.mongodb.mg2;
var mg4 = conf.mongodb.mg4;

var apnConnection = new apn.Connection({maxConnections: 10, minConnections: 3});

var jobRedis = {
    ip: process.argv[2],
    port: parseInt(process.argv[3])
};
var jobInfo = {
    ip: process.argv[4],
    port: parseInt(process.argv[5]),
    type: 'JNode',
    id: 'jn_' + process.argv[4] + '_' + process.argv[5]
};
var client;

brain.add(jobInfo.type, jobInfo.id, jobInfo.ip, jobInfo.port);

redisConnect.connect(jobRedis.port, jobRedis.ip, function (_client) {
    client = _client;
    dealPushNotifyJobs();
});

function dealPushNotifyJobs() {
    client.select(0, function () {
        client.brpop('pushStack', 0, function (err, job) {
            dealPush(JSON.parse(job[1]));
        });
    });
}

function dealPush(notice) {
    async.waterfall([
        function (cb) {
            MongodbClient.findPushSetting(mg2, notice, cb);
        }, function (filtered, cb) {
            if (filtered) return cb(null, {});
            MongodbClient.findIosPushToken(mg4, notice.uid, cb)
        }
    ], function (err, res) {
        if (err) {
            console.error('[job server] find mongodb false, err is', err);
            return false;
        }
        //因为web端安卓用户也有token，而ios端token为64+7空格
        if (res.token && res.token.length === 71) {
            sendNotification(notice, res.token, res.hiddenPushMsg);
        } else {
            dealPushNotifyJobs();
        }
    });
}

function sendNotification(notice, token, hidden) {
    var notify = new apn.Notification();
    notify.sound = "default";
    notify.expiry = Math.floor(Date.now() / 1000) + 3600 * 5;//推送5小时后失效
    notify.device = new apn.Device(token.replace(/\s/g, ""));
    notify.badge = notice.count;
    notify.alert = hidden ? "你收到一条新消息" :
        (notice.message.length < 50 ? notice.message : notice.message.slice(0, 50) + "...");
    notify.payload = {
        aps: {
            content: {
                "poster"  : notice.poster,
                "userkind": notice.userkind
            }
        }
    };
    //1 2 3 为群组类型，4 5 6 为用户类型
    if (notice.userkind <= 3) notify.payload.aps.content.togroup = notice.groupId;
    apnConnection.pushNotification(notify, notify.device);
    dealPushNotifyJobs();
}

apnConnection.on("connected", function (openSockets) {
    console.log('[job server] @__@!connected is ', openSockets);
});

apnConnection.on("transmitted", function (notification, device) {
    //console.log('notification is', notification.toJSON());
    //console.log('device is', device.toString());
});

apnConnection.on("disconnected", function (openSockets) {
    console.log('[job server] $__$!disconnected is ', openSockets);
});


apnConnection.on("err", function (err) {
    console.error('[job server] err is', err);
});

apnConnection.on("socketError", function (err) {
    console.error('[job server] socketError err is', err);
});

apnConnection.on("cacheTooSmall", function (sizeDifference) {
    console.error('cacheTooSmall is ', sizeDifference);
});

apnConnection.on("transmissionError", function (errorCode, notification, device) {
    console.error('[job server] transmissionError is ', errorCode, notification, device);
    //目前只能对无效token进行有效过滤
    if (errorCode === 8) {
        var token = device.toString().replace(/(.{8})(?=.{8})/g, "$1 ");
        MongodbClient.updateIosPushToken(mg4, [token], function (err, num) {
            if (err) {
                console.error('update token false. err is', err);
                return false;
            }
            console.log('update %d invalidToken success.', num);
        });
    }
});

//每五分钟获取一次feedback
var feedback = new apn.Feedback({interval: 300});
feedback.on("feedback", function (devices) {
    if (!devices.length) return true;

    //数据库中token均为每8字符加空格格式，故转换token格式
    devices = devices.map(function (item) {
        return item.device.toString("hex").replace(/(.{8})(?=.{8})/g, "$1 ");
    });

    MongodbClient.updateIosPushToken(mg4, devices, function (err, num) {
        if (err) {
            console.error('[job server] feedback update token false. err is', err);
            return false;
        }
        console.log('update %d invalidToken success.', num);
    });
});
```

**Comment by argon** [comment]
How often do you see error 10 occurring? I have tried your code and I agree it works correctly when error  8 occurs. There is no difference in connection handling in node-apn between error 8 and error 10 so I do not understand why the process would block. Could you please run your service with `DEBUG=apn,apn:trace` set and post the log output when error 10 occurs, including the messages before and after the error so I can see what is happening.

**Comment by haozxuan** [comment]
ok, but apn shut down is not often broken. so I can not guarantee that can be displayed immediately. 
i guess, node-apn have some count number of count reconncet false. if have no retry times, node-apn would block?

**Comment by argon** [comment]
There is a connection retry limit of 10. If it is exceeded then a socketError event is emitted. You can disable this by passing `connectionRetryLimit: 0` in the options and see if that helps.

**Comment by haozxuan** [comment]
Thank you very much so careful to explain. I will continue to focus node-apn module :)
