### ISSUE TITLE
error 8 while sending notifications: Using Sandbox certificates and passing production: false parameter

### ISSUE THREAD

**Issue by egupta171** [argon/node-apn#330]
I get the following error:

apn Initialising connection +0ms
  apn Loading Credentials +2ms
  apn 1 left to send +1ms
env is development
  apn Connection established +582ms
  apn Socket drained +102ms 0
  apn 0 left to send +1ms
  apn 0 left to send +0ms
  apn Notification 0 caused an error: 8 +85ms
  apn Raising error: +0ms 8 { encoding: 'utf8',
  payload:
   { messageFrom: 'Caroline',
     aps:
      { badge: 3,
        sound: 'ping.aiff',
        alert: 'You have a new message',
        'url-args': undefined,
        category: undefined } },
  expiry: 1447280950,
  priority: 10,
  retryLimit: -1,
  device: undefined,
  compiled: '{"messageFrom":"Caroline","aps":{"badge":3,"sound":"ping.aiff","alert":"You have a new message"}}',
  truncateAtWordEnd: false,
  _badge: 3,
  _sound: 'ping.aiff',
  _alert: 'You have a new message' } { token: <Buffer d8 48 99 0f 17 ba 04 bb 35 14 f4 f6 c4 fd f9 66 b8 71 bb 65 77 28 c7 8e ec 36 a4 4b 8a 7d 74 08> }
  apn Buffering 0 notifications for resending +1ms
  apn Socket closed +1ms 0
  apn Removing socket from pool +0ms 0
  apn Initialising connection +0ms
  apn 0 left to send +0ms
  apn Connection established +254ms
  apn 0 left to send +100ms

And here is my nodejs code:

var iphone = "D848990F17BA04BB3514F4F6C4FDF966B871BB657728C78EEC36A44B8A7D7408";
var myDevice = new apn.Device(iphone);

var note = new apn.Notification();

note.expiry = Math.floor(Date.now() / 1000) + 3600; // Expires 1 hour from now.
note.badge = 3;
note.sound = "ping.aiff";
note.alert = "You have a new messaewege";
note.payload = {'messageFrom': 'Caewroline'};

var options = {
    passphrase : 'xxxx',
    production : false
};

var apnConnection = new apn.Connection(options);

apnConnection.pushNotification(note, myDevice);

**Comment by argon** [comment]
You are using a token which does not match the 

—A

**Comment by argon** [comment]
You are using a device token which does not match your certificate and environment. Double check your certificates and try again.

**Comment by egupta171** [comment]
Got this on running openssl x509 -text -noout -in cert.pem

Certificate:
    Data:
        Version: 3 (0x2)
        Serial Number: 2253733508346349197 (0x1f46deaf5f61068d)
    Signature Algorithm: sha1WithRSAEncryption
        Issuer: C=US, O=Apple Inc., OU=Apple Worldwide Developer Relations, CN=Apple Worldwide Developer Relations Certification Authority
        Validity
            Not Before: Nov 11 13:51:51 2015 GMT
            Not After : Nov 10 13:51:51 2016 GMT
        Subject: UID=com.brandistapp.applicationonex, CN=Apple Development IOS Push Services: com.brandistapp.applicationonex, OU=6Z9C79FW8P, C=US
        Subject Public Key Info:
            Public Key Algorithm: rsaEncryption
                Public-Key: (2048 bit)
                Modulus:
                    00:de:27:a5:b3:ae:88:a8:4f:ba:26:db:21:55:91:
                    5b:33:d4:df:f2:a6:94:25:f9:f5:c8:d2:e2:3b:a1:
                    c3:15:ab:e1:c9:b9:8d:b7:c1:f6:7e:28:63:f5:cb:
                    77:e6:1f:27:66:0e:97:02:bd:6f:05:29:a3:4b:ce:
                    23:2f:41:4b:55:76:10:4d:77:3d:c2:2f:05:08:d2:
                    47:f7:5b:df:29:47:9b:91:ee:f4:97:e1:5f:1a:5d:
                    cf:58:79:7b:82:f5:94:e6:be:5c:6f:9a:a4:da:1f:
                    e1:71:e1:04:99:5a:89:a2:0a:2d:3d:68:a7:15:09:
                    7c:f5:ef:c5:5c:89:15:9f:3e:42:85:7e:38:86:51:
                    93:61:87:04:58:37:85:ad:da:11:76:62:31:d2:62:
                    35:08:a9:3b:9f:ef:05:83:7c:a1:e6:eb:f6:80:bf:
                    1c:c2:e7:b2:28:d1:79:30:b4:5d:89:3a:ea:67:96:
                    56:35:6c:61:58:7a:46:cf:ef:c9:ff:eb:b3:98:b3:
                    66:f8:7f:87:14:19:bb:a0:9f:63:a8:97:0d:26:e2:
                    28:12:85:1c:29:46:a4:ea:3b:d4:e4:33:3f:9e:87:
                    46:6a:a7:90:29:c3:0f:30:f0:fe:ff:10:e1:69:8a:
                    c6:33:46:6c:57:7b:49:91:b9:21:ce:c7:a1:e3:43:
                    2b:91
                Exponent: 65537 (0x10001)
        X509v3 extensions:
            X509v3 Subject Key Identifier:
                89:A2:BB:FE:C0:53:6E:2D:10:C6:54:35:87:BC:29:85:91:F9:B8:0C
            X509v3 Basic Constraints:
                CA:FALSE
            X509v3 Authority Key Identifier:
                keyid:88:27:17:09:A9:B6:18:60:8B:EC:EB:BA:F6:47:59:C5:52:54:A3:B7

            X509v3 Certificate Policies:
                Policy: 1.2.840.113635.100.5.1
                  User Notice:
                    Explicit Text: Reliance on this certificate by any party assumes acceptance of the then applicable standard terms and conditions of use, certificate policy and certification practice statements.
                  CPS: http://www.apple.com/appleca/

            X509v3 CRL Distribution Points:

                Full Name:
                  URI:http://developer.apple.com/certificationauthority/wwdrca.crl

            X509v3 Key Usage:
                Digital Signature
            X509v3 Extended Key Usage:
                TLS Web Client Authentication
            1.2.840.113635.100.6.3.1:
                ..
    Signature Algorithm: sha1WithRSAEncryption
         5f:f1:71:15:bf:80:11:5b:ac:72:48:16:ad:33:f7:76:97:9b:
         1a:28:27:db:7b:b3:4d:57:64:df:90:e9:5f:dd:12:78:a5:03:
         4d:52:c5:f7:b8:39:cd:f8:1c:68:9c:b4:c8:c6:dc:46:da:78:
         a1:fe:ce:36:f1:b3:cb:b4:75:18:91:0e:04:70:2b:18:ed:b4:
         bc:de:8c:5e:35:15:9b:2d:ee:09:e2:ce:ed:c7:9b:f9:21:f5:
         d8:be:f4:61:9d:6c:24:8d:92:86:b8:91:17:3f:56:18:9b:9b:
         4c:01:34:24:56:99:1b:64:13:8a:e4:34:e9:e1:98:29:a0:b2:
         66:f2:7a:68:d3:a3:7c:58:4c:16:89:05:a6:62:54:8d:b6:7b:
         b1:c5:37:f8:18:e1:73:cc:e3:fe:62:d2:a0:83:5b:6f:90:3b:
         50:37:94:e8:64:2e:ae:de:02:4e:61:60:c6:4d:f6:b0:27:28:
         72:87:26:c2:95:7a:57:ca:39:3b:95:4f:88:aa:a6:c0:9e:44:
         b9:f2:3f:1e:40:b3:6a:bb:63:31:c7:ec:40:6e:46:30:1c:72:
         a9:1d:61:98:4a:00:0f:d7:13:b3:b1:8d:cb:99:04:64:fa:8a:
         ac:3b:94:76:c0:da:e2:ab:2e:1e:62:3f:3e:83:ef:85:6d:8c:
         6e:10:03:e1


Bundle ID is same as the application's. Is there something I am doing wrong ?

**Comment by egupta171** [comment]
Ok, got the error. I forgot to enable push notifications in the build capabilities. Thanks for the help ! :)
