### ISSUE TITLE
How to send MDM commands to push an app to iOS device

### ISSUE THREAD

**Issue by pravinraj** [argon/node-apn#332]
Hi,
I need to push an app through MDM commands. 
With .net to install an app, MDM command is 

< key>RequestType</key><string>InstallApplication</string><key>ManifestURL</key><string>https://domain//static/z21e6gwewUJSflzPFAAFCYQIF6iv0eOtiM5AjiCzE3k3S7Xc2AinK1ONm1jJ3h0O7CiDRNu23V0l_equal_l/ARG/ApplicationRepository/app-102/iPad/1.0.0/manifest.plist</string><key>ManagementFlags</key><integer>1</integer>

To remove app, the corresponding MDM command is 

<key>RequestType</key><string>RemoveApplication</string><key>Identifier</key><string>domainSomething.safespace</string>

How to implement the same with node-apn module? How to frame the commands? Does it should be XML format or it should be in JSON

Thanks,
Pravin

**Comment by argon** [comment]
This is not the correct place for this question. Please post on StackOverflow

**Comment by pravinraj** [comment]
Hi,
I have posted the same in stackOverflow. http://stackoverflow.com/questions/33781850/how-to-send-mdm-commands-to-push-an-app-to-ios-device-in-nodejs

Please let me know how to send the same in apn-payload.
