### ISSUE TITLE
Handling ECONNRESET issue and resend the past notification

### ISSUE THREAD

**Issue by mohit3081989** [argon/node-apn#334]
Hi,

In a day around 15-20 times, I get { [Error: read ECONNRESET] code: 'ECONNRESET', errno: 'ECONNRESET', syscall: 'read' } error, due to which some of the notifications get missed. I want to retry those notification. I have seen a lot related issue earlier but none seems to give proper answer for retrying failed messages. I have the errorCallback in place, but it seems apn doesn't send the notification and device info in errorCallBack, how can I retry it in case this happens ?

var apnsConnection = new apns.Connection(apnConfig);
apnConfig.errorCallback = function (err, msg) {
  console.log("APN ERROR : ", err, " s: ", msg);
}

apnConfig have all cert, key and production true variables in place. So its production code which is running fine, but in betweeen I get ECONNRESET errors, how to solve this issue ? I haven't touched retryLimit which is -1 by default and which means apn will retry infinitely. So basically I want to track such errors and resend the notifications for which this error encountered first.

**Comment by argon** [comment]
Have you configured a connectionTimeout value?

**Comment by mohit3081989** [comment]
Its the default one which I didn't touch. Its connectTimeout: 10000, by default

**Comment by argon** [comment]
When the connection timeout occurs do you see it connecting and disconnecting?

**Comment by mohit3081989** [comment]
For the next message it reconnects, and message gets delivered.

**Comment by mohit3081989** [comment]
As I said, occurrences is like avg 30per day in a week. But its directlt impacting production.

**Comment by mohit3081989** [comment]
My bad about connecting, disconnecting question, here are the frequency of error occurrence, I see that errors are happening in batches and at a particular time, below are the time and logs:

= 28 Nov 2015 10:29:53.522 2015-11-28T04:59:46.396Z info APN ERROR : { [Error: read ECONNRESET] code: 'ECONNRESET', errno: 'ECONNRESET', syscall: 'read' } s: null 
» 28 Nov 2015 10:29:53.616 2015-11-28T04:59:46.397Z info APN ERROR : { [Error: read ECONNRESET] code: 'ECONNRESET', errno: 'ECONNRESET', syscall: 'read' } s: null 
» 28 Nov 2015 10:29:54.486 2015-11-28T04:59:47.351Z info APN ERROR : { [Error: read ECONNRESET] code: 'ECONNRESET', errno: 'ECONNRESET', syscall: 'read' } s: null 
» 28 Nov 2015 10:29:54.608 2015-11-28T04:59:47.351Z info APN ERROR : { [Error: read ECONNRESET] code: 'ECONNRESET', errno: 'ECONNRESET', syscall: 'read' } s: null 
» 28 Nov 2015 10:29:55.503 2015-11-28T04:59:48.341Z info APN ERROR : { [Error: read ECONNRESET] code: 'ECONNRESET', errno: 'ECONNRESET', syscall: 'read' } s: null 
» 28 Nov 2015 10:29:55.562 2015-11-28T04:59:48.340Z info APN ERROR : { [Error: read ECONNRESET] code: 'ECONNRESET', errno: 'ECONNRESET', syscall: 'read' } s: null 
» 28 Nov 2015 10:29:56.314 2015-11-28T04:59:49.274Z info APN ERROR : { [Error: read ECONNRESET] code: 'ECONNRESET', errno: 'ECONNRESET', syscall: 'read' } s: null 
» 28 Nov 2015 10:29:56.351 2015-11-28T04:59:49.274Z info APN ERROR : { [Error: read ECONNRESET] code: 'ECONNRESET', errno: 'ECONNRESET', syscall: 'read' } s: null 
» 28 Nov 2015 11:13:22.793 2015-11-28T05:43:15.625Z info APN ERROR : { [Error: read ECONNRESET] code: 'ECONNRESET', errno: 'ECONNRESET', syscall: 'read' } s: null 
» 28 Nov 2015 11:13:22.829 2015-11-28T05:43:15.625Z info APN ERROR : { [Error: read ECONNRESET] code: 'ECONNRESET', errno: 'ECONNRESET', syscall: 'read' } s: null 
» 28 Nov 2015 11:28:12.628 2015-11-28T05:58:05.327Z info APN ERROR : { [Error: read ECONNRESET] code: 'ECONNRESET', errno: 'ECONNRESET', syscall: 'read' } s: null 
» 28 Nov 2015 11:28:12.682 2015-11-28T05:58:05.327Z info APN ERROR : { [Error: read ECONNRESET] code: 'ECONNRESET', errno: 'ECONNRESET', syscall: 'read' } s: null 
» 28 Nov 2015 11:30:21.370 2015-11-28T06:00:14.066Z info APN ERROR : { [Error: read ECONNRESET] code: 'ECONNRESET', errno: 'ECONNRESET', syscall: 'read' } s: null 
» 28 Nov 2015 11:30:21.462 2015-11-28T06:00:14.066Z info APN ERROR : { [Error: read ECONNRESET] code: 'ECONNRESET', errno: 'ECONNRESET', syscall: 'read' } s: null 
» 28 Nov 2015 12:42:42.363 2015-11-28T07:12:35.075Z info APN ERROR : { [Error: read ECONNRESET] code: 'ECONNRESET', errno: 'ECONNRESET', syscall: 'read' } s: null 
» 28 Nov 2015 12:42:42.556 2015-11-28T07:12:35.075Z info APN ERROR : { [Error: read ECONNRESET] code: 'ECONNRESET', errno: 'ECONNRESET', syscall: 'read' } s: null 
» 28 Nov 2015 12:53:26.997 2015-11-28T07:23:19.514Z info APN ERROR : { [Error: read ECONNRESET] code: 'ECONNRESET', errno: 'ECONNRESET', syscall: 'read' } s: null 
» 28 Nov 2015 12:53:27.024 2015-11-28T07:23:19.514Z info APN ERROR : { [Error: read ECONNRESET] code: 'ECONNRESET', errno: 'ECONNRESET', syscall: 'read' } s: null 
» 28 Nov 2015 14:07:08.656 2015-11-28T08:37:01.147Z info APN ERROR : { [Error: read ECONNRESET] code: 'ECONNRESET', errno: 'ECONNRESET', syscall: 'read' } s: null 
» 28 Nov 2015 14:07:08.681 2015-11-28T08:37:01.148Z info APN ERROR : { [Error: read ECONNRESET] code: 'ECONNRESET', errno: 'ECONNRESET', syscall: 'read' } s: null 
» 28 Nov 2015 14:07:09.117 2015-11-28T08:37:01.673Z info APN ERROR : { [Error: read ECONNRESET] code: 'ECONNRESET', errno: 'ECONNRESET', syscall: 'read' } s: null 
» 28 Nov 2015 14:07:09.119 2015-11-28T08:37:01.590Z info APN ERROR : { [Error: read ECONNRESET] code: 'ECONNRESET', errno: 'ECONNRESET', syscall: 'read' } s: null 
» 28 Nov 2015 14:07:10.028 2015-11-28T08:37:02.472Z info APN ERROR : { [Error: read ECONNRESET] code: 'ECONNRESET', errno: 'ECONNRESET', syscall: 'read' } s: null 
» 28 Nov 2015 14:07:10.291 2015-11-28T08:37:02.642Z info APN ERROR : { [Error: read ECONNRESET] code: 'ECONNRESET', errno: 'ECONNRESET', syscall: 'read' } s: null 
» 28 Nov 2015 14:07:11.121 2015-11-28T08:37:03.589Z info APN ERROR : { [Error: read ECONNRESET] code: 'ECONNRESET', errno: 'ECONNRESET', syscall: 'read' } s: null 
» 28 Nov 2015 14:07:11.179 2015-11-28T08:37:03.589Z info APN ERROR : { [Error: read ECONNRESET] code: 'ECONNRESET', errno: 'ECONNRESET', syscall: 'read' } s: null 
» 28 Nov 2015 15:16:42.980 2015-11-28T09:46:35.310Z info APN ERROR : { [Error: read ECONNRESET] code: 'ECONNRESET', errno: 'ECONNRESET', syscall: 'read' } s: null 
» 28 Nov 2015 15:16:42.984 2015-11-28T09:46:35.311Z info APN ERROR : { [Error: read ECONNRESET] code: 'ECONNRESET', errno: 'ECONNRESET', syscall: 'read' } s: null 
» 28 Nov 2015 15:36:23.702 2015-11-28T10:06:16.090Z info APN ERROR : { [Error: read ECONNRESET] code: 'ECONNRESET', errno: 'ECONNRESET', syscall: 'read' } s: null 
» 28 Nov 2015 15:36:23.704 2015-11-28T10:06:16.090Z info APN ERROR : { [Error: read ECONNRESET] code: 'ECONNRESET', errno: 'ECONNRESET', syscall: 'read' } s: null 
» 28 Nov 2015 17:52:12.335 2015-11-28T12:22:04.262Z info APN ERROR : { [Error: read ECONNRESET] code: 'ECONNRESET', errno: 'ECONNRESET', syscall: 'read' } s: null 
» 28 Nov 2015 17:52:12.371 2015-11-28T12:22:04.262Z info APN ERROR : { [Error: read ECONNRESET] code: 'ECONNRESET', errno: 'ECONNRESET', syscall: 'read' } s: null 
» 28 Nov 2015 17:52:46.767 2015-11-28T12:22:38.653Z info APN ERROR : { [Error: read ECONNRESET] code: 'ECONNRESET', errno: 'ECONNRESET', syscall: 'read' } s: null 
» 28 Nov 2015 17:52:46.791 2015-11-28T12:22:38.653Z info APN ERROR : { [Error: read ECONNRESET] code: 'ECONNRESET', errno: 'ECONNRESET', syscall: 'read' } s: null 
» 28 Nov 2015 17:52:50.638 2015-11-28T12:22:42.662Z info APN ERROR : { [Error: read ECONNRESET] code: 'ECONNRESET', errno: 'ECONNRESET', syscall: 'read' } s: null 
» 28 Nov 2015 17:52:50.817 2015-11-28T12:22:42.662Z info APN ERROR : { [Error: read ECONNRESET] code: 'ECONNRESET', errno: 'ECONNRESET', syscall: 'read' } s: null

**Comment by mohit3081989** [comment]
Just one question, is it possible that device which is inactive at APPLE server, and we try to send a notification to it, APPLE will send APN error 8 and after that breaks the connection ?

**Comment by haozxuan** [comment]
@mohit3081989 yes,  because APNS think this device is illegal, and APNS will break down this connect

**Comment by argon** [comment]
@mohit3081989 that is exactly what will happen. You need to ensure that you are using the data from the feedback service to prune old tokens from your database.

**Comment by mohit3081989** [comment]
@argon but it might happen that device for which notification failed is out of network, in that case I can't consider it for pruning out from database, don't you think so ?

**Comment by argon** [comment]
Please read this: https://developer.apple.com/library/ios/documentation/NetworkingInternet/Conceptual/RemoteNotificationsPG/Appendixes/BinaryProviderAPI.html#//apple_ref/doc/uid/TP40008194-CH106-SW4

**Comment by mohit3081989** [comment]
@argon I have already seen that, this document says that if the notification is not delivered it means that destination App doesn't exist or the token has expired. I have implemented this service and seen that notification for which it was failing has again been active after a day or 2. How would Apple eventually get to know that App doesn't exist, I understand it can confirm about expired token

**Comment by argon** [comment]
If you have ensured that the token is being refreshed in the app after every launch and your server is processing feedback correctly, then you are doing all you can. Apple will take care of the rest.

—A
