### ISSUE TITLE
Error code: 'ECONNRESET'

### ISSUE THREAD

**Issue by joshi3embed** [argon/node-apn#335]
```javascript
    var apn = require('apn');
	var tokens = ["dffa18014daa35f4ab0871a564b981e737a122bae6b56c8c0c8ec78070cfb846"];

	if(tokens[0] == "") {
		
	console.log("Please set token to a valid device token for the push notification serv");
	process.exit();
		
	}
	
	var options={	
		production:false
	}

	// Create a connection to the serv using mostly default parameters.
	var serv = new apn.connection(options);
	console.log(serv);
	serv.on('connected', function() {
	console.log("Connected");
	});
	
	serv.on('transmitted', function(notification, device) {
	console.log("Notification transmitted to:" + device.token.toString('hex'));
	});

	serv.on('transmissionError', function(errCode, notification, device) {
	console.error("Notification caused error: " + errCode + " for device ", device, notification);
	});

	serv.on('timeout', function () {
	console.log("Connection Timeout");
	});

	serv.on('disconnected', function() {
	console.log("Disconnected from APNS");
	});
	
	serv.on('socketError', console.error);
	// If you have a list of devices for which you want to send a customised notification you can create one and send it to and individual device.
	function pushSomeNotifications() {
	for (var i in tokens) {
	var note = new apn.notification();
	note.setAlertText("Hello, from node-apn! You are number: " + i);
	note.badge = 1;
		serv.pushNotification(note, tokens[i]);	
		}
	}
	
	pushSomeNotifications();
```
I am using above code to send push. but getting the following error frequently. I am using sendbox certificate for this and node js is running on the ubuntu.

this is the output with an error.
```
Disconnected from APNS
{ [Error: read ECONNRESET] code: 'ECONNRESET', errno: 'ECONNRESET', syscall: 'read' }
Disconnected from APNS
{ [Error: read ECONNRESET] code: 'ECONNRESET', errno: 'ECONNRESET', syscall: 'read' }
```
argon plz can you help me to solve above.

**Comment by argon** [comment]
Do any of the notifications arrive?

**Comment by mohamed-ahmed** [comment]
I'm having the same issue. @joshi3embed were you able to solve it?

**Comment by wallverb** [comment]
I was getting similar errors and it turned out that it was due to 'Error: certificate has expired: 2016-02-20', but I was using older version of apn and it was not showing this error until i updated to latest.

**Comment by arhi** [comment]
certs are active for another year .. this code was working yesterday ?!

test]# export DEBUG=apn
test]# node apntest.js
Sending the same notification each of the devices with one call to pushNotification.
Sending a tailored notification to 1 devices
  apn Initialising connection +0ms
  apn Loading Credentials +1ms
  apn 1 left to send +14ms
  apn Socket error occurred +526ms undefined { [Error: socket hang up] code: 'ECONNRESET' }
  apn Destroying connection +3ms undefined
  apn Removing socket from pool +0ms undefined
  apn Raising error: +2ms { [Error: socket hang up] code: 'ECONNRESET' } undefined undefined
  apn Error occurred with trace: +0ms Error: socket hang up
    at TLSSocket.onHangUp (_tls_wrap.js:968:21)
    at TLSSocket.g (events.js:199:16)
    at TLSSocket.emit (events.js:129:20)
    at _stream_readable.js:908:16
    at process._tickCallback (node.js:355:11)
{ [Error: socket hang up] code: 'ECONNRESET' }
  apn Socket error occurred +1ms undefined [Error: 140346698495808:error:14094416:SSL routines:SSL3_READ_BYTES:sslv3 alert certificate unknown:../deps/openssl/openssl/ssl/s3_pkt.c:1300:SSL alert number 46
]
[Error: 140346698495808:error:14094416:SSL routines:SSL3_READ_BYTES:sslv3 alert certificate unknown:../deps/openssl/openssl/ssl/s3_pkt.c:1300:SSL alert number 46
]
  apn Raising error: +1ms [Error: 140346698495808:error:14094416:SSL routines:SSL3_READ_BYTES:sslv3 alert certificate unknown:../deps/openssl/openssl/ssl/s3_pkt.c:1300:SSL alert number 46
] null undefined
  apn Error occurred with trace: +0ms Error: 140346698495808:error:14094416:SSL routines:SSL3_READ_BYTES:sslv3 alert certificate unknown:../deps/openssl/openssl/ssl/s3_pkt.c:1300:SSL alert number 46

    at Error (native)
  apn Destroying connection +0ms undefined
  apn Removing socket from pool +8ms undefined
  apn Socket closed +0ms undefined
  apn Removing socket from pool +1ms undefined
Disconnected from APNS
  apn 1 left to send +0ms
  apn Initialising connection +992ms
  apn 1 left to send +0ms
  apn Socket error occurred +455ms undefined { [Error: socket hang up] code: 'ECONNRESET' }
  apn Destroying connection +1ms undefined
  apn Removing socket from pool +0ms undefined
  apn Raising error: +0ms { [Error: socket hang up] code: 'ECONNRESET' } undefined undefined
  apn Error occurred with trace: +1ms Error: socket hang up
    at TLSSocket.onHangUp (_tls_wrap.js:968:21)
    at TLSSocket.g (events.js:199:16)
    at TLSSocket.emit (events.js:129:20)
    at _stream_readable.js:908:16
    at process._tickCallback (node.js:355:11)
{ [Error: socket hang up] code: 'ECONNRESET' }
  apn Socket error occurred +0ms undefined [Error: 140346698495808:error:14094416:SSL routines:SSL3_READ_BYTES:sslv3 alert certificate unknown:../deps/openssl/openssl/ssl/s3_pkt.c:1300:SSL alert number 46
]
[Error: 140346698495808:error:14094416:SSL routines:SSL3_READ_BYTES:sslv3 alert certificate unknown:../deps/openssl/openssl/ssl/s3_pkt.c:1300:SSL alert number 46
]
  apn Raising error: +1ms [Error: 140346698495808:error:14094416:SSL routines:SSL3_READ_BYTES:sslv3 alert certificate unknown:../deps/openssl/openssl/ssl/s3_pkt.c:1300:SSL alert number 46
] null undefined
  apn Error occurred with trace: +0ms Error: 140346698495808:error:14094416:SSL routines:SSL3_READ_BYTES:sslv3 alert certificate unknown:../deps/openssl/openssl/ssl/s3_pkt.c:1300:SSL alert number 46

    at Error (native)
  apn Destroying connection +0ms undefined
  apn Removing socket from pool +0ms undefined
  apn Socket closed +0ms undefined
  apn Removing socket from pool +0ms undefined
Disconnected from APNS
  apn 1 left to send +0ms
  apn Initialising connection +2s
  apn 1 left to send +1ms
  apn Socket error occurred +461ms undefined { [Error: socket hang up] code: 'ECONNRESET' }
  apn Destroying connection +1ms undefined
  apn Removing socket from pool +0ms undefined
  apn Raising error: +1ms { [Error: socket hang up] code: 'ECONNRESET' } undefined undefined
  apn Error occurred with trace: +0ms Error: socket hang up
    at TLSSocket.onHangUp (_tls_wrap.js:968:21)
    at TLSSocket.g (events.js:199:16)
    at TLSSocket.emit (events.js:129:20)
    at _stream_readable.js:908:16
    at process._tickCallback (node.js:355:11)
{ [Error: socket hang up] code: 'ECONNRESET' }
  apn Raising error: +0ms 514 { encoding: 'utf8',
  payload:
   { params: { data: [Object] },
     aps:
      { badge: 3,
        sound: 'ping.aiff',
        alert: '📧 ✉ trtmrt',
        'url-args': undefined,
        category: undefined } },
  expiry: 1468620470,
  priority: 10,
  retryLimit: -1,
  device: undefined,
  compiled: '{...}',
  truncateAtWordEnd: false,
  _badge: 3,
  _sound: 'ping.aiff',
  _alert: '📧 ✉ trtmrt' } { token: <Buffer 05 84 9d fd 33 52 cb 04 fe 5a 3b a8 1a 8b 43 00 cd 21 05 32 0b 6c 50 f0 7b b4 9c 8f 8b 00 63 89> }
Notification caused error: 514 for device  { token: <Buffer 05 84 9d fd 33 52 cb 04 fe 5a 3b a8 1a 8b 43 00 cd 21 05 32 0b 6c 50 f0 7b b4 9c 8f 8b 00 63 89> } { encoding: 'utf8',
  payload:
   { params: { data: [Object] },
     aps:
      { badge: 3,
        sound: 'ping.aiff',
        alert: '📧 ✉ trtmrt',
        'url-args': undefined,
        category: undefined } },
  expiry: 1468620470,
  priority: 10,
  retryLimit: -1,
  device: undefined,
  compiled: '{...}',
  truncateAtWordEnd: false,
  _badge: 3,
  _sound: 'ping.aiff',
  _alert: '📧 ✉ trtmrt' }
  apn Initialising connection +3ms
  apn 0 left to send +0ms
/root/node_modules/apn/node_modules/q/q.js:155
                throw e;
                      ^
Error: socket hang up
    at TLSSocket.onHangUp (_tls_wrap.js:968:21)
    at TLSSocket.g (events.js:199:16)
    at TLSSocket.emit (events.js:129:20)
    at _stream_readable.js:908:16
    at process._tickCallback (node.js:355:11)
test]#

**Comment by argon** [comment]
Verify with OpenSSL

openssl s_client -connect gateway.push.apple.com:2195 -key <path-to-key.pem> -cert <path-to-cert.pem>

—A

**Comment by arhi** [comment]
thanks for quick followup :D

```
prod]# openssl s_client -connect gateway.push.apple.com:2195 -key key.pem -cert cert.pem
CONNECTED(00000003)
depth=2 O = Entrust.net, OU = www.entrust.net/CPS_2048 incorp. by ref. (limits liab.), OU = (c) 1999 Entrust.net Limited, CN = Entrust.net Certification Authority (2048)
verify return:1
depth=1 C = US, O = "Entrust, Inc.", OU = See www.entrust.net/legal-terms, OU = "(c) 2012 Entrust, Inc. - for authorized use only", CN = Entrust Certification Authority - L1K
verify return:1
depth=0 C = US, ST = California, L = Cupertino, O = Apple Inc., CN = gateway.push.apple.com
verify return:1
140028541097824:error:14094416:SSL routines:SSL3_READ_BYTES:sslv3 alert certificate unknown:s3_pkt.c:1293:SSL alert number 46
140028541097824:error:140790E5:SSL routines:SSL23_WRITE:ssl handshake failure:s23_lib.c:184:
---
Certificate chain
 0 s:/C=US/ST=California/L=Cupertino/O=Apple Inc./CN=gateway.push.apple.com
   i:/C=US/O=Entrust, Inc./OU=See www.entrust.net/legal-terms/OU=(c) 2012 Entrust, Inc. - for authorized use only/CN=Entrust Certification Authority - L1K
 1 s:/C=US/O=Entrust, Inc./OU=See www.entrust.net/legal-terms/OU=(c) 2012 Entrust, Inc. - for authorized use only/CN=Entrust Certification Authority - L1K
   i:/O=Entrust.net/OU=www.entrust.net/CPS_2048 incorp. by ref. (limits liab.)/OU=(c) 1999 Entrust.net Limited/CN=Entrust.net Certification Authority (2048)
---
Server certificate
-----BEGIN CERTIFICATE-----
 . . . 
-----END CERTIFICATE-----
subject=/C=US/ST=California/L=Cupertino/O=Apple Inc./CN=gateway.push.apple.com
issuer=/C=US/O=Entrust, Inc./OU=See www.entrust.net/legal-terms/OU=(c) 2012 Entrust, Inc. - for authorized use only/CN=Entrust Certification Authority - L1K
---
Acceptable client certificate CA names
/C=US/O=Apple Inc./OU=Apple Certification Authority/CN=Apple Root CA
/C=US/O=Apple Inc./OU=Apple Worldwide Developer Relations/CN=Apple Worldwide Developer Relations Certification Authority
/C=US/O=Apple Inc./OU=Apple Certification Authority/CN=Apple Application Integration Certification Authority
---
SSL handshake has read 3138 bytes and written 2148 bytes
---
New, TLSv1/SSLv3, Cipher is AES256-SHA
Server public key is 2048 bit
Secure Renegotiation IS supported
Compression: NONE
Expansion: NONE
SSL-Session:
    Protocol  : TLSv1
    Cipher    : AES256-SHA
    Session-ID:
    Session-ID-ctx:
    Master-Key: 4CD...FD
    Key-Arg   : None
    Krb5 Principal: None
    PSK identity: None
    PSK identity hint: None
    Start Time: 1468621295
    Timeout   : 300 (sec)
    Verify return code: 0 (ok)
---
prod]#

```
not sure how to read this output .. it finishes with 
    Verify return code: 0 (ok)

but I do see before that
140028541097824:error:14094416:SSL routines:SSL3_READ_BYTES:sslv3 alert certificate unknown:s3_pkt.c:1293:SSL **alert number 46**
140028541097824:error:140790E5:SSL routines:SSL23_WRITE:**ssl handshake failure**:s23_lib.c:184:

alert number 46 and "unknown" .. how did it worked yesterday?! same certificate, how is it unknown all of a sudden .. not sure what I'm doing wrong :(

I created them from P12 with
```
openssl pkcs12 -in Sandbox.p12 -out dev/key.pem -nodes
openssl pkcs12 -in Production.p12 -out prod/key.pem -nodes
openssl x509 -in aps_development.cer -inform DER -outform PEM -out dev/cert.pem
openssl x509 -in aps.cer -inform DER -outform PEM -out prod/cert.pem
```

the dates are ok:
```
prod]# openssl x509 -enddate -noout -in cert.pem
notAfter=Jul 31 16:01:27 2017 GMT
prod]# openssl x509 -enddate -noout -in key.pem
notAfter=Jul 31 16:01:27 2017 GMT
```

**Comment by arhi** [comment]
thanks for helping debug, this 
openssl s_client -connect gateway.push.apple.com:2195
helps find issues ... the problem was the certificates on apple got "invalid", no clue how but .. 
thanks
