### ISSUE TITLE
pushing notification one by one

### ISSUE THREAD

**Issue by HKskn** [argon/node-apn#337]
Hi,

When i tried to push notification one by one, connection's pending queue going to be empty, when i got this result, i used shutdown function on apn connection, and when i tried to push new notification my event listeners were working twice, i want to terminate old listeners. How could it be? Thanks.
(i created connection once and pushed notification twice)

apnConnection.pushNotification(message, iosId);

function blabla () { 
apnConnection.on('completed', function () {
     console.log("pending queue is empty");
     apnConnection.shutdown();
});
}

**Comment by argon** [comment]
`connection.shutdown()` is intended to clean up the connection to be able to terminate application. If you are using the same connection over a long period of time you should not call shutdown and just continue to use the connection as normal.

**Comment by HKskn** [comment]
When i used " apnConnection.once('completed'...) " logs executed  once then i solved my problem with it. 
We are sending in batches of 1000 and sometimes it takes time finishing one batch job and following batch fails. My pending queue going to be empty in first batch and for the following batch the completed event is not triggered. So how can i use push notification twice or more with one connection?

**Comment by argon** [comment]
I'm sorry but I can't understand your comment. Could you please show me some code that you've tried and what you're expecting it to do.

**Comment by HKskn** [comment]
I have a recursive function that queries 1000 users by sql, and push notification them. We have for example 100.000 user so this code will be execute 10 times recursively, i didn't have any problem in first batch job, but my recursive function executed again process stopped and doesn't flow and doesn't throw any error. When i try this code my problem solved but you said "If you are using the same connection over a long period of time you should not call shutdown and just continue to use the connection as normal." so what is the true way about my operation ? if there are any solution what can i do about it or if there aren't , what is the bottleneck about shutdown connection? thank you.

      apnConnection.once('completed', function () {
        console.log("pending queue is empty");
        apnConnection.shutdown();
      });



-------------------------------------------------------------------------------------------
var apnConnection = new APN.Connection(createIOSNotificationOptions("gateway.push.apple.com", config.root + "/cert/" + config.IOS_CERT_FILENAME));

sendPushNotificationToUserWithIOSDevices: function  iosIds, message) {
    if (iosIds && iosIds.length > 0) {
      var deferred = Q.defer();
      apnConnection.pushNotification(message, iosIds);
      apnConnection.once("error", function error (err) {
        deferred.resolve({ isIOS: true});
        console.log(err);
      });
      apnConnection.once('transmitted', function transmitted (notification, device) {
        console.log("notification transmitted correctly",device);
        deferred.resolve({success: iosIds.length, failure: 0, isIOS: true});
      });
      apnConnection.once('transmissionError', function transmissionError (errCode, notification, device) {
        console.error("Notification caused error: " + errCode + " for device ", device, notification);
        if (errCode == 8) {
          console.log("A error code of 8 indicates that the device token is invalid. This could be for a number of reasons - are you using the correct environment? i.e. Production vs. Sandbox");
        }
        deferred.resolve({success: 0, failure: iosIds.length, isIOS: true});
      });
      apnConnection.once('timeout', function timeout () { 
        deferred.resolve({success: 0, failure: iosIds.length, isIOS: true});
        console.log("Connection Timeout");
      });
      apnConnection.once('disconnected', function openSockets (openSockets) {
        deferred.resolve({success: 0, failure: iosIds.length, isIOS: true});
        console.log("An error has occurred or the connection has timed out.", openSockets);
      });
      apnConnection.once('socketError', function socketError (result) {
        deferred.resolve({success: 0, failure: iosIds.length, isIOS: true});
        console.log("Socket error from APNS", result);
      });
      apnConnection.once('cacheTooSmall', function cacheTooSmall (sizeDifference) {
        console.log("The parameter is an estimate of how many notifications have been lost.", sizeDifference);
      });
      apnConnection.once('connected', function connected (openSockets) {
        console.log("number of open connections: ", openSockets);
      });
      apnConnection.once('completed', function () {
        console.log("pending queue is empty");
        apnConnection.shutdown();
      });
      return deferred.promise;
    } else {
      return Q.fcall(function () {
        return {success: 0, failure: 0};
      });
    }
  }

**Comment by argon** [comment]
What you attempting to do with promises here is unfortunately not possible with the current version of node-apn. In fact, none of the metrics you're trying to gather here are actually meaningful as you are going to receive lots of duplicates. For starters, `transmitted` is emitted for *every* notification sent to Apple, before it is known whether an error has occurred. Therefore the promise will be resolved for each notification `transmitted` then potentially *again* for each error which occurs, however a promise will only resolve once so you never get any of the info you're trying to gather.

It is *not possible* to implement a promises based interface on top of the current apn protocol.

You're definitely trying to complicate things and it should be kept simple. More will be possible with the next version but I don't have it working yet.

For now, each event handler you have attached should be handled globally. You'll need to rethink this I'm afraid.

```js
var apnConnection = new APN.Connection(createIOSNotificationOptions("gateway.push.apple.com", config.root + "/cert/" + config.IOS_CERT_FILENAME));

apnConnection.on("error", function error (err) {
  console.log(err);
});

apnConnection.on('transmitted', function transmitted (notification, device) {
  console.log("notification transmitted correctly",device);
});

apnConnection.on('transmissionError', function transmissionError (errCode, notification, device) {
  console.error("Notification caused error: " + errCode + " for device ", device, notification);
  if (errCode == 8) {
    console.log("A error code of 8 indicates that the device token is invalid. This could be for a number of reasons - are you using the correct environment? i.e. Production vs. Sandbox");
  }
});

apnConnection.on('timeout', function timeout () { 
  console.log("Connection Timeout");
});

apnConnection.on('disconnected', function openSockets (openSockets) {
  console.log("An error has occurred or the connection has timed out.", openSockets);
});

apnConnection.on('socketError', function socketError (result) {
  console.log("Socket error from APNS", result);
});

apnConnection.on('cacheTooSmall', function cacheTooSmall (sizeDifference) {
  console.log("The parameter is an estimate of how many notifications have been lost.", sizeDifference);
});

apnConnection.on('connected', function connected (openSockets) {
  console.log("number of open connections: ", openSockets);
});

apnConnection.on('completed', function () {
  console.log("pending queue is empty");
});

sendPushNotificationToUserWithIOSDevices: function  iosIds, message) {
  if (iosIds && iosIds.length > 0) {
    apnConnection.pushNotification(message, iosIds);
  }
}
```

**Comment by mauron85** [comment]
@argon +1 to promises
