### ISSUE TITLE
Potential Memory Leak?

### ISSUE THREAD

**Issue by wcchoi** [argon/node-apn#339]
Hi, I am trying to figure out some memory leak problems in my server application, and I notice (from heapdump) that `deferredConnection` in `lib/feedback.js` is retaining quite some memory by holding references to lots of closure object. I go and read the source code and find the following snippet that may be causing the problem, I wonder if it is really the cause or is it just me using the library wrongly.

In `lib/feedback.js`

```javascript
/**
 * Connect to the feedback service, also initialise the timer if an interval is specified.
 */
Feedback.prototype.start = function () {
	debug("Starting feedback service");
	this.cancel();
	if (this.options.interval > 0) {
		debug("Feedback service interval set at: %d", this.options.interval);
		this.interval = setInterval(this.request.bind(this), this.options.interval * 1000);
	}
	this.request();
};

/**
 * @private
 */
Feedback.prototype.request = function () {
	debug("Performing feedback request");
	this.createSocket().fail(function (error) {
		this.emit("feedbackError", error);
	}.bind(this));
};
```

It seems that each time `request` is called (in interval), a new fail handler is attached to the promise returned by `this.createSocket()` (if it is still the same promise) and it is not freed.

I am still using an older version(1.5.2) of node-apn, but that part of code is about the same. Not sure if that matters.

**Comment by argon** [comment]
This is a fair observation, however it is incorrect for `request` to be called more than once on a single connection. When a request is performed it will connect to APNS and close the connection when all data is received. The close event handler disposes of the `createSocket` promise ensuring there is no memory leak. There should be little need to set the interval to less than 1 hour and for most applications once per day would probably suffice, thereby avoiding any memory leaks in this case.

Thanks for getting in touch though!
