### ISSUE TITLE
apn connection seems to be ignoring the options dict

### ISSUE THREAD

**Issue by thehessian** [argon/node-apn#340]
* I'm using some simple code to set up an apn connection:
        var options = {};
        options["production"] = true;
        options["cert"] = "/FULL/PATH/TO/cert.pem";
        options["key"] = "/FULL/PATH/TO/key.pem";
        apnConnection = new apn.Connection(options);

* However, when I pass these options to the apn Connection, the options seem to be ignored 
/PATH/nodejs/node_modules/q/q.js:155
                throw e;
                ^

Error: ENOENT: no such file or directory, open 'cert.pem'
    at Error (native)

* Am I missing something obvious?

**Comment by thehessian** [comment]
FWIW if i copy the cert and key to the same directory as the node file, everything seems to work, but I'd really like to store them elsewhere.

**Comment by minkesh** [comment]
any updates on this issue, facing the same problem !

**Comment by argon** [comment]
You're probably not configuring the feedback service correctly.

**Comment by minkesh** [comment]
How is the feedback service related to this, As per my understanding this should work even if I don't use feedback service at all.

**Comment by argon** [comment]
Every time I have seen people with this problem it has been due to the feedback service being instantiated without options leading to that error.

If you continue to see a problem then open an issue with an example of the code you're using an full details.

**Comment by minkesh** [comment]
Sure! Thanks man.
