### ISSUE TITLE
apn connection seems to be ignoring the options dict

### ISSUE THREAD

**Issue by thehessian** [argon/node-apn#341]
* I'm using some simple code to set up an apn connection:
```
var options = {};
options["production"] = true;
options["cert"] = "/FULL/PATH/TO/cert.pem";
options["key"] = "/FULL/PATH/TO/key.pem";
apnConnection = new apn.Connection(options);
```
* However, when I pass these options to the apn Connection, the options seem to be ignored 
```
    /PATH/nodejs/node_modules/q/q.js:155
    throw e;
    ^
    
    Error: ENOENT: no such file or directory, open 'cert.pem'
    at Error (native)
```
* Am I missing something obvious?  FWIW if i copy the cert and key to the same directory as the node file, everything seems to work, but I'd really like to store them elsewhere.

**Comment by ryanbennettvoid** [comment]
try `fs.readFileSync("FULL/PATH/TO/xxx")` instead

**Comment by argon** [comment]
Please run your application with `DEBUG=apn*` environment variable to see more logging. This should show you the problem.

**Comment by gokul-toobler** [comment]
have same issue.. any help.

**Comment by gokul-toobler** [comment]
ok . i  figure it out.. in feedback options for feedback hendler also specify the cert and key.
the error is raised from there..

**Comment by milosjovac** [comment]
Hi, I have the same problem.

No matter where I put .pem files (same entry point as main.js, or elsewhere), I get: Error: ENOENT: no such file or directory, open 'cert.pem'

console.log(__dirname + '/conf/dev_key.pem') logs a good path.
console.log(fs.readFileSync(__dirname + '/conf/dev_key.pem')); logs:  Buffer 42 61 67 20 41 74 74 72 69 62 75 74 65 73 0a 20 20 20 20 66 72 69 65 6e 64 6c 79 4e 61 6d 65 3a 20 69 50 68 6f 6e 65 20 44 65 76 65 6c 6f 70 65 72 3a ...  so it is definitely valid

My options var:

       options = {
	    "key"  : fs.readFileSync(__dirname + '/conf/dev_key.pem'),
	    "cert"  : fs.readFileSync(__dirname + '/conf/dev_cert.pem'),
	    "passphrase" : "Sifter2015",
	    "production" : false
      };

Error happens for path and Buffer as well.
Is everything OK with the latest version of the lib?

**Comment by argon** [comment]
Can you confirm you are using the correct options with `new Feedback()`. That is usually where this error comes from

**Comment by milosjovac** [comment]
options = {
			 "batchFeedback": true,
		 	"interval": 300
		 };

     var feedback = new apn.Feedback(options);
		     feedback.on("feedback", function(devices) {
			    devices.forEach(function(item) {
				  console.log(item);
			  });
		  });

**Comment by milosjovac** [comment]
Yeah, it was the Feeback options. The one that works now looks like this:

      var options = {
		     "key"  : me.production ? prodKey : devKey,
		     "cert"  : me.production ? prodCert : devCert,
		     "passphrase" : "Sifter2015",
		     "production" : me.production ? true : false,
		     "batchFeedback": true,
		     "interval": 300
		  };
