### ISSUE TITLE
Issue installing apn on CentOS

### ISSUE THREAD

**Issue by jakorten** [argon/node-apn#342]
I get this error (node-forge@0.6.38 is installed in fact): 

npm ERR! Error: No compatible version found: node-forge@'^0.6.20'
npm ERR! Valid install targets:
npm ERR! ["0.1.2","0.1.3","0.1.4","0.1.5","0.1.6","0.1.7","0.1.8","0.1.9","0.1.10","0.1.11","0.1.12","0.1.13","0.1.14","0.1.15","0.2.0","0.2.1","0.2.2","0.2.3","0.2.4","0.2.5","0.2.6","0.2.7","0.2.8","0.2.9","0.2.10","0.2.11","0.2.12","0.2.13","0.2.14","0.2.15","0.2.17","0.2.18","0.2.19","0.2.20","0.2.21","0.2.22","0.2.23","0.2.24","0.2.25","0.2.26","0.2.27","0.2.28","0.2.29","0.2.30","0.2.31","0.2.32","0.2.33","0.2.34","0.2.35","0.2.36","0.2.37","0.3.0","0.4.1-dev","0.4.1","0.4.2","0.4.3","0.5.1","0.5.2","0.5.3","0.5.4","0.5.5","0.6.0","0.6.1","0.6.2","0.6.3","0.6.4","0.6.5","0.6.6","0.6.7","0.6.8","0.6.9","0.6.10","0.6.11","0.6.12","0.6.13","0.6.14","0.6.16","0.6.18","0.6.19","0.6.20","0.6.21","0.6.22","0.6.23","0.6.24","0.6.25","0.6.26","0.6.27","0.6.28","0.6.29","0.6.30","0.6.31","0.6.32","0.6.33","0.6.34","0.6.35","0.6.37","0.6.38"]
npm ERR!     at installTargetsError (/opt/node/lib/node_modules/npm/lib/cache.js:719:10)
npm ERR!     at /opt/node/lib/node_modules/npm/lib/cache.js:638:10
npm ERR!     at RegClient.get_ (/opt/node/lib/node_modules/npm/node_modules/npm-registry-client/lib/get.js:105:14)
npm ERR!     at RegClient.<anonymous> (/opt/node/lib/node_modules/npm/node_modules/npm-registry-client/lib/get.js:41:12)
npm ERR!     at fs.js:266:14
npm ERR!     at /opt/node/lib/node_modules/npm/node_modules/graceful-fs/graceful-fs.js:103:5
npm ERR!     at Object.oncomplete (fs.js:107:15)
npm ERR! If you need help, you may report this log at:
npm ERR!     <http://github.com/isaacs/npm/issues>
npm ERR! or email it to:
npm ERR!     <npm-@googlegroups.com>

**Comment by argon** [comment]
Which version of node / npm are you using? Older versions don't support '^' versioning syntax. You probably need to upgrade

—A

**Comment by jakorten** [comment]
I was using an older version indeed, while it was quite a hassle to update it is resolved now (first I needed to upgrade python, then NPM and finally I could upgrade Node).
