### ISSUE TITLE
Notification not sending when only a payload is specified

### ISSUE THREAD

**Issue by mnort9** [argon/node-apn#344]
When I create a notification with only a payload object, I receive no error through node-apn, but the notification is not received. When I add an "alert" or "badge", it does work. 

Should this maybe error out if the notification object is not complete? 

```
var apnNotification = new apn.Notification();
apnNotification.payload = {"foo": "bar"};

var device = new apn.Device('token');
apnConnection.pushNotification(apnNotification, device);
```

**Comment by argon** [comment]
Perhaps. In certain cases aps isn't needed (when mdm is used for instance). In principle I don't think node-apn should necessarily guard against this.

—A

**Comment by mnort9** [comment]
Should it maybe show a warning in debug mode? 

You're probably right that it's not a node-apn responsibility, it just tripped me up for a few hours and I can see it happening to others. Apple does a poor job of providing any type of status for the notification after it has been submitted to apns.

**Comment by argon** [comment]
In this case I think you will find that the notification is "valid" so Apple will deliver it to the device. However, when it arrives at the device there is nothing for the OS to do unless the app is currently running, in which case it probably would be delivered. I don't think this is a defect of the library so I'm going to close this.

**Comment by fbartolom** [comment]
I have exactly the same problem. The notification seems to be sent with no error from the Apple APN but no notification is received when I submit the data in the payload. If conversely I add them to the notification as properties it works fine by I have no cue about how to send random properties in that way.

**Comment by jeacott1** [comment]
yep - seeing this too with 2.1.4, payload only specified, no errors, accepted by apple, but notification never arrives. same push works fine with 1.7.x.
