### ISSUE TITLE
Error with sandbox cert, key and production: false

### ISSUE THREAD

**Issue by harunurhan** [argon/node-apn#346]
~~~
			var options = {
				cert: './dcert.pem',
				key: './dkey.pem',
				passphrase: 'xxxxx',
				production: false,
			};
~~~

Pem files are for development and production is set to false as you can see but I am seeing below error
`Error: certificate does not support configured environment, production: false`

**Comment by argon** [comment]
Do you also have cert.pem and key.pem in that directory?

—A

**Comment by harunurhan** [comment]
@argon No I didn't have but with new certificates it works right now. So I am closing this issue.
Thanks for your response!
