### ISSUE TITLE
Unable to send MDM command to device

### ISSUE THREAD

**Issue by VenkateshSrini** [argon/node-apn#348]
Hi,
The pay load that we are giving is as below
```json
{
    "aps": {
        "sound": "notification-beep.wav",
        "alert": {
            "body": "<?xml version=\"1.0\" encoding=\"UTF-8\"?>\n<!DOCTYPE plist PUBLIC \"-//Apple//DTD PLIST 1.0//EN\" \"http://www.apple.com/DTDs/PropertyList-1.0.dtd\">\n<plist version=\"1.0\">\n  <dict>\n    <key>CommandUUID</key>\n    <string>9d25178d-e26c-4085-a20a-df39f56a0c16</string>\n    <key>Command</key>\n    <dict>\n      <key>RequestType</key>\n      <string>InstallApplication</string>\n      <key>ManifestURL</key>\n      <string>https://xxx.com/app_manifest/app_manifest_9.plist</string>\n      <key>ManagementFlags</key>\n      <integer>1</integer>\n    </dict>\n  </dict>\n</plist>"
        }
    },
    "mdm": "PUSH magic token given during enrollment"
}
```
But the notification is not sent to device at all. The feedback server keeps reporting failure. Can some  insights be given on how to achieve it

**Comment by argon** [comment]
Which error are you receiving? That will give you insight into the problem

**Comment by VenkateshSrini** [comment]
Hi argon,

Sorry earlier payload was wrongly pasted. Can you please see the new one.

**Comment by argon** [comment]
See my earlier message

**Comment by VenkateshSrini** [comment]
Also the error is reported by feedback service. The code I have written in feedback service is 
var feedback = new apn.Feedback(options1);
feedback.on("feedback", function (devices) {
    //console.log('devices>>>>> ' + devices);
    devices.forEach(function (item) {
        console.log('item>>>>>>> ' + item.device);
	
        // Do something with item.device and item.time;
    });
}); 
As you can see I'm able to just get the device token in hex format of failed message, Is there some property that will tell me what the error is

**Comment by argon** [comment]
When the feedback service sends a device token it indicates that the device is no longer registered with APN so it will not be receiving notifications.

You need to re-register the device.

**Comment by VenkateshSrini** [comment]
Hi Andrew,
As stated earlier what I'm doing is an iOS MDM. In that process I have completed the device enrollment process and as a result of the tokenUpdate (device check in process) I got the Token (device token) and push magic token. Now these are token returned by device to my MDM server. I'm using the device token to create apn.Device object and the Push magic token is used for sending the MDM pay load. so I'm not sure how we  need to re- register this device. I have tried reinstalling the enrollment profile and it worked successfully.

**Comment by argon** [comment]
So it's working now? Do you receive any errors while sending the notification?

**Comment by VenkateshSrini** [comment]
Hi Andrew,
No it is still not working. I removed the profile and re-installed as a result of that I got a  new push magic token. But the device token was the same. I tried sending the message with new push magic but that also did not succeed. Instead of APP install I gave a device lock notification. The command was something as below
{"aps":{"alert":{"body":"<?xml version=\"1.0\" encoding=\"UTF-8\"?><!DOCTYPE plist PUBLIC \"-//Apple//DTD PLIST 1.0//EN\" \"http://www.apple.com/DTDs/PropertyList-1.0.dtd\">\n<plist version=\"1.0\">\n  <dict>\n    <key>CommandUUID</key>\n    <string>af4d37ad-0464-420c-ab68-d9a5dac9d324</string>\n    <key>Command</key>\n    <dict>\n      <key>RequestType</key>\n      <string>DeviceLock</string>\n    </dict>\n  </dict>\n</plist>"}},"mdm":"PUSH magic token given during enrollment"}

But still not working. I'm struggling with this

**Comment by argon** [comment]
I don't know anything about MDM as Apple keep all documentation secret. Check that you are using the correct environment (production vs sandbox).

The problem you are describing is unrelated from node-apn and sounds like it would happen regardless of APN library so I would recommend asking in the Apple Developer Forums

**Comment by VenkateshSrini** [comment]
Hi Andrew,
I beg to differ. The issue is like this.
1) I need to know how to construct the notification for an MDM command. In case of normal command I just create a instance of pay load and keep assigning the various properties and it works great. Where as when it comes to MDM, Do we need to construct XML payload with "aps" object or can we just assign a few JSON property and get it working. I guess from my research we need to send the xml payload but not sure of the same
2) The library has support for setMDM function which accepts the push magic token. But not that much support for pay load construction.
3) The same logic works from other platform like .NET. We are using a JDSOFT library to do the MDM push notification and it works like a charm. There we pass an object plus a custom notification header called MDM with push magic token. It works seamlessly. Unfortunately we are not able to do a serialization of the output from JD soft to see what pay load goes.

So it all boils down as to how pay load construction needs to happen. If I crack this then I will be more than happy to add these features in node- apn

**Comment by argon** [comment]
As I said above. Apple keep all MDM documentation secret so I have no information about how to create those payloads. All notification objects must be in JSON form but I suspect you may need to send XML as part of one of the properties as a string.

I would strongly urge you to consult the documentation as you are pressing me for information I do not have access to:

**Apple do not publish MDM documentation publicly.**

**Comment by argon** [comment]
@VenkateshSrini I have received some further information about the MDM command. According to my source the push payload should _only_ contain the MDM push secret. It is an error for it to contain any other properties. 

The notification is very simple and only includes the identifier. When the iOS device receives the notification with the `mdm` property it will connect directly to the MDM server to receive the commands. The Push notification payload should be in the format:

```json
{"mdm":"aaaaaaaa-bbbb-cccc-dddd-eeeeeeeeeeee"}
```

I have verified this behaviour and node-apn behaves exactly as it should:
```
> let apn = require("apn");
undefined
> let note = new apn.notification();
undefined
> note.mdm = "aaaaaaaa-bbbb-cccc-dddd-eeeeeeeeeeee";
'aaaaaaaa-bbbb-cccc-dddd-eeeeeeeeeeee'
> note.compile()
'{"mdm":"aaaaaaaa-bbbb-cccc-dddd-eeeeeeeeeeee"}'
>
```

mdm support has been functional in this module since Feb 24 2013, in commit a1a5a656f1c89a34f8912e6cde3541a092f1d953

**Comment by VenkateshSrini** [comment]
Thanks Andrew will try this and let you know

-----Original Message-----

**Comment by VenkateshSrini** [comment]
Hi Andrew,
Even after implementation this suggestion the feed back service us still reporting my device I'd which implies delivery failure. Please share any other thought that you have 

-----Original Message-----
From: "Venkatesh Srinivasan" <venkateshsrini3@gmail.com>
Sent: ‎29-‎01-‎2016 07:22 AM
To: "argon/node-apn" <reply@reply.github.com>; "argon/node-apn" <node-apn@noreply.github.com>
Subject: RE: [node-apn] Unable to send MDM command to device (#348)

Thanks Andrew will try this and let you know

**Comment by argon** [comment]
If the feedback service is reporting the device token you should stop sending notifications to that token and re-register. As this is not an issue with the node-apn module please ask your question on the Apple Developer Forums

**Comment by VenkateshSrini** [comment]
Sure Thanks

-----Original Message-----
