### ISSUE TITLE
unsure about feedback service semantics

### ISSUE THREAD

**Issue by molecular** [argon/node-apn#349]
Hello,

I'm unsure about feedback service semantics. When receiving device info in feedback service, does it mean the device has uninstalled the app or can there be other reasons (like device switched off) to trigger feedback?

This text from the readme got me thinking:

```
Apple recommends checking the feedback service periodically for a list of devices for which there were failed delivery attempts.
```

what exactly constitutes a 'failed delivery attempt'?

I don't want to accidentally remove tokens from my db that still have my app installed.

What also makes me feel uneasy: the official (?) apple documentation at https://developer.apple.com/library/ios/documentation/NetworkingInternet/Conceptual/RemoteNotificationsPG/Chapters/Introduction.html#//apple_ref/doc/uid/TP40008194-CH1-SW1 doesn't seem to mention the feedback service at all (any more?). Is it obsolete? I'm using quite an old version of node-apn (1.6.0).

**Comment by argon** [comment]
https://developer.apple.com/library/ios/documentation/NetworkingInternet/Conceptual/RemoteNotificationsPG/Appendixes/BinaryProviderAPI.html#//apple_ref/doc/uid/TP40008194-CH106-SW4

**Comment by molecular** [comment]
jesus, you're fast! thanks, will check it out

**Comment by molecular** [comment]
maybe so other can read, here's the relevant part from the apple documentation argon linked:

```
The Apple Push Notification service includes a feedback service to give you information about failed remote notifications. When a remote notification cannot be delivered because the intended app does not exist on the device, the feedback service adds that device’s token to its list. Remote notifications that expire before being delivered are not considered a failed delivery and don’t impact the feedback service.
```

maybe the readme could be worded differently to clarify that "failed delivery" in this context really means "failed delivery because app is not installed".

**Comment by argon** [comment]
I will plan to add some information to the docs.

As a side note: the semantics are a little more subtle than that. If the app is uninstalled, then reinstalled it may receive a new device token after reinstalling (which sometimes leads to duplicate notifications if feedback is not obeyed). It's possible that a device token can appear in the feedback service even if the app is reinstalled because the token is for the previous installation.

**Comment by molecular** [comment]
Ok. So I take the 'correct' way to implement feedback service is to remove the token as soon as it's seen on feedback service?

**Comment by argon** [comment]
You must take into account the time property also sent back to you in case the token has been updated on your side more recently as reinstalls can sometimes yield the same token.

—A

**Comment by molecular** [comment]
> You must take into account the time property also sent back to you in case the token has been updated on your side more recently as reinstalls can sometimes yield the same token.

I understand.

Oh my... I'm already expecting to fight some timezone or similar problems. ;|

**Comment by argon** [comment]
Keep everything in UTC on your server and all will be ok
