### ISSUE TITLE
voip push setting

### ISSUE THREAD

**Issue by breaklee** [argon/node-apn#352]
i'm using below settings for production , sandbox.
with same certification files.

```json
var production = {
	            maxConnections : 2,
	            fastMode       : true,
	            voip 		   : true,
	            connectTimeout : 10000,
	            production     : true,
};

var sandbox = {
	            maxConnections : 2,
	            fastMode       : true,
	            voip 		   : true,
	            connectTimeout : 10000,
	            production     : false,
};
```
'production' property is worth to setting?
there are only one certificate file pair for voip push.

but 

some device token raise errors on production push.
and some token raise errors on sandbox push.

**Comment by argon** [comment]
Even though the certificates are the same you still need to ensure that tokens from Development apps use sandbox and tokens from Distribution apps use production.
