### ISSUE TITLE
Not sure where the error is.

### ISSUE THREAD

**Issue by mohamed-ahmed** [argon/node-apn#353]
I'm trying to get push notifications working and I'm not sure where its failing. I can't tell if the cert and key are invalid, other options, not set correctly or the id. The code I'm using is

> process.env.DEBUG="apn";
> var apn = require('apn');
> 
>  var options = {
>  	key : "key.pem",
>  	passphrase : '123',
>  	production : false,
>  };
> 
> var apnConnection = new apn.Connection(options);
> 
> apnConnection.on("completed", function(){console.log("completed");});
> apnConnection.on("error", function(error){console.log("completed", error);});
> apnConnection.on("timeout", function(error){console.log("timeout", error);});
> apnConnection.on("connected", function(error){console.log("connected", error);});
> apnConnection.on("disconnected", function(error){console.log("disconnected", error);});
> apnConnection.on("transmitted", function(error){console.log("transmitted", error);});
> apnConnection.on("socketError", function(error){console.log("socketError", error);});
> 
> 
> var myDevice = new apn.Device('d7b28....9493');
//actual token is 64 characters in length
> console.log(myDevice);
> 
> var note = new apn.Notification();
> 
> note.expiry = Math.floor(Date.now() / 1000) + 3600; // Expires 1 hour from now.
> note.badge = 3;
> note.alert = "\uD83D\uDCE7 \u2709 You have a new message";
> note.payload = {'messageFrom': 'Test'};
> 
> var options = {
>     "batchFeedback": true,
>     "interval": 300
> };
> 
> var feedback = new apn.Feedback(options);
> feedback.on("feedback", function(devices) {
> 	console.log("devices: ");
> 	console.log(devices);
>     devices.forEach(function(item) {
>         // Do something with item.device and item.time;
>     });
> });
> 
> apnConnection.pushNotification(note, myDevice);

and the output is

> { token: <Buffer d7 b2 8d ..... 97 26 72 2b ba 94 93> }
>   apn Initialising connection +0ms
>   apn Loading Credentials +2ms
>   apn 1 left to send +2ms
>   apn Socket error occurred +343ms undefined { [Error: socket hang up] code: 'ECONNRESET' }
>   apn Destroying connection +2ms undefined
>   apn Removing socket from pool +0ms undefined
>   apn Raising error: +2ms { [Error: socket hang up] code: 'ECONNRESET' } undefined undefined
>   apn Error occurred with trace: +0ms Error: socket hang up
>     at TLSSocket.onHangUp (_tls_wrap.js:961:21)
>     at TLSSocket.g (events.js:199:16)
>     at TLSSocket.emit (events.js:129:20)
>     at _stream_readable.js:908:16
>     at process._tickCallback (node.js:355:11)
> socketError { [Error: socket hang up] code: 'ECONNRESET' }
>   apn Socket closed +0ms undefined
>   apn Removing socket from pool +1ms undefined
> disconnected 0
>   apn 1 left to send +0ms
> devices: 
> []
>   apn Initialising connection +1s
>   apn 1 left to send +0ms
>   apn Socket error occurred +318ms undefined { [Error: socket hang up] code: 'ECONNRESET' }
>   apn Destroying connection +1ms undefined
>   apn Removing socket from pool +0ms undefined
>   apn Raising error: +1ms { [Error: socket hang up] code: 'ECONNRESET' } undefined undefined
>   apn Error occurred with trace: +0ms Error: socket hang up
>     at TLSSocket.onHangUp (_tls_wrap.js:961:21)
>     at TLSSocket.g (events.js:199:16)
>     at TLSSocket.emit (events.js:129:20)
>     at _stream_readable.js:908:16
>     at process._tickCallback (node.js:355:11)
> socketError { [Error: socket hang up] code: 'ECONNRESET' }
>   apn Socket closed +1ms undefined
>   apn Removing socket from pool +0ms undefined
> disconnected 0
>   apn 1 left to send +0ms

**Comment by mohamed-ahmed** [comment]
The issue is that the certificates were created using different command line options.

**Comment by mohamed-ahmed** [comment]
The notification works fine now but I'm wondering why the script doesn't close after sending the notification. 
Tha is, running node apn_test.js hangs and doesn't return to the command line.

**Comment by argon** [comment]
node-apn is designed for long running applications. Apple's own documentation states that sockets should not be created and torn down frequently as it will be treated as a Denial of Service attack and your credentials may be revoked. As such the system is designed to keep sockets open as long as possible.

If you require `node-apn` to clean up after sending a batch of notifications you can call `connection.shutdown()`. I would consider your use case very carefully before you go down this route.

**Comment by paweldziura** [comment]
@mohamed-ahmed Could you describe the problem that you faced more precisely? I am facing similar issue now. What do you mean by "different command line options"?
Thanks!
