### ISSUE TITLE
how we can set sandbox or live environment in push notify?

### ISSUE THREAD

**Issue by manprajapat** [argon/node-apn#354]
I am not able to receive notification when application is downloaded from app store. but from my development side is working well. may be by defining environment can be solved. how we can set environment?

**Comment by argon** [comment]
You should use the `production` option:

> production {Boolean} Specifies which environment to connect to: Production (if true) or Sandbox - The hostname will be set automatically. (Defaults to the value of `NODE_ENV == "production"`, i.e. false unless the NODE_ENV environment variable is set accordingly)

https://github.com/argon/node-apn/blob/master/doc/connection.markdown

**Comment by manprajapat** [comment]
So for production level is this perfect?

 var options = {
                cert: 'cert.pem',
                key: 'key.pem',
                passphrase: 'xxxxx',
                production: true,
            };

and what is the different between  **cert.pem** and **key.pem**

**Comment by argon** [comment]
One is the certificate file for connection to Apple and the other is the private key. If you only have one file with extension `pfx` or `p12` then you should use the `pfx` option instead. If you have one file with `pem` extension then use that filename for both parameters.
