### ISSUE TITLE
device is not receiving notification under production

### ISSUE THREAD

**Issue by zzeng4** [argon/node-apn#357]
It works well under development env, but when I switch it to production environment with production certificate and key, it doesn't work at all.

I tested the certificates with APNS tool, which can be downloaded from App store; it works there, but not in here.

there is no error occurs when I send notification with node, and I run it under debug mode, the feedback is the same as under the development mode.

`var options = {
        cert: config.apsCert,
        key: config.apsKey,
        passphrase: config.apsPass,
    };

    var apnConnection = new apn.Connection(options);

    //var myDevice = new apn.Device(receiverDeviceToken);

    var note = new apn.Notification();
        note.expiry = Math.floor(Date.now() / 1000) + 3600;
        note.sound = "default";
        note.badge = 1;
        note.alert = "haha";
        note.payload = {"messageFrom": "tester"};
    apnConnection.pushNotification(note, receiverDeviceToken);

apn Initialising connection +0ms
  apn Loading Credentials +1ms
  apn 1 left to send +2ms
  apn Connection established +454ms
  apn Socket drained +103ms 0
  apn 0 left to send +0ms
  apn 0 left to send +1ms
  apn Notification 0 caused an error: 8 +89ms
  apn Raising error: +0ms 8 { encoding: 'utf8',
  payload: 
   { messageFrom: 'tester',
     aps: 
      { badge: 1,
        sound: 'default',
        alert: 'haha',
        'url-args': undefined,
        category: undefined } },
  expiry: 1455097030,
  priority: 10,
  retryLimit: -1,
  device: undefined,
  compiled: '{"messageFrom":"tester","aps":{"badge":1,"sound":"default","alert":"haha"}}',
  truncateAtWordEnd: false,
  _sound: 'default',
  _badge: 1,
  _alert: 'haha' } { token: <Buffer af 83 9d 07 12 45 7e d9 60 76 95 d8 7a a0 4c 20 ee 86 b8 b7 0f b4 65 e3 4f c4 ea 22 f4 4c 51 d2> }
  apn Buffering 0 notifications for resending +2ms
  apn Socket closed +1ms 0
  apn Removing socket from pool +0ms 0
  apn Initialising connection +0ms
  apn 0 left to send +1ms
  apn Connection established +288ms
  apn 0 left to send +101ms
`

**Comment by ronyrun** [comment]
add 

gateway: 'gateway.push.apple.com',

in your options.

**Comment by argon** [comment]
You shouldn't use gateway option, it has been deprecated. Set `production: true`

—A

**Comment by haozxuan** [comment]
or  set your environment NODE_ENV === "production"
