### ISSUE TITLE
The device cannot receive notification in production environment

### ISSUE THREAD

**Issue by YuanBoot** [argon/node-apn#360]
That is the code, very easy.

`var apn = require('apn');`
`var options = {production:true};`

`var apnConnection = new apn.Connection(options);`
`var myDevice = new apn.Device('****************');`

`var note = new apn.Notification();`

`note.expiry = Math.floor(Date.now() / 1000) + 3600; // Expires 1 hour from now.`
`note.badge = 3;`
`note.sound = "ping.iff";`
`note.alert = "\uD83D\uDCE7 \u2709 You have a new message";`
`note.payload = {'messageFrom': 'Caroline'};`

`apnConnection.pushNotification(note, myDevice);`

if production is true, the device cannot receive the notification.
but if production is false, it works well.
Can anybody tell me the reason? Thank you very much!

**Comment by argon** [comment]
Are you using different tokens for production true/false. Do you receive any errors?

**Comment by haozxuan** [comment]
different environment need different certificate, and have different token. so look you err message.
