### ISSUE TITLE
Notification caused error: 8 for device  Device

### ISSUE THREAD

**Issue by teledna** [argon/node-apn#361]
i am facing invalid token issue. Below is the log
```
Notification caused error: 8 for device  Device {
  token: <Buffer 14 1c 25 bc 19 b1 bf 38 c7 53 e2 ab ae ec 4a b5 c8 de 9d 4e 96 73 79 0a 4d ec 12 bd 77 49 ea 51> } Notification {
  encoding: 'utf8',
  payload: { aps: { alert: 'Hello, from node-apn! You are number: 0' } },
  expiry: 0,
  identifier: 0,
  retryLimit: -1,
  device: undefined,
  alert: 'Hello, from node-apn! You are number: 0',
  badge: '0',
  sound: undefined,
  newsstandAvailable: undefined,
  contentAvailable: undefined,
  mdm: undefined,
  compiled: true,
  compiledPayload: '{"aps":{"alert":"Hello, from node-apn! You are number: 0"}}' }
  apn Raising error: +1ms 8 Notification {
  encoding: 'utf8',
  payload: { aps: { alert: 'Hello, from node-apn! You are number: 0' } },
  expiry: 0,
  identifier: 0,
  retryLimit: -1,
  device: undefined,
  alert: 'Hello, from node-apn! You are number: 0',
  badge: '0',
  sound: undefined,
  newsstandAvailable: undefined,
  contentAvailable: undefined,
  mdm: undefined,
  compiled: true,
  compiledPayload: '{"aps":{"alert":"Hello, from node-apn! You are number: 0"}}' } Device {
  token: <Buffer 14 1c 25 bc 19 b1 bf 38 c7 53 e2 ab ae ec 4a b5 c8 de 9d 4e 96 73 79 0a 4d ec 12 bd 77 49 ea 51> }
  apn Buffering 0 notifications for resending +2ms
  apn Socket closed +1ms 1
```

**Comment by argon** [comment]
Error 8 means you are using an invalid device token. How has the app been installed on the device?

**Comment by teledna** [comment]
Now i recreated the provisioning files. I got the notification once. second time when i send it is not throwing any error but no notification received on the phone

**Comment by argon** [comment]
Is the phone locked?

**Comment by teledna** [comment]
if phone is locked also notification will be received right

**Comment by argon** [comment]
Notifications do not create an alert when the app is open. It is left to the App to display UI instead

**Comment by teledna** [comment]
App is not open

**Comment by argon** [comment]
Have you switched on debugging?

`DEBUG=apn*` environment variable.

**Comment by teledna** [comment]
Yes and below is the log
`  apn Initialising connection +0ms
  apn Initialising module +5ms
  apn 1 left to send +5ms
token is :4e7ec0e711f2c497e84ff5ffb96b012b1ba0fb5d9fc5c5253d33724b296eba36
recipient not instanceof Device
token is a string
  apn 2 left to send +2ms
  apn Connection established +777ms
Connected
  apn Transmitting notification from buffer +0ms
  apn Socket drained +2ms 0
Notification transmitted to:N~ï¿½ï¿½ï¿½Äï¿½Oï¿½ï¿½ï¿½k+¿½ï¿½]ï¿½ï¿½ï¿½%=3rK)nï¿½6
  apn 1 left to send +0ms
  apn Transmitting notification from buffer +0ms
  apn Socket drained +1ms 0
Notification transmitted to:N~ï¿½ï¿½ï¿½Äï¿½Oï¿½ï¿½ï¿½k+¿½ï¿½]ï¿½ï¿½ï¿½%=3rK)nï¿½6
  apn 0 left to send +1ms`

**Comment by teledna** [comment]
Recreated the certificates. it is working now
