### ISSUE TITLE
OpenSSL "unable to get local issuer certificate" after following guide

### ISSUE THREAD

**Issue by siddo420** [argon/node-apn#363]
Thanks for the guide at https://github.com/argon/node-apn/wiki/Preparing-Certificates

I followed every step but I still get the error when I run test openssl command
```
verify error:num=20:unable to get local issuer certificate
```
I used Knuff and that seems to work fine  and sending notifications to my development app from the same Macbook.

Also, I need the certificate and key to use for pushd which uses node-apn behind the scenes.

**Comment by argon** [comment]
Which `openssl` step fails?

**Comment by siddo420** [comment]
I did not get any errors from openssl command, but when I run the test command 
```
openssl s_client -connect gateway.sandbox.push.apple.com:2195 -cert cert.pem -key key.pem
```
I get this error
```
verify error:num=20:unable to get local issuer certificate
```
I have already checked ports etc and Knuff works so that should not be an issue.

**Comment by argon** [comment]
You probably need to include the intermediate certificates in the certificate file.

https://www.apple.com/certificateauthority/

If your certificate is newly generated you will likely need the [WWDR Certificate (Expiring 02/07/23)](https://developer.apple.com/certificationauthority/AppleWWDRCA.cer) along with the [Apple Inc. Root Certificate](https://www.apple.com/appleca/AppleIncRootCertificate.cer).

Download each of them, convert them to PEM format and append to your `cert.pem` file

```
 $ openssl x509 -inform der -in AppleWWDRCA.cer -outform pem >> cert.pem
 $ openssl x509 -inform der -in AppleIncRootCertificate.cer -outform pem >> cert.pem
```

**Comment by argon** [comment]
You should use more descriptive titles for your issues. I can see you frequently open issues with useless titles like "question" or "error". You're not helping anyone by doing that, in fact some people are less likely to look at it properly.

Give issues more descriptive titles and people are going to find it much easier to help you. That way everyone benefits.

**Comment by siddo420** [comment]
sorry about the title ... I am sick and tired of fighting with these Apple certificate issues for the past several days (first Safari push which still does not work and now this iOS thing). 

You're right, certificate is new. I followed the steps you mentioned but same error again. I can't seem to get past this thing.

Entrust certificates were mentioned at http://stackoverflow.com/questions/22870710/apns-error20-unable-to-get-local-issuer-certificate-using-terminal, so I used that too 

openssl x509 -inform der -in entrust_2048_ca.cer -outform pem >> cert.pem

but got an error: unable to load certificate

**Comment by argon** [comment]
If you could email me the certificate at the email address on my github profile I will fix it for you.

**Comment by siddo420** [comment]
email sent

**Comment by siddo420** [comment]
problem seems to be with pushd

closing now.

Thanks.
