### ISSUE TITLE
Error connect UNKNOWN

### ISSUE THREAD

**Issue by volkanduru** [argon/node-apn#364]
we use for a long time this project.But getting this error. I noticed something.

nslookup gateway.push.apple.com
Addresses:  17.172.238.218, 17.172.232.39, 17.172.234.189, 17.172.233.145
          17.172.238.219, 17.172.232.230, 17.172.238.220, 17.172.233.5

but node-apn not connected to either of them.Choose a different IP.

  apn Initialising connection +0ms
  apn Loading Credentials +4ms
  apn 1 left to send +8ms
  apn Socket error occurred +230ms undefined { [Error: connect UNKNOWN 17.110.22
5.34:2195 - Local (undefined:undefined)]
  code: 'UNKNOWN',
  errno: 'UNKNOWN',
  syscall: 'connect',
  address: '17.110.225.34',
  port: 2195 }
  apn Destroying connection +2ms undefined
  apn Removing socket from pool +0ms undefined
  apn Raising error: +1ms { [Error: connect UNKNOWN 17.110.225.34:2195 - Local (
undefined:undefined)]
  code: 'UNKNOWN',
  errno: 'UNKNOWN',
  syscall: 'connect',
  address: '17.110.225.34',
  port: 2195 } undefined undefined
  apn Error occurred with trace: +1ms Error: connect UNKNOWN 17.110.225.34:2195
- Local (undefined:undefined)
    at Object.exports._errnoException (util.js:870:11)
    at exports._exceptionWithHostPort (util.js:893:20)
    at connect (net.js:843:14)
    at net.js:985:7
    at GetAddrInfoReqWrap.asyncCallback [as callback] (dns.js:63:16)
    at GetAddrInfoReqWrap.onlookup [as oncomplete] (dns.js:82:10)
{ [Error: connect UNKNOWN 17.110.225.34:2195 - Local (undefined:undefined)]
  code: 'UNKNOWN',
  errno: 'UNKNOWN',
  syscall: 'connect',
  address: '17.110.225.34',
  port: 2195 }
  apn Socket closed +4ms undefined
  apn Removing socket from pool +0ms undefined
Disconnected from APNS
  apn 1 left to send +1ms

**Comment by argon** [comment]
I'm pretty sure this is because you're trying to use the IP, why not the host name?

Are you able to connect with:

    openssl s_client -connect gateway.push.apple.com:2195 -key key.pem -cert cert.pem

—A

**Comment by volkanduru** [comment]
C:\openssl\bin>openssl s_client -connect gateway.push.apple.com:2195 -key key.pem -cert cert.pem
Loading 'screen' into random state - done
CONNECTED(000006E0)
depth=1 /C=US/O=Entrust, Inc./OU=www.entrust.net/rpa is incorporated by referenc
e/OU=(c) 2009 Entrust, Inc./CN=Entrust Certification Authority - L1C
verify error:num=20:unable to get local issuer certificate
verify return:0
---
Certificate chain
 0 s:/C=US/ST=California/L=Cupertino/O=Apple Inc./CN=gateway.push.apple.com
   i:/C=US/O=Entrust, Inc./OU=www.entrust.net/rpa is incorporated by reference/O
U=(c) 2009 Entrust, Inc./CN=Entrust Certification Authority - L1C
 1 s:/C=US/O=Entrust, Inc./OU=www.entrust.net/rpa is incorporated by reference/O
U=(c) 2009 Entrust, Inc./CN=Entrust Certification Authority - L1C
   i:/O=Entrust.net/OU=www.entrust.net/CPS_2048 incorp. by ref. (limits liab.)/O
U=(c) 1999 Entrust.net Limited/CN=Entrust.net Certification Authority (2048)
---
Server certificate
-----BEGIN CERTIFICATE-----
************** REMOVED **************
-----END CERTIFICATE-----
subject=/C=US/ST=California/L=Cupertino/O=Apple Inc./CN=gateway.push.apple.com
issuer=/C=US/O=Entrust, Inc./OU=www.entrust.net/rpa is incorporated by reference
/OU=(c) 2009 Entrust, Inc./CN=Entrust Certification Authority - L1C
---
Acceptable client certificate CA names
/C=US/O=Apple Inc./OU=Apple Certification Authority/CN=Apple Root CA
/C=US/O=Apple Inc./OU=Apple Worldwide Developer Relations/CN=Apple Worldwide Dev
eloper Relations Certification Authority
/C=US/O=Apple Inc./OU=Apple Certification Authority/CN=Apple Application Integra
tion Certification Authority
---
SSL handshake has read 3137 bytes and written 2289 bytes
---
New, TLSv1/SSLv3, Cipher is AES256-SHA
Server public key is 2048 bit
Compression: NONE
Expansion: NONE
SSL-Session:
    Protocol  : TLSv1
    Cipher    : AES256-SHA
    Session-ID:
    Session-ID-ctx:
    Master-Key: 33ACC42315F367B5C8076451D7355612E11F14657E15D4F627D732A06AE6AD0E
2E854115D29241D14EBF659CE586C721
    Key-Arg   : None
    Start Time: 1456841892
    Timeout   : 300 (sec)
    Verify return code: 20 (unable to get local issuer certificate)
---
read:errno=10093

**Comment by argon** [comment]
You require the entrust 2048 certificate. You must download this and pass it in the `ca` parameter.

https://www.entrust.net/downloads/binary/entrust_2048_ca.cer

**Comment by volkanduru** [comment]
Here is the my print all config and getting exception.

>node apntest.js
*******Config*****
{ cert: 'cert.pem',
  key: 'key.pem',
  ca: 'entrust_2048_ca.cer',
  pfx: null,
  passphrase: null,
  production: true,
  voip: false,
  address: 'gateway.push.apple.com',
  port: 2195,
  rejectUnauthorized: true,
  cacheLength: 1000,
  autoAdjustCache: true,
  maxConnections: 1,
  minConnections: 1,
  connectTimeout: 10000,
  connectionTimeout: 3600000,
  connectionRetryLimit: 10,
  buffersNotifications: true,
  fastMode: false,
  disableNagle: false,
  disableEPIPEFix: false }
*******Notification*****
{ encoding: 'utf8',
  payload: {},
  expiry: 0,
  priority: 10,
  retryLimit: -1,
  device: undefined,
  compiled: false,
  truncateAtWordEnd: false,
  _sound: 'ping.aiff',
  _alert: 'Test alert!' }
expriy:::0
************
  apn Initialising connection +0ms
  apn Loading Credentials +3ms
  apn 1 left to send +8ms
  apn Socket error occurred +57ms undefined { [Error: connect UNKNOWN 17.110.226
.220:2195 - Local (undefined:undefined)]
  code: 'UNKNOWN',
  errno: 'UNKNOWN',
  syscall: 'connect',
  address: '17.110.226.220',
  port: 2195 }
  apn Destroying connection +3ms undefined
  apn Removing socket from pool +0ms undefined
  apn Raising error: +3ms { [Error: connect UNKNOWN 17.110.226.220:2195 - Local
(undefined:undefined)]
  code: 'UNKNOWN',
  errno: 'UNKNOWN',
  syscall: 'connect',
  address: '17.110.226.220',
  port: 2195 } undefined undefined
  apn Error occurred with trace: +1ms Error: connect UNKNOWN 17.110.226.220:2195
 - Local (undefined:undefined)
    at Object.exports._errnoException (util.js:870:11)
    at exports._exceptionWithHostPort (util.js:893:20)
    at connect (net.js:843:14)
    at net.js:985:7
    at GetAddrInfoReqWrap.asyncCallback [as callback] (dns.js:63:16)
    at GetAddrInfoReqWrap.onlookup [as oncomplete] (dns.js:82:10)
{ [Error: connect UNKNOWN 17.110.226.220:2195 - Local (undefined:undefined)]
  code: 'UNKNOWN',
  errno: 'UNKNOWN',
  syscall: 'connect',
  address: '17.110.226.220',
  port: 2195 }
  apn Socket closed +4ms undefined
  apn Removing socket from pool +1ms undefined
Disconnected from APNS
  apn 1 left to send +0ms
^C

**Comment by volkanduru** [comment]
node apntest.js
{ cert: 'cert.pem',
  key: 'key.pem',
  ca: 'entrust_2048_ca.cer',
  pfx: null,
  passphrase: null,
  production: true,
  voip: false,
  address: 'gateway.push.apple.com',
  port: 2195,
  rejectUnauthorized: true,
  cacheLength: 1000,
  autoAdjustCache: true,
  maxConnections: 1,
  minConnections: 1,
  connectTimeout: 10000,
  connectionTimeout: 3600000,
  connectionRetryLimit: 10,
  buffersNotifications: true,
  fastMode: false,
  disableNagle: false,
  disableEPIPEFix: false }
{ encoding: 'utf8',
  payload: {},
  expiry: 0,
  priority: 10,
  retryLimit: -1,
  device: undefined,
  compiled: false,
  truncateAtWordEnd: false,
  _sound: 'ping.aiff',
  _alert: 'Test Alert!' }

  apn Initialising connection +0ms
  apn Loading Credentials +4ms
  apn 1 left to send +8ms
  apn Raising error: +10s [Error: Connect timed out] undefined undefined
  apn Error occurred with trace: +1ms Error: Connect timed out
    at Connection.<anonymous> (C:\Users\test\Downloads\nodejs\node_modules\apn\l
ib\connection.js:225:35)
    at Timer.listOnTimeout (timers.js:92:15)
**************SOCKET ERROR > Error: Connect timed out

**Comment by volkanduru** [comment]
I have new info capture network. I think what's causing this problem. 
(TCP packet out of state: First packet isn't SYN tcp_flags: RST-ACK)

**Comment by argon** [comment]
It sounds like you have network problems then or an underlying issue with Node.js. This clearly isn't a node-apn issue.

**Comment by volkanduru** [comment]
Argon i am sorry to bother you. Now I have tested this project this logicalparadox/apnagent notification send successfully completed it.

**Comment by argon** [comment]
So, `apnagent` works but `node-apn` does not. Is that correct?

**Comment by volkanduru** [comment]
Yes apnagent works, successfully sent notif.

**Comment by argon** [comment]
Both modules connect to Apple the same way, using the `tls` module in node.js. There must be some other underlying cause.

**Comment by volkanduru** [comment]
Sure! used node-apn for along time works smoothly.. 
I debug project. Getting result, maybe help.

  apn Initialising connection +46ms
  apn Loading Credentials +3ms
  apn 1 left to send +6ms
  apn:socket connecting to:  +41ms gateway.push.apple.com:2195
  apn Socket error occurred +5ms undefined { [Error: connect UNKNOWN 17.143.164.
10:2195 - Local (undefined:undefined)]
  code: 'UNKNOWN',
  errno: 'UNKNOWN',
  syscall: 'connect',
  address: '17.143.164.10',
  port: 2195 }
  apn Destroying connection +1ms undefined
  apn Removing socket from pool +1ms undefined
  apn:trace connection failed +1ms 1000
  apn Raising error: +1ms { [Error: connect UNKNOWN 17.143.164.10:2195 - Local (
undefined:undefined)]
  code: 'UNKNOWN',
  errno: 'UNKNOWN',
  syscall: 'connect',
  address: '17.143.164.10',
  port: 2195 } undefined undefined
  apn Error occurred with trace: +1ms Error: connect UNKNOWN 17.143.164.10:2195
Local (undefined:undefined)
    at Object.exports._errnoException (util.js:870:11)
    at exports._exceptionWithHostPort (util.js:893:20)
    at connect (net.js:843:14)
    at net.js:985:7
    at GetAddrInfoReqWrap.asyncCallback [as callback] (dns.js:63:16)
    at GetAddrInfoReqWrap.onlookup [as oncomplete] (dns.js:82:10)
{ [Error: connect UNKNOWN 17.143.164.10:2195 - Local (undefined:undefined)]
  code: 'UNKNOWN',
  errno: 'UNKNOWN',
  syscall: 'connect',
  address: '17.143.164.10',
  port: 2195 }
  apn Socket closed +3ms undefined
  apn Removing socket from pool +1ms undefined
Disconnected from APNS

**Comment by volkanduru** [comment]
I had to move the project different server location and it works. (I think problem is the node bug dns resolve part.. )

**Comment by volkanduru** [comment]
I did a test Node.js v0.10.32 previous version works successful :+1:  However, new version does not work...

**Comment by volkanduru** [comment]
No I've got "Transmission Error 5". I don't receive any errors but same device 5-6 push notification same time :(
