### ISSUE TITLE
I've got this "Transmission Error 5" after put some codes in sandbox mode

### ISSUE THREAD

**Issue by crapthings** [argon/node-apn#366]
Transmission Error 5

the token is an Random id from meteor method

sku3pdBt3SyZWDJMu like this

but somethings i've got 

Transmission Error 8

	// var path = Meteor.npmRequire('path')

	// console.log(process.argv[1])

	var apn = Meteor.npmRequire('apn')

	var options = {
		cert: "/Users/monsterstep/Desktop/aps/" + "cert.pem",
		key: "/Users/monsterstep/Desktop/aps/" + "key.pem",
		production: false
	}

	var token = Random.id()

	console.log(token)

	var service = new apn.connection(options)

	service.on("connected", function () {
		console.log("Connected")
	})

	service.on("completed", function () {
		console.log("Completed!")
	})

	service.on("transmitted", function (notification) {
		console.log("Transmitted: ", notification)
	})

	service.on("socketError", function (err) {
		console.log("Socket error", err.message)
	})

	service.on('transmissionError', function (err) {
		console.log("Transmission Error", err)
	})

	service.on("error", function (err) {
		console.log("Standard error", err)
	})

	function pushNotification() {
		var note = new apn.notification().setAlertText("helloworld")

		service.pushNotification(note, token)

		service.shutdown()
	}

	pushNotification()

	var opt = options

	var feedback = new apn.Feedback(opt)

	feedback.on("feedback", function (devices) {
		devices.forEach(function (item) {
			// Do something with item.device and item.time
			console.log('feedback wow', item)
		})
	})

	feedback.start()

**Comment by argon** [comment]
https://github.com/argon/node-apn/blob/master/lib/errors.js#L13

**Comment by crapthings** [comment]
thank you~ let me try

what is a device token ?

i work with cordova, can i use device.uuid as token ?

**Comment by crapthings** [comment]
i've use chance.js to get token like this below

chance.apple_token()
=> 'b50edac575bfba07dd019b28b2af7189a3ddda17c806ef14a9abbfd00533f67e'

but i still get Transmission Error 8

**Comment by argon** [comment]
You probably need to use this. I don't have experience with cordova. https://github.com/phonegap/phonegap-plugin-push

**Comment by crapthings** [comment]
still get Transmission Error 8

after Test certificates: i found

verify error:num=20:unable to get local issuer certificate

**Comment by argon** [comment]
https://github.com/argon/node-apn/issues/364#issuecomment-190935715

**Comment by crapthings** [comment]
openssl s_client -connect gateway.sandbox.push.apple.com:2195 -cert cert.pem -key key.pem # sandbox
    CONNECTED(00000003)
    depth=1 /C=US/O=Entrust, Inc./OU=www.entrust.net/rpa is incorporated by reference/OU=(c) 2009 Entrust, Inc./CN=Entrust Certification Authority - L1C
    verify error:num=20:unable to get local issuer certificate
    verify return:0
    ---
    Certificate chain
     0 s:/C=US/ST=California/L=Cupertino/O=Apple Inc./CN=gateway.sandbox.push.apple.com
       i:/C=US/O=Entrust, Inc./OU=www.entrust.net/rpa is incorporated by reference/OU=(c) 2009 Entrust, Inc./CN=Entrust Certification Authority - L1C
     1 s:/C=US/O=Entrust, Inc./OU=www.entrust.net/rpa is incorporated by reference/OU=(c) 2009 Entrust, Inc./CN=Entrust Certification Authority - L1C
       i:/O=Entrust.net/OU=www.entrust.net/CPS_2048 incorp. by ref. (limits liab.)/OU=(c) 1999 Entrust.net Limited/CN=Entrust.net Certification Authority (2048)
    ---
    Server certificate
    -----BEGIN CERTIFICATE-----
    MIIFMzCCBBugAwIBAgIETCMmsDANBgkqhkiG9w0BAQUFADCBsTELMAkGA1UEBhMC
    VVMxFjAUBgNVBAoTDUVudHJ1c3QsIEluYy4xOTA3BgNVBAsTMHd3dy5lbnRydXN0
    Lm5ldC9ycGEgaXMgaW5jb3Jwb3JhdGVkIGJ5IHJlZmVyZW5jZTEfMB0GA1UECxMW
    KGMpIDIwMDkgRW50cnVzdCwgSW5jLjEuMCwGA1UEAxMlRW50cnVzdCBDZXJ0aWZp
    Y2F0aW9uIEF1dGhvcml0eSAtIEwxQzAeFw0xNDA1MjMxNzQyNDJaFw0xNjA1MjQw
    NzA1MTNaMHQxCzAJBgNVBAYTAlVTMRMwEQYDVQQIEwpDYWxpZm9ybmlhMRIwEAYD
    VQQHEwlDdXBlcnRpbm8xEzARBgNVBAoTCkFwcGxlIEluYy4xJzAlBgNVBAMTHmdh
    dGV3YXkuc2FuZGJveC5wdXNoLmFwcGxlLmNvbTCCASIwDQYJKoZIhvcNAQEBBQAD
    ggEPADCCAQoCggEBAOQpUlXpU3+LJ2XR01QdVooN7S9OFOINp3/tomPaenQAwFGo
    qIakKFcN7AotWLFXFcR0QXKJkn4PL/zPKDBucyRFkc79S5+ZraGRISWfi7G8XeaG
    G3GzgeVQ977Qrn0IdCswnbwLsJoErnmq4AveQajUbYueR9SxhkWBwMimSxXzXoOS
    XUOPzRvzObCxVZrvBBDSRJCeNVnVxtCmb17DM3+z5GZatBwWnvw0jgvSQsgof+uC
    idXgqcN4msv3tVH54ipmuD9kbbwvtnDCHBZRXMMmhUfFXZRuE8GBEbPfVkqB16ad
    JV4TVrVxwFENwdnsX9CXavHCgFJhtHRWKOoCH48CAwEAAaOCAY0wggGJMAsGA1Ud
    DwQEAwIFoDAdBgNVHSUEFjAUBggrBgEFBQcDAQYIKwYBBQUHAwIwMwYDVR0fBCww
    KjAooCagJIYiaHR0cDovL2NybC5lbnRydXN0Lm5ldC9sZXZlbDFjLmNybDBkBggr
    BgEFBQcBAQRYMFYwIwYIKwYBBQUHMAGGF2h0dHA6Ly9vY3NwLmVudHJ1c3QubmV0
    MC8GCCsGAQUFBzAChiNodHRwOi8vYWlhLmVudHJ1c3QubmV0LzIwNDgtbDFjLmNl
    cjBKBgNVHSAEQzBBMDUGCSqGSIb2fQdLAjAoMCYGCCsGAQUFBwIBFhpodHRwOi8v
    d3d3LmVudHJ1c3QubmV0L3JwYTAIBgZngQwBAgIwKQYDVR0RBCIwIIIeZ2F0ZXdh
    eS5zYW5kYm94LnB1c2guYXBwbGUuY29tMB8GA1UdIwQYMBaAFB7xq4kG+EkPATN3
    7hR67hl8kyhNMB0GA1UdDgQWBBSSGfpGPmr9+FPcqRiStH0iKRBL7DAJBgNVHRME
    AjAAMA0GCSqGSIb3DQEBBQUAA4IBAQAkj6+okMFVl7NHqQoii4e4iPDFiia+LmHX
    BCc+2UEOOjilYWYoZ61oeqRXQ2b4Um3dT/LPmzMkKmgEt9epKNBLA6lSkL+IzEnF
    wLQCHkL3BgvV20n5D8syzREV+8RKmSqiYmrF8dFq8cDcstu2joEKd173EfrymWW1
    fMeaYTbjrn+vNkgM94+M4c/JnIDOhiPPbeAx9TESQZH+/6S98hrbuPIIlmaOJsOT
    GMOUWeOTHXTCfGb1EM4SPVcyCW28TlWUBl8miqnsEO8g95jZZ25wFANlVxhfxBnP
    fwUYU5NTM3h0xi3rIlXwAKD6zLKipcQ/YXRx7oMYnAm53tfU2MxV
    -----END CERTIFICATE-----
    subject=/C=US/ST=California/L=Cupertino/O=Apple Inc./CN=gateway.sandbox.push.apple.com
    issuer=/C=US/O=Entrust, Inc./OU=www.entrust.net/rpa is incorporated by reference/OU=(c) 2009 Entrust, Inc./CN=Entrust Certification Authority - L1C
    ---
    Acceptable client certificate CA names
    /C=US/O=Apple Inc./OU=Apple Certification Authority/CN=Apple Root CA
    /C=US/O=Apple Inc./OU=Apple Worldwide Developer Relations/CN=Apple Worldwide Developer Relations Certification Authority
    /C=US/O=Apple Inc./OU=Apple Certification Authority/CN=Apple Application Integration Certification Authority
    ---
    SSL handshake has read 3160 bytes and written 2175 bytes
    ---
    New, TLSv1/SSLv3, Cipher is AES256-SHA
    Server public key is 2048 bit
    Secure Renegotiation IS supported
    Compression: NONE
    Expansion: NONE
    SSL-Session:
        Protocol  : TLSv1
        Cipher    : AES256-SHA
        Session-ID:
        Session-ID-ctx:
        Master-Key: 994D783236624DBA67058DDFDE5ECA8A4ED7971B585289390BD9E64265E7F0A75C7FDEAA152FC0657E816FCD9869EEA1
        Key-Arg   : None
        Start Time: 1457365935
        Timeout   : 300 (sec)
        Verify return code: 0 (ok)
    ---

**Comment by argon** [comment]
From the comment above:
> You require the entrust 2048 certificate. You must download this and pass it in the ca parameter.
>
> https://www.entrust.net/downloads/binary/entrust_2048_ca.cer

**Comment by crapthings** [comment]
what is a ca parameter

pass to where ?

**Comment by argon** [comment]
https://github.com/argon/node-apn/blob/master/doc/connection.markdown

Yes it must be converted to pem

**Comment by crapthings** [comment]
after do these steps

    openssl x509 -in cert.cer -inform DER -outform PEM -out cert.pem

    openssl pkcs12 -in key.p12 -out key.pem -nodes

    openssl s_client -connect gateway.sandbox.push.apple.com:2195 -cert cert.pem -key key.pem -CAfile "Entrust.net Certification Authority (2048).pem"

mylog seems okay

    openssl s_client -connect gateway.sandbox.push.apple.com:2195 -cert cert.pem -key key.pem -CAfile "Entrust.net Certification Authority (2048).pem"
    CONNECTED(00000003)
    depth=2 /O=Entrust.net/OU=www.entrust.net/CPS_2048 incorp. by ref. (limits liab.)/OU=(c) 1999 Entrust.net Limited/CN=Entrust.net Certification Authority (2048)
    verify return:1
    depth=1 /C=US/O=Entrust, Inc./OU=www.entrust.net/rpa is incorporated by reference/OU=(c) 2009 Entrust, Inc./CN=Entrust Certification Authority - L1C
    verify return:1
    depth=0 /C=US/ST=California/L=Cupertino/O=Apple Inc./CN=gateway.sandbox.push.apple.com
    verify return:1
    ---
    Certificate chain
     0 s:/C=US/ST=California/L=Cupertino/O=Apple Inc./CN=gateway.sandbox.push.apple.com
       i:/C=US/O=Entrust, Inc./OU=www.entrust.net/rpa is incorporated by reference/OU=(c) 2009 Entrust, Inc./CN=Entrust Certification Authority - L1C
     1 s:/C=US/O=Entrust, Inc./OU=www.entrust.net/rpa is incorporated by reference/OU=(c) 2009 Entrust, Inc./CN=Entrust Certification Authority - L1C
       i:/O=Entrust.net/OU=www.entrust.net/CPS_2048 incorp. by ref. (limits liab.)/OU=(c) 1999 Entrust.net Limited/CN=Entrust.net Certification Authority (2048)
    ---
    Server certificate
    -----BEGIN CERTIFICATE-----
    MIIFMzCCBBugAwIBAgIETCMmsDANBgkqhkiG9w0BAQUFADCBsTELMAkGA1UEBhMC
    VVMxFjAUBgNVBAoTDUVudHJ1c3QsIEluYy4xOTA3BgNVBAsTMHd3dy5lbnRydXN0
    Lm5ldC9ycGEgaXMgaW5jb3Jwb3JhdGVkIGJ5IHJlZmVyZW5jZTEfMB0GA1UECxMW
    KGMpIDIwMDkgRW50cnVzdCwgSW5jLjEuMCwGA1UEAxMlRW50cnVzdCBDZXJ0aWZp
    Y2F0aW9uIEF1dGhvcml0eSAtIEwxQzAeFw0xNDA1MjMxNzQyNDJaFw0xNjA1MjQw
    NzA1MTNaMHQxCzAJBgNVBAYTAlVTMRMwEQYDVQQIEwpDYWxpZm9ybmlhMRIwEAYD
    VQQHEwlDdXBlcnRpbm8xEzARBgNVBAoTCkFwcGxlIEluYy4xJzAlBgNVBAMTHmdh
    dGV3YXkuc2FuZGJveC5wdXNoLmFwcGxlLmNvbTCCASIwDQYJKoZIhvcNAQEBBQAD
    ggEPADCCAQoCggEBAOQpUlXpU3+LJ2XR01QdVooN7S9OFOINp3/tomPaenQAwFGo
    qIakKFcN7AotWLFXFcR0QXKJkn4PL/zPKDBucyRFkc79S5+ZraGRISWfi7G8XeaG
    G3GzgeVQ977Qrn0IdCswnbwLsJoErnmq4AveQajUbYueR9SxhkWBwMimSxXzXoOS
    XUOPzRvzObCxVZrvBBDSRJCeNVnVxtCmb17DM3+z5GZatBwWnvw0jgvSQsgof+uC
    idXgqcN4msv3tVH54ipmuD9kbbwvtnDCHBZRXMMmhUfFXZRuE8GBEbPfVkqB16ad
    JV4TVrVxwFENwdnsX9CXavHCgFJhtHRWKOoCH48CAwEAAaOCAY0wggGJMAsGA1Ud
    DwQEAwIFoDAdBgNVHSUEFjAUBggrBgEFBQcDAQYIKwYBBQUHAwIwMwYDVR0fBCww
    KjAooCagJIYiaHR0cDovL2NybC5lbnRydXN0Lm5ldC9sZXZlbDFjLmNybDBkBggr
    BgEFBQcBAQRYMFYwIwYIKwYBBQUHMAGGF2h0dHA6Ly9vY3NwLmVudHJ1c3QubmV0
    MC8GCCsGAQUFBzAChiNodHRwOi8vYWlhLmVudHJ1c3QubmV0LzIwNDgtbDFjLmNl
    cjBKBgNVHSAEQzBBMDUGCSqGSIb2fQdLAjAoMCYGCCsGAQUFBwIBFhpodHRwOi8v
    d3d3LmVudHJ1c3QubmV0L3JwYTAIBgZngQwBAgIwKQYDVR0RBCIwIIIeZ2F0ZXdh
    eS5zYW5kYm94LnB1c2guYXBwbGUuY29tMB8GA1UdIwQYMBaAFB7xq4kG+EkPATN3
    7hR67hl8kyhNMB0GA1UdDgQWBBSSGfpGPmr9+FPcqRiStH0iKRBL7DAJBgNVHRME
    AjAAMA0GCSqGSIb3DQEBBQUAA4IBAQAkj6+okMFVl7NHqQoii4e4iPDFiia+LmHX
    BCc+2UEOOjilYWYoZ61oeqRXQ2b4Um3dT/LPmzMkKmgEt9epKNBLA6lSkL+IzEnF
    wLQCHkL3BgvV20n5D8syzREV+8RKmSqiYmrF8dFq8cDcstu2joEKd173EfrymWW1
    fMeaYTbjrn+vNkgM94+M4c/JnIDOhiPPbeAx9TESQZH+/6S98hrbuPIIlmaOJsOT
    GMOUWeOTHXTCfGb1EM4SPVcyCW28TlWUBl8miqnsEO8g95jZZ25wFANlVxhfxBnP
    fwUYU5NTM3h0xi3rIlXwAKD6zLKipcQ/YXRx7oMYnAm53tfU2MxV
    -----END CERTIFICATE-----
    subject=/C=US/ST=California/L=Cupertino/O=Apple Inc./CN=gateway.sandbox.push.apple.com
    issuer=/C=US/O=Entrust, Inc./OU=www.entrust.net/rpa is incorporated by reference/OU=(c) 2009 Entrust, Inc./CN=Entrust Certification Authority - L1C
    ---
    Acceptable client certificate CA names
    /C=US/O=Apple Inc./OU=Apple Certification Authority/CN=Apple Root CA
    /C=US/O=Apple Inc./OU=Apple Worldwide Developer Relations/CN=Apple Worldwide Developer Relations Certification Authority
    /C=US/O=Apple Inc./OU=Apple Certification Authority/CN=Apple Application Integration Certification Authority
    ---
    SSL handshake has read 3160 bytes and written 2175 bytes
    ---
    New, TLSv1/SSLv3, Cipher is AES256-SHA
    Server public key is 2048 bit
    Secure Renegotiation IS supported
    Compression: NONE
    Expansion: NONE
    SSL-Session:
        Protocol  : TLSv1
        Cipher    : AES256-SHA
        Session-ID:
        Session-ID-ctx:
        Master-Key: A7392F73805468B6D77AC477159A7C78D93214C89888D9C5A2E3D7C57761CEDB1B434066DFAB0F9C11AD6229689A6228
        Key-Arg   : None
        Start Time: 1457368067
        Timeout   : 300 (sec)
        Verify return code: 0 (ok)
    ---

but i still get Transmission Error 8

	// var path = Meteor.npmRequire('path')

	// console.log(process.argv[1])

	var Chance = Meteor.npmRequire("chance")

	var chance = new Chance()

	var apn = Meteor.npmRequire('apn')

	var options = {
		cert: "/Users/monsterstep/Desktop/aps/" + "cert.pem",
		key: "/Users/monsterstep/Desktop/aps/" + "key.pem",
		ca: "/Users/monsterstep/Desktop/aps/" + "Entrust.net Certification Authority (2048).pem",
		production: false
	}

	var token = "6075373d0a2b9b61179093b01a2b72a7a976de97252d2307d637b86856defe37"

	console.log(token)

	var service = new apn.connection(options)

	service.on("connected", function () {
		console.log("Connected")
	})

	service.on("completed", function () {
		console.log("Completed!")
	})

	service.on("transmitted", function (notification) {
		console.log("Transmitted: ", notification)
	})

	service.on("socketError", function (err) {
		console.log("Socket error", err.message)
	})

	service.on('transmissionError', function (err) {
		console.log("Transmission Error", err)
	})

	service.on("error", function (err) {
		console.log("Standard error", err)
	})

	function pushNotification() {
		var note = new apn.notification().setAlertText("helloworld")

		service.pushNotification(note, token)

		service.shutdown()
	}

	pushNotification()

	var opt = options

	var feedback = new apn.Feedback(opt)

	feedback.on("feedback", function (devices) {
		devices.forEach(function (item) {
			// Do something with item.device and item.time
			console.log('feedback wow', item)
		})
	})

	feedback.start()

	Meteor.methods({

		test: function (a) {
			console.log(a)
		}

	})
		
the server logs

	=> Meteor server restarted
	I20160308-00:28:49.596(8)? Connected
	I20160308-00:28:49.702(8)? Transmitted:  { encoding: 'utf8',
	I20160308-00:28:49.703(8)?   payload:
	I20160308-00:28:49.703(8)?    { aps:
	I20160308-00:28:49.703(8)?       { badge: undefined,
	I20160308-00:28:49.703(8)?         sound: undefined,
	I20160308-00:28:49.703(8)?         alert: 'helloworld',
	I20160308-00:28:49.703(8)?         'url-args': undefined,
	I20160308-00:28:49.704(8)?         category: undefined } },
	I20160308-00:28:49.704(8)?   expiry: 0,
	I20160308-00:28:49.704(8)?   priority: 10,
	I20160308-00:28:49.704(8)?   retryLimit: -1,
	I20160308-00:28:49.704(8)?   device: undefined,
	I20160308-00:28:49.704(8)?   compiled: '{"aps":{"alert":"helloworld"}}',
	I20160308-00:28:49.704(8)?   truncateAtWordEnd: false,
	I20160308-00:28:49.704(8)?   _alert: 'helloworld' }
	I20160308-00:28:49.704(8)? Completed!
	I20160308-00:28:50.051(8)? Transmission Error 8

**Comment by crapthings** [comment]
should i do this ?
https://github.com/argon/node-apn/issues/363#issuecomment-189017003

**Comment by argon** [comment]
Error 8 is caused by an invalid token. Double check to ensure the certificates you are using to connect to APNS match the provisioning profile of your app.

**Comment by crapthings** [comment]
after adding iOS Provisioning Profiles (Development) at dev center

there's no problem with token
