### ISSUE TITLE
Connections never close

### ISSUE THREAD

**Issue by thegalah** [argon/node-apn#369]
I've noticed the connections to apn server never close. My application was using a huge amount of memory (gigabytes). I do a netstat and see that it has thousands of connections still open to the apn server ip address.

**Comment by HKskn** [comment]
Define connection globally and use it in your functions' scope. When your application is completed, you can shutdown the connection with 'shutdown'  and 'removeAllListeners' method to reusing socket.

**Comment by thegalah** [comment]
Awesome that worked!
