### ISSUE TITLE
Socket Error

### ISSUE THREAD

**Issue by barocsi** [argon/node-apn#370]
I keep getting this after a sudden:
Socket Error
ECONNREFUSED
17.110.227.35

**Comment by margelov** [comment]
yeah, same here.
I keep getting same error. Began all of a sudden. Has been working pretty smoothly before. 
 apn Raising error: +1ms { [Error: socket hang up] code: 'ECONNRESET', sslError: undefined } undefined undefined
  apn Error occurred with trace: +0ms Error: socket hang up
    at SecurePair.error (tls.js:1010:23)
    at EncryptedStream.CryptoStream._done (tls.js:702:22)
    at CleartextStream.read [as _read] (tls.js:498:24)
    at CleartextStream.Readable.read (_stream_readable.js:340:10)
    at EncryptedStream.onCryptoStreamFinish (tls.js:303:47)
    at EncryptedStream.g (events.js:180:16)
    at EncryptedStream.emit (events.js:117:20)
    at finishMaybe (_stream_writable.js:359:12)
    at endWritable (_stream_writable.js:366:3)
    at EncryptedStream.Writable.end (_stream_writable.js:344:5)
    at EncryptedStream.CryptoStream.end (tls.js:640:31)
    at Socket.onend (_stream_readable.js:501:10)
    at Socket.g (events.js:180:16)
    at Socket.emit (events.js:117:20)
    at _stream_readable.js:943:16
    at process._tickDomainCallback (node.js:463:13)

I tried to connect to the Apple gateway using openssl client and same credentials and everything is ok.
Really no clue what changed / happened.

**Comment by argon** [comment]
ECONNRESET is not a new error for APNS, a increased frequency is probably a change on Apples side but in reality it should be an error you can ignore. If everything still seems to be working correctly aside from the error then it's nothing to worry about.

—A

**Comment by margelov** [comment]
Actually it prevents the connection to be made and thus the notification to be sent. So nothing is working.
I guess this is somehow related to the disabling of sslv3 on Apple's side. Tries different secureProtocol and secureOptions options but nothing seems to be working(

**Comment by argon** [comment]
Which version of node are you running?

—A

**Comment by margelov** [comment]
0.10.42 and 0.12.2 same error

**Comment by argon** [comment]
Please post the configuration you have been using. This is unlikely to be due to SSLv3 as that happened last year and has had no impact on node-apn use.

**Comment by margelov** [comment]
```
{
            production: true,
            maxConnections: 1,
            fastMode:true,
            buffersNotifications:true,
            passphrase:"blablabla",
            cert: fs.readFileSync("/some/path/to/cert/file.pem"),
            key:  fs.readFileSync("/some/path/to/key/file.pem")
       };
```

**Comment by margelov** [comment]
I tried setting different options and it doesn't matter... And the openssl command line client connects without problems from the same box, so should not be a matter of server configurations/blocked ports etc. And it has been working really fine up till some moment in March when it suddenly stopped
