### ISSUE TITLE
Connect to APNS server timeout

### ISSUE THREAD

**Issue by yaochangjun** [argon/node-apn#372]
Now I can receive the notification in iOS from APNs ,but It always output connect  timeout in nodejs console . How to stop it?

this is my code

```
 var apn = require('apn');

 var pushOptions = {
       production: false,
       passphrase:"XXXXXX",
       cert: "cert_developer.pem", 
       key: "key_developer.pem",   
       connectionTimeout:10000,
       errorCallback: function(err,notifcation){
           console.log(err + ' :: ' + notifcation);
       }
 }

module.exports.sendOneNotification = function (token, options,cb) {

    var apnConnection = new apn.Connection(pushOptions),
        device = new apn.Device(token),
        note = new apn.Notification()

    options.expire = options.expire || 60 * 60 * 24;


    apnConnection.on("error", function (err) {
        // do error handling here
        console.log("Notification error with:" + err)
    })

    apnConnection.on("transmitted", function (notification, device) {
        console.log("Notification transmitted to:" + device.token.toString("hex"));
    });

    apnConnection.on("timeout", function () {
        console.log("Connection Timeout To APNS");

    });

    apnConnection.on("disconnected", function () {
        console.log("Disconnected from APNS");
    });

    apnConnection.on("socketError with APNS", console.error);

    apnConnection.on("transmissionError", function (errCode, notification, device) {
        console.error("Notification caused error: " + errCode + " for device ", device, notification);
       
        if (errCode === 8) {
            console.log("A error code of 8 indicates that the device token is invalid. This could be for a number of reasons - are you using the correct environment? i.e. Production vs. Sandbox");
        }
    });

    note.expiry = Math.floor(Date.now() / 1000) + options.expire || (60);
    note.badge = options.badge || 1;
    note.alert = options.alert || "test";
    note.sound = options.sound || 'default';
    note.payload = {
        'custom': {
            "custom": options.message || {}
        }
    };
    note.device = device;
    apnConnection.pushNotification(note, device);

}
```

Here is the output in console

> [2016-03-21 18:03:00.193] [INFO] console - Notification transmitted to:5b7b026ea74c86063142d0c4834ced496efd14af59b51b25689023ccba6760e6
> [2016-03-21 18:03:10.195] [INFO] console - Connection Timeout To APNS
> [2016-03-21 18:03:10.199] [INFO] console - Disconnected from APNS
> [2016-03-21 18:16:28.683] [INFO] console - Disconnected from APNS
> [2016-03-21 18:16:38.973] [INFO] console - Connection Timeout To APNS
> [2016-03-21 18:16:38.974] [INFO] console - Disconnected from APNS
> [2016-03-21 18:16:50.271] [INFO] console - Connection Timeout To APNS
> [2016-03-21 18:16:50.273] [INFO] console - Disconnected from APNS
> [2016-03-21 18:17:00.582] [INFO] console - Connection Timeout To APNS
> [2016-03-21 18:17:00.584] [INFO] console - Disconnected from APNS
> [2016-03-21 18:17:10.799] [INFO] console - Connection Timeout To APNS
> [2016-03-21 18:17:10.801] [INFO] console - Disconnected from APNS
> [2016-03-21 18:17:21.091] [INFO] console - Connection Timeout To APNS
> [2016-03-21 18:17:21.092] [INFO] console - Disconnected from APNS
...........

**Comment by barocsi** [comment]
+1 for me, in my server logs I always get this timeout error event fired.

**Comment by florianreinhart** [comment]
Please provide more information about your environment.

**Comment by barocsi** [comment]
Please be more specific. Its running under Debian/ NodeJs v4.5 + Loopback 2.24. Production environment. 
Is there any debug information I can provide from the event? It does not return anything.

**Comment by florianreinhart** [comment]
The most important information is your node-apn version 😉

**Comment by barocsi** [comment]
Ah for me it was obvious to be the most up to date. But turned out the question is legitimate, because it's lagging behind the master with version 1.7.5.

**Comment by florianreinhart** [comment]
OK. Then please try updating to 1.7.8, which is the latest version of the 1.x branch.

**Comment by barocsi** [comment]
Thanks, I will try to implement the master, it seems pretty well refined tho.
