### ISSUE TITLE
APN connection not established

### ISSUE THREAD

**Issue by vijayaa** [argon/node-apn#373]
Throwing `uncaughtException: error:0906A068:PEM routines:PEM_do_header:bad password` error.
Certificates are valid
telnet gateway.sandbox.push.apple.com 2195 is working fine
openssl s_client -connect gateway.sandbox.push.apple.com:2195  -cert PushChatCert.pem -key PushChatKey.pem  is working fine

**Comment by argon** [comment]
`bad password` means the password is wrong, there is no mystery here.

**Comment by vijayaa** [comment]
But password is correct . The commandopenssl s_client -connect gateway.sandbox.push.apple.com:2195 -cert PushChatCert.pem -key PushChatKey.pem is working fine

**Comment by argon** [comment]
You need to verify the password and ensure that the correct certificate is being loaded. Are you using the feedback service?

—A
