### ISSUE TITLE
pem files

### ISSUE THREAD

**Issue by joelwass** [argon/node-apn#374]
where is apn looking for the cert and key pem files to be located? Should we import them with require('../path/to/cert.pem')? or should they be in the same directory?

**Comment by argon** [comment]
https://github.com/argon/node-apn/blob/master/doc/connection.markdown

**Comment by argon** [comment]
```js
let connection = apn.Connection({
    cert: "../path/to/cert.pem",
    key: "../path/to/key.pem"
});
```

**Comment by joelwass** [comment]
perfect thank you
