### ISSUE TITLE
Notification transmitted to: binary

### ISSUE THREAD

**Issue by joelwass** [argon/node-apn#375]
why would i be getting the following output for Notification Transmitted To.... How should we be storing the device Token in our db?
![screen shot 2016-03-29 at 11 56 49 am](https://cloud.githubusercontent.com/assets/7344422/14114601/81600cd0-f5a5-11e5-93a6-7eb37a85e337.png)

**Comment by argon** [comment]
That means the token is invalid, check you're targeting the correct environment, sandbox vs prod.

**Comment by joelwass** [comment]
![screen shot 2016-03-29 at 12 03 06 pm](https://cloud.githubusercontent.com/assets/7344422/14114740/3cd4da72-f5a6-11e5-8055-7357fdbd6454.png)

**Comment by argon** [comment]
In that case the token you're trying to send to is probably for the sandbox environment.

**Comment by joelwass** [comment]
how do i designate that i want to target the production environment when i run my app from xcode onto my iphone? is it in the run or profile scheme in xcode, or is it designated elsewhere? Much appreciation for the help

**Comment by argon** [comment]
The production environment is used when signed by a distribution certificate. A development certificate will use the sandbox environment.

—A

**Comment by joelwass** [comment]
Here is how I was previously accessing the device id in swift.
![screen shot 2016-03-30 at 8 22 40 pm](https://cloud.githubusercontent.com/assets/7344422/14161905/4366ec26-f6b5-11e5-8183-3b41078ccb51.png)
![screen shot 2016-03-30 at 8 22 33 pm](https://cloud.githubusercontent.com/assets/7344422/14161910/48b6219c-f6b5-11e5-9a0b-6af50b245f36.png)


I then tried using the udid provided on itunes for my phone. I would think this identifier is the identifier that will be used to identify a phone. and i'm still getting more or less gibberish with 'Notification Transmitted To:' as seen in the following screen shot
![screen shot 2016-03-30 at 8 21 44 pm](https://cloud.githubusercontent.com/assets/7344422/14161891/3199d5a8-f6b5-11e5-81e9-a190576c7aae.png)

**Comment by argon** [comment]
The code is fine but your certificate does not match the app. Ensure:

- bundle ID matches
- Push Notifications entitlement is enabled
- correct environment is being used (sandbox vs. Production)

**Comment by argon** [comment]
If everything looks ok then regenerating the certificate seems to always fix this problem

**Comment by joelwass** [comment]
I wasn't handling push notifications when the app was running properly..... sorry for the barrage of questions - thanks again for your patience.
