### ISSUE TITLE
1.7.5 does not accept aps payload in Notification constructor

### ISSUE THREAD

**Issue by agnoster** [argon/node-apn#377]
Previously we could create a Notification with a payload like so:

    var notification = new apn.Notification({ aps: { badge: 1, message: "Hi there!" }})

However, b0bd4e7ba12d1fd0d4b841db6a3ada9232968a55 broke this behavior.

I'd be happy to contribute to fixing this issue, though it seems the easiest might be to simply revert that commit?

**Comment by argon** [comment]
Could you try out https://github.com/argon/node-apn/pull/378 to check that it matches your use case before I merge?

**Comment by agnoster** [comment]
Ooh, nice. I'll give it a try!

**Comment by agnoster** [comment]
(From examining the code it definitely looks like it should solve my issue, though!)

**Comment by argon** [comment]
I'm in no rush to release as my focus is on the http2 stuff. Let me know whenever you get to it and I'll get it sorted then.

**Comment by agnoster** [comment]
Yeah, that seems like a pretty big undertaking! I'd love to get a bugfix out so we can upgrade to 1.7.6 so I'm definitely motivated to test it out :-) Just want to finish up some things I'm working on now because it's always a pain for me setting up to test push notifications so... switching costs
