### ISSUE TITLE
Crashes when certificate is expired

### ISSUE THREAD

**Issue by etiennea** [argon/node-apn#380]
Should just log an error no?

**Comment by argon** [comment]
It is probably crashing because you haven't attached an `error` handler. Expired certificates are a fatal error for the module so it correctly emits an `error`.

**Comment by cbratschi** [comment]
I had the same issue. Adding an 'error' handler to the Feedback instance solved this issue.

**Comment by T-SEA** [comment]
Where do you add the error handler?
