### ISSUE TITLE
Module initialisation error on notification Error: EMFILE

### ISSUE THREAD

**Issue by BEYONDi** [argon/node-apn#387]
The following error is thrown at the last device token of just over 5000. I initially thought it was an issue with my key, but if I run a test with a handful of device tokens I do not receive this error and the notification is sent successfully. Thank you for your time.

apn Initialising connection +0ms
  apn Loading Credentials +0ms
  apn 1 left to send +0ms
  apn Module initialisation error: +2s { [Error: EMFILE, open 'path/to/key.pem'] errno: -24, code: 'EMFILE', path: 'path/to/key.pem' }
  apn Raising error: +2ms 513

**Comment by BEYONDi** [comment]
In addition, the following is at the last bit printed to stdout:
/var/test/node_modules/q/q.js:151
                throw e;
                      ^
Error: EMFILE, open 'path/to/key.pem'
    at Error (native)

**Comment by BEYONDi** [comment]
New info: I went back and decided to attempt batching of 1000 notifications at a time and it is working. It seems that the code has a limit on the number of notifications it can handle?

**Comment by argon** [comment]
There isn't a limit. `EMFILE` is "too many open files". There is a problem with your machine or the way you are using the module.

**Comment by BEYONDi** [comment]
I found that the original developer implemented the module in such a way that the connection method was called for each device_token.
