### ISSUE TITLE
Closing Connections & Moving On

### ISSUE THREAD

**Issue by medoix** [argon/node-apn#388]
So i am trying everything i can find to close the connection after notifications are sent but nothing i do works and the script just sits there waiting for something and not moving on to my next logic section.

I have tried the connetionTimeout option and also the connection.shutdown() functions it still sits in a running state.

The code i have currently is below
```
for(d in device){
              console.log('Device ' + d + ' Type: ' + JSON.stringify(device[d].type));
              console.log('Device ' + d + ' ID: ' + JSON.stringify(device[d].devId));
              if(device[d].type == "ios"){
                var myDevice = new apn.Device(device[d].devId);
                var note = new apn.Notification();
                note.expiry = Math.floor(Date.now() / 1000) + 3600; // Expires 1 hour from now.
                note.badge = 1;
                note.sound = "ping.aiff";
                note.alert = "\uD83D\uDCE7 \u2709 You have a new message";
                note.payload = {'messageFrom': 'Caroline'};
                apnConnection.pushNotification(note, myDevice);
                console.log('Push Sent To: ' + device[d].devId);
              } else if(device[d].type == "android"){
                registrationIds.push(device[d].devId);
              }
            }
            apnConnection.once('completed', function () {
              console.log("pending queue is empty");
              apnConnection.shutdown();
            });
```

I see the text "pending queue is empty" but the connections do not shutdown and the script just sits waiting instead of moving on to the next section....

**Comment by argon** [comment]
I don't understand what you mean by "next section" that raises red flags

**Comment by medoix** [comment]
thanks @argon, i have the above code inside a request() statement that gets the device types and ID's from an API i have. As you can see i iterate through each device returned to check if they are ios or android. For each ios device i set the note details and then run apnConnection.pushNotification(note, myDevice);  i also do similar for gcm (and it does actually go through all android devices also so my assumption of it "not moving to the next function" was incorrect). However only with node-apn does the script stay in a "hung or running state" after all messages are sent. i.e when i have one script that just does node-gcm i get an output of "null" (success) and the script ends. But with node-apn the messages send successfully and this is shown by having the "console.log("pending queue is empty");" fire but the script just sits in a running state waiting for something... im trying to be as descriptive as i can and i hope this helps.

**Comment by medoix** [comment]
<img width="613" alt="screen shot 2016-05-21 at 12 10 30 pm" src="https://cloud.githubusercontent.com/assets/149519/15445846/103fc294-1f4d-11e6-8d27-c26b8c49d6f6.png">
Screenshot of terminal to help explain what happens, just sits even though the apnConnection.shutdown(); command is called...

**Comment by HKskn** [comment]
You should call shutdown() method out of the callback and 'completed' event is not  guarentee notification is sent. So you can use promises and timeout when 'completed' fired. 
an example:

pushNotification(....).then(function (apn) {
  setTimeout(apn.shutdown(), 10000)
});

function pushNotification () {
      var deferred = Q.defer();
      var clientApnConnection = new APN.Connection(....);
      clientApnConnection.on('completed', function () {
         deferred.resolve({apn : clientApnConnection});
      });
}

**Comment by mvanallen** [comment]
I had the same issue as the OP (node process not exiting) and found that it's an issue with the connection handling. Here's what happens:

If you push a notification on a basic setup and then let it sit for a while, the socketBuffer will spin up, create a socket and work until the notificationQueue is empty. Then it will emit "completed" and exit while leaving the socket open b/c 'shutdownPending' is still "false" at that point in time.

It you then call shutdown() later on (e.g. in response to a SIGINT), it will toggle the 'shutdownPending' flag, but not do anything beyond that as the socketBuffer thing isn't running anymore. Due to the remaining socket the node process kept running I had to kill it manually.

I got it to work as expected by simply adding a call to ´serviceBuffer´ after ´shutdown()´. That causes it to recognize that the message queue is empty and retire the socket properly.

**Comment by argon** [comment]
That's really interesting, thanks for the investigation.

—A

**Comment by medoix** [comment]
My issue was that i didn't understand the feedback service enough and it was in fact the feedback function that was remaining open (by design). I have now split that out into a different service and all works fine. Would have helped if i had of shared all the code to start. Sorry @argon

**Comment by Vinayk93** [comment]
still no answer No worries I am gonna use process.exit().
Work for me.
