### ISSUE TITLE
InvalidToken error (errornum=8) on TransmissionError

### ISSUE THREAD

**Issue by ickata** [argon/node-apn#389]
Hi all,

I perfectly know that this issue is not related to node-apn module, but I really don't know where to look for a solution anymore. Apple cannot assist me.

I'm trying to build a hybrid app using PhoneGap. I created a Push Notification registration following that example:
https://github.com/phonegap/phonegap-plugin-push/blob/master/docs/EXAMPLES.md

The `"onregistration"` event returned me a `registrationId` property with a HEX value which I use as Device Token.

Then I'm trying to send Push Notification using node-apn module. I'm executing the script from my Mac and here's the code:

```
var http = require('http');
var apn = require('apn');
var url = require('url');
 
var myPhone = "7e028f4d66d07...a568c350b257";  // I'm not giving the whole token on purpose :)

var apnsConnection = new apn.Connection({
   production  : false,
   cert        : 'aps_development.pem',
   key         : 'key.pem',
   ca          : [ 'entrust_2048_ca.cer' ],
   passphrase  : ''
});
 
var myDevice = new apn.Device( myPhone );
 
var note = new apn.Notification();
note.expiry = Math.floor(Date.now() / 1000) + 3600; // Expires 1 hour from now.
note.badge = 1;
note.sound = "notification-beep.wav";
note.alert = "Hello tables!";
note.payload = {'messageFrom': 'Tables'};

apnsConnection.on( 'error', function ( e ) {
   console.log( 'Error', e );
}).on( 'socketError', function ( e ) {
   console.log( 'SocketError', e );
}).on( 'transmitted', function ( note, id ) {
   console.log( 'Transmitted', id );
}).on( 'completed', function () {
   console.log( 'Completed' );
}).on( 'connected', function (sockets ) {
   console.log( 'Connected', sockets );
}).on( 'timeout', function () {
   console.log( 'Timeout' );
}).on( 'transmissionError', function ( code, note, id ) {
   console.log( 'TransmissionError', code, id );
});

apnsConnection.pushNotification( note, myDevice );
```

I followed these instructions for creating the required certificates from Apple Developer Center:
https://www.raywenderlich.com/123862/push-notifications-tutorial

I also downloaded entrust_2048_ca.cer from Entrust. 

I think that everything is fine with my certificates because executing this openssl command returns no errors:
```
$ openssl s_client -connect gateway.sandbox.push.apple.com:2195 -cert aps_development.pem -debug -showcerts -CAfile entrust_2048_ca.pem

...
    Start Time: 1464243673
    Timeout   : 300 (sec)
    Verify return code: 0 (ok)
```

Still, I am unable to send Push Notification to my device:

```
Connected 1
Transmitted Device {
  token: <Buffer 7e 02 8f 4d 07 b6 ... 5e 25 a5 68 c3 50 b2 57> }
Completed
TransmissionError 8 Device {
  token: <Buffer 7e 02 8f 4d 07 b6 ... 5e 25 a5 68 c3 50 b2 57> }
Connected 1
```

The TransmissionError event contains error code 8, which is "InvalidToken" error according to this table:
https://developer.apple.com/library/ios/documentation/NetworkingInternet/Conceptual/RemoteNotificationsPG/Appendixes/BinaryProviderAPI.html#//apple_ref/doc/uid/TP40008194-CH106-SW1

Can anybody tell me what am I doing wrong?

**Comment by argon** [comment]
Your certificates are likely provisioned incorrectly.

**Comment by ickata** [comment]
Hi @argon , 

Thanks for the reply and the NodeJS module ;)

I also considered this as possibility, however:

  - Why the `openssl` command with certificates forwarding returns no errors?
  - Why would be there a problem since I am strictly following the instructions for provisioning?

But you may be right though. Something which I forgot to add - after issuing the required certificate and adding it to Keychain Access, I always get "This certificate has an invalid user" error:
http://i.imgur.com/pjfB7z6.png

Could it be this?

**Comment by argon** [comment]
I don't doubt that the certificates are valid. But I do not think they have been created to correctly match your app. You must ensure the bundle ID's and provisioning entitlements are correct.

—A

**Comment by ickata** [comment]
Hm, maybe the problem is the way I'm using PhoneGap? I'm using the desktop app:
http://docs.phonegap.com/getting-started/1-install-phonegap/desktop/#mac

And the iPhone app on my iPhone:
https://itunes.apple.com/app/id843536693

I'm using the same bundle ID in iOS Certificates and the application configuration:
http://imgur.com/a/R2eMx

But maybe the PhoneGap iOS app has different bundle ID and that's the reason why I cannot successfully receive a push notification? For the protocol, using `phonegap` push command from the terminal successfully sends push notification to my device, however this is not working for me - I want to see if the whole system works. 

Also, using GCM I managed to successfully send push notification to Android device using the same PhoneGap app.

Do you have any suggestions?

**Comment by argon** [comment]
You can only use push notifications with an app that you have signed with your developer profile. If you are using another app downloaded from the store that will be tied to a different profile and give you a device token for that, not your profile and therefore it will be invalid.

**Comment by ickata** [comment]
OK, got it. Thanks for the clarifications!
