### ISSUE TITLE
not sending anymore

### ISSUE THREAD

**Issue by knodeit** [argon/node-apn#390]
Notification no longer sending and there is a loop

Code:
`
 var apn = require('apn');
            var options = {
                production: accountMessaging.mode,
                key: key,
                cert: cert };

            this.service = new apn.connection(options);

            this.service.on('connected', function () {
                console.log('APNS SERVER Connected');
            });

            this.service.on('transmitted', function (notification, device) {
                console.log('APNS SERVER  Notification transmitted to:' + device.token.toString('hex'));
            });

            this.service.on('transmissionError', function (errCode, notification, device) {
                console.error('APNS SERVER  Notification caused error: ' + errCode + ' for device ', device, notification);
                if (errCode == 1) {
                    console.log('Processing error');
                }
                if (errCode == 2) {
                    console.log('Missing device token');
                }
                if (errCode == 3) {
                    console.log('Missing topic');
                }
                if (errCode == 4) {
                    console.log('Missing payload');
                }
                if (errCode == 5) {
                    console.log('Invalid token size');
                }
                if (errCode == 6) {
                    console.log('Invalid topic size');
                }
                if (errCode == 7) {
                    console.log('Invalid payload size');
                }
                if (errCode == 8) {
                    console.log('APNS SERVER  A error code of 8 indicates that the device token is invalid. This could be for a number of reasons - are you using the correct environment? i.e. Production vs. Sandbox');
                }
                if (errCode == 513) {
                    console.log('Certificate has expired');
                }
            });

            this.service.on('error', function (err) {
                console.log('APNS SERVER - ' + err);
            });

            this.service.on('error', function (err) {
                console.log('APNS SERVER - ' + err);
            });

            this.service.on('timeout', function () {
                console.log('APNS SERVER  Connection Timeout');
            });

            this.service.on('disconnected', function () {
                console.log('APNS SERVER  Disconnected from APNS');
            });

            var apnConnection = new apn.Connection(options);
            var note = new apn.Notification();

            note.expiry = Math.floor(Date.now() / 1000) + 3600; // Expires 1 hour from now.

            note.alert = title;
            note.payload = payload;

            this.service.pushNotification(note, user.notifications.iOSToken);
`
OUTPUT:
APNS SERVER Connected
APNS SERVER  Disconnected from APNS
APNS SERVER Connected
APNS SERVER  Disconnected from APNS
APNS SERVER Connected
APNS SERVER  Disconnected from APNS
APNS SERVER Connected
APNS SERVER  Disconnected from APNS
APNS SERVER Connected
APNS SERVER  Disconnected from APNS
APNS SERVER Connected
APNS SERVER  Disconnected from APNS

and this keeps going on

Certificates are new generated and OK

node version v5.11.1
npm version 3.8.6
apn verisn 1.7.5

**Comment by argon** [comment]
How have you verified the certificates?

—A

**Comment by knodeit** [comment]
I've recreated all certificates and verified they are correct using this command
openssl s_client -connect gateway.sandbox.push.apple.com:2195 -cert devcert.pem -key devkey.pem

Which opens a connection correctly 

I've tested this for adhoc certificate and developer certificate and both connect correctly to the APNS server, however the problem is consistent.

I'm using the same module with exact same code on several other projects and they all work great

**Comment by knodeit** [comment]
I noticed this
CONNECTED(00000003)
depth=1 /C=US/O=Entrust, Inc./OU=See www.entrust.net/legal-terms/OU=(c) 2012 Entrust, Inc. - for authorized use only/CN=Entrust Certification Authority - L1K
verify error:num=20:unable to get local issuer certificate
verify return:0
---
Certificate chain
 0 s:/C=US/ST=California/L=Cupertino/O=Apple Inc./CN=gateway.sandbox.push.apple.com
   i:/C=US/O=Entrust, Inc./OU=See www.entrust.net/legal-terms/OU=(c) 2012 Entrust, Inc. - for authorized use only/CN=Entrust Certification Authority - L1K
 1 s:/C=US/O=Entrust, Inc./OU=See www.entrust.net/legal-terms/OU=(c) 2012 Entrust, Inc. - for authorized use only/CN=Entrust Certification Authority - L1K
   i:/O=Entrust.net/OU=www.entrust.net/CPS_2048 incorp. by ref. (limits liab.)/OU=(c) 1999 Entrust.net Limited/CN=Entrust.net Certification Authority (2048)
---


And read the ticket about it but cant figure out which certifcate to download from where and install
i've just change this new project to new dev server so that might cause it

any help welcome

**Comment by argon** [comment]
You probably need to download this https://www.entrust.com/root-certificates/entrust_2048_ca.cer and add the path to the "ca" property when creating a connection.

—A

**Comment by knodeit** [comment]
Tried that but no luck
I've downloaded the certificate and installed it in keychain but error is exactly the same

**Comment by faaez** [comment]
I'm having a similar issue. Getting an 'UNABLE_TO_GET_ISSUER_CERT_LOCALLY' error when debug mode is on. I downloaded the entrust certificate you linked to @argon and am able to connect using openssl s_client, and specifying the entrust cert as the CA file. 

Thanks for the great work on this, btw! Really well-documented package.

**Comment by argon** [comment]
Which version of node are you using?

**Comment by IrishAdo** [comment]
I'm using the following 
```
var base_pem_path = pathInfo.resolve(__dirname, '../pem/');
var AppleCertPath = base_pem_path+'/entrust_2048_ca.cer';

var options = {
  gateway: process.env.NODE_ENV == 'production' ? 'gateway.push.apple.com' : 'gateway.sandbox.push.apple.com',
  errorCallback: callback,
  ca:  [ AppleCertPath ],
  cert: pemFile, 
  key:  pemFile,  // ** NEED TO SET TO YOURS
  passphrase: '', // ** NEED TO SET TO YOURS
  port: 2195,                       
  enhanced: true,                   
  cacheLength: 10000                  
}
var apnsConnection = new apn.Connection(options);
```

can getting the error 

**Error: Socket unusable after connection. Hint: You may be using a certificate for the wrong environment**

when I test using open ssl 
i first got the message "Verify return code: 20 (unable to get local issuer certificate)" 
then I added the "-CApath" parameter and am now gettign return code of 0 

have I set the CA correctly in the options?

**Comment by argon** [comment]
You're using deprecated options there. 

```javascript
var options = {
  ca:  [ AppleCertPath ],
  cert: pemFile, 
  key:  pemFile,  // ** NEED TO SET TO YOURS
  passphrase: '', // ** NEED TO SET TO YOURS                
  cacheLength: 10000                  
}
```

Which version of node-apn are you using?

**Comment by IrishAdo** [comment]
"apn": "^1.7.5",

Should I change the options to what you supplied?

**Comment by argon** [comment]
Yes, though I don't know if it'll help with your error in this case. There's definitely something wrong with the connection between node and Apple.

Could you please run the following command and email the output to the address on my Github profile and I might be able to offer further insight
```
openssl x509 -text -noout -in <path-to-pem>
```

**Comment by IrishAdo** [comment]
sent

**Comment by danielgolub** [comment]
I'm facing the same issue.
The error code I receive when using this package is 513.

**Comment by IrishAdo** [comment]
thats moduleInitialisationFailed  can you supply some of your code

**Comment by danielgolub** [comment]
@IrishAdo Here it is:
````````````
var apn = require('apn');

function send(tokens, body, data) {
		try {
			var options = {
				cert: "/Apple/cert.pem",
				key: "/Apple/keys.pem",
				passphrase: "**secret**",
				production: true,
			};

			var apnConnection = new apn.Connection(options);
			apnConnection.on("connected", function() {
			    console.log("Connected");
			});
			apnConnection.on("socketError", function() {
				console.error("ERROR!!!")
			});
			apnConnection.on("timeout", function () {
			    console.log("Connection Timeout");
			});

			apnConnection.on("disconnected", function() {
			    console.log("Disconnected from APNS");
			});
			apnConnection.on("transmitted", function(notification, device) {
			    console.log("Notification transmitted to:" + device.token.toString("hex"));
			});

			apnConnection.on("transmissionError", function(errCode, notification, device) {
			    console.error("Notification caused error: " + errCode + " for device ", notification);
			    if (errCode === 8) {
			        console.log("A error code of 8 indicates that the device token is invalid. This could be for a number of reasons - are you using the correct environment? i.e. Production vs. Sandbox");
			    }
			});

			var notification = new apn.Notification();

			notification.sound = "default";
			notification.alert = body;
			notification.payload = data;

			var i, device;
			for (i = 0;i<tokens.length;i++) {
				device = new apn.Device(tokens[i]);
				console.info(tokens[i])
				apnConnection.pushNotification(notification, device);
			}
		} catch(e) {
			console.info(e)
		}
	}

```````````````

**Comment by IrishAdo** [comment]
its probably from the path to your certs

/Apple/cert.pem

is the root of your server not the correct directory

try using 

var base_pem_path = pathInfo.resolve(__dirname);
var options = {
                cert: base_pem_path+"/Apple/cert.pem",
                key: base_pem_path+"/Apple/keys.pem",
                passphrase: "**secret**",
                production: true,
            };

**Comment by IrishAdo** [comment]
Argon just wanted to say a big thank you for all your help with getting the notifications working cleared out all of the tokens and its working fine I also set up a staging server and db and blocked the developers from accessing alive site with a test app so the tokens should never break again.;-)
