### ISSUE TITLE
Apn.Connection.on('transmitted', function(notification, ...) {}) bad/malformed notification object. Stringify then parse workaround.

### ISSUE THREAD

**Issue by samsonho** [argon/node-apn#392]
Hi,

I have weird problem which I have a current fix/workaround for but perhaps someone can shed some more light. I am trying to access a custom property 'messageId' on notification via the Apn.Connection.on('transmitted', ...) callback parameter but it is failing. But for some reason it doesn't fail with the workaround below, where I access the messageId on notificationObj instead.

```
        const notificationString = JSON.stringify(notification);
        const notificationObj = JSON.parse(notificationString);
```

So notification.messageId fails as undefined by notificationObj.messageId is fine.

My payload which sends successfully looks like the following; it has a custom field named messageId beside the removed calls to setAlertTitle and setAlertBody.

```
	const result = new Apn.Notification();

	result.payload = {
		'messageId': message.messageId // message.messageId is a String.
		...
	};
```

My callback handler looks like so.

```
    connection.on('transmitted', function(notification, device) {  
        console.log(`transmitted notification: ${JSON.stringify(notification)} device: ${device} starting...`);

        const notificationString = JSON.stringify(notification);
        const notificationObj = JSON.parse(notificationString);

        notification.messageId // undefined
        notificationObj.messageId // fine

        console.log(`transmitted finished.`);
    });
```

Perhaps someone has encountered this before or I can not see the error in my js.

Thanks,
Sam

**Comment by argon** [comment]
You need:
```javascript
notification.payload.messageId
```

**Comment by samsonho** [comment]
I just logged in and confirmed your solution. I knew I was missing something obvious. Thank you for replying and fixing my problem. Cheers.
