### ISSUE TITLE
Extending the Notification Payload

### ISSUE THREAD

**Issue by josh-authy** [argon/node-apn#396]
We have extended the notification payload for our use case.  This required modifying the getters/setters in the Notification class.  

Is there a business/Apple reason the code base doesn't automatically extend the payload?

**Comment by argon** [comment]
I don't understand your question. As far as I'm aware the current notification object is fully customisable in all ways that make sense.

**Comment by josh-authy** [comment]
We wanted to add an additinonal field (uuid) like below.  This field was not passed through b/c you are setting them on the APS payload a getter/setter in the Notification prototype.  Without extending the Notification Class w/ this additional value, it is not passed through.  Is this done intentionally because of some spec?

With your module, you have to add an additional getter/setter in the Notification prototoype here:
https://github.com/argon/node-apn/blob/master/lib/notification.js#L23

and extend the apsPayload function with the addtional field.
https://github.com/argon/node-apn/blob/master/lib/notification.js#L480

e.g. 
`var note = new apn.Notification();

note.expiry = Math.floor(Date.now() / 1000) + 3600; // Expires 1 hour from now.
note.badge = 3;
note.sound = "ping.aiff";
note.uuid ="THIS VALUE IS NOT PASSED THROUGH";
note.alert = "\uD83D\uDCE7 \u2709 You have a new message";
note.payload = {'messageFrom': 'Caroline'};

apnConnection.pushNotification(note, myDevice);`

**Comment by argon** [comment]
All properties on note are convenience accessors for the aps properties. Anything custom should be set in the payload which is for application specific data. 

This will do what you need:

    note.payload = { uuid: "something" }

—A

**Comment by josh-authy** [comment]
Thank you.  TIL
