### ISSUE TITLE
How to set badges in pushnotification

### ISSUE THREAD

**Issue by hitenzaptech** [argon/node-apn#398]
Hello,
I did push notification in ios using apn but i dont know how to set badges count in it . So every time when i sent push notification its count is only 1 not incremented at all.

This is my code of iOS push notification.

if(deviceType[i] == "ios"){
                var myDevice = new apn.Device(tokens[i]);  
                var note = new apn.Notification();
                note.badge = 1;
                note.sound = "beep.wav"; //path to your sound
                note.contentAvailable = 1;
                note.alert = { "body" : data.label, "action-loc-key" : "Show Me!" , "launch-image" : "mysplash.png", "uuid": uuid};
                note.payload = {'uuid': data.uuid, 'channelId': data.channelId}; // additional payload 
                note.device = myDevice;
     
                var callback = function(errorNum, notification){
                    console.log('Error is: %s', errorNum);
                    console.log("Note " + JSON.stringify(notification));
                }
                
                var options = {
                    gateway: 'gateway.sandbox.push.apple.com',
                    errorCallback: callback,
                    cert: pem, 
                    key:  pem,  // ** NEED TO SET TO YOURS
                    passphrase: '', // ** NEED TO SET TO YOURS
                    port: 2195,                       
                    enhanced: true,                   
                    cacheLength: 10000                  
                }
            
                var apnsConnection = new apn.Connection(options);
                console.log("Note " + JSON.stringify(note));
                apnsConnection.sendNotification(note);
            }

**Comment by argon** [comment]
iOS does not support incrementing the badge. The number sent in the payload is the number displayed on the badge.

—A

**Comment by hitenzaptech** [comment]
So iOS developers can't set badge numbers?
So it will be set by backend node.js developer ?

**Comment by argon** [comment]
I strongly encourage you to read the documentation.

Set the badge to 2 for node-apn and it will update the icon.

—A

**Comment by hitenzaptech** [comment]
Can you please provide me the link for it ?

**Comment by argon** [comment]
https://developer.apple.com/library/ios/documentation/NetworkingInternet/Conceptual/RemoteNotificationsPG/Chapters/TheNotificationPayload.html#//apple_ref/doc/uid/TP40008194-CH107-SW2

**Comment by IrishAdo** [comment]
Hiten please use the latest code base which is sending notifications correctly also doesn't use the deprecated function sendNotification.  It also puts out a lot of Debug in the console that will help you debug.

**Comment by hitenzaptech** [comment]
@IrishAdo Thank you for your suggestions.
I am working on it.
