### ISSUE TITLE
Support for new JSON Web Token Authentication

### ISSUE THREAD

**Issue by florianreinhart** [argon/node-apn#401]
"Later this year" Apple will introduce APNS provider authentication based on JSON Web Tokens, i.e. we hopefully don't have to deal with expiring certificates anymore.

Session 724 from WWDC16 has a little more information:
* [Session Video](https://developer.apple.com/videos/play/wwdc2016/724/)
* [Slides](http://devstreaming.apple.com/videos/wwdc/2016/724x4wbpmrtkjpgfdlj/724/724_whats_new_in_the_apple_push_notification_service.pdf)

However, the documentation hasn't been updated yet. I'll update this if there are any new announcements.

**Comment by argon** [comment]
Thanks for making the issue, I have already mentioned it on https://github.com/argon/node-apn/pull/278 but haven't done any work towards it yet.

**Comment by argon** [comment]
I'm hoping to release this in v2.1 this weekend

**Comment by florianreinhart** [comment]
Awesome!
I guess they added documentation for JWT 2 days ago: https://developer.apple.com/library/content/documentation/NetworkingInternet/Conceptual/RemoteNotificationsPG/Chapters/APNsProviderAPI.html#//apple_ref/doc/uid/TP40008194-CH101-SW21

**Comment by n3trino** [comment]
Apple announced JWT Authentication is available :)

**Comment by argon** [comment]
@n3trino I'm already working on this, see #430

**Comment by argon** [comment]
This has been released in 2.1.0
