### ISSUE TITLE
Error with development environment

### ISSUE THREAD

**Issue by dhkundan** [argon/node-apn#404]
var options = {  
        cert: 'Certificates.pem',
        key : 'Certificates.pem',
        production  : false
        };

I have only one certificate generated which is **Certificates.pem**. I have put Certificates.pem in cert as well as in key. but I am getting error as Error: certificate does not support configured environment, production: false.
Can anyone tell me how to solve this issue?

**Comment by argon** [comment]
please run the following command and post the output (or email me directly, if you prefer)

`openssl x509 -in Certificates.pem -text -noout`
