### ISSUE TITLE
Badge count 0 not sent

### ISSUE THREAD

**Issue by mspensieri** [argon/node-apn#406]
If you set the badge number to 0, it is ignored and set to `undefined` instead. This was fixed over a month ago with this commit https://github.com/argon/node-apn/commit/0fa7cf0d598e13f26214cd2273052c1b052ce824, but no new version has been released with this fix.

Please release v1.7.7 to NPM

**Comment by alavers** [comment]
👍

**Comment by argon** [comment]
Done

**Comment by mspensieri** [comment]
Thank you 😀
