### ISSUE TITLE
feedback service problem

### ISSUE THREAD

**Issue by davibe** [argon/node-apn#409]
I sent some message to a list of 10 push token. Only 1 of them was valid (belonging to a device that's still alive). I received the notification on the device and received no feedback for hours.

After a few hours i got a response from the feedback service invalidating all the tokens including the one that worked just fine.

This is the thing i am writing https://github.com/davibe/push-notification-service
And this is the specific apn usage https://github.com/davibe/push-notification-service/blob/master/src/services/apn.coffee

**Comment by khatekar** [comment]
How you fix it? I am facing similar issues.

**Comment by argon** [comment]
That is probably valid behaviour the timestamp is the crucial bit here. Please read the documentation from Apple that explains how to handle the feedback service.
