### ISSUE TITLE
Using APNS in Production and Development

### ISSUE THREAD

**Issue by hockeybro12** [argon/node-apn#410]
It seems like recently Apple has allowed the use of the same certificate for APNS for both production and sandbox mode. Has Node-APN been updated to reflect this? The documentation still asks to set the environment variable in order to use in production like so: `process.env['NODE_ENV'] = 'production';` Is this still necessary anymore?

If I want to use node-apn for both production/sandbox, is the only way to do that by making changes to the database where the APNS ID is stored?

**Comment by argon** [comment]
It is still necessary because different servers must be used depending on the environment. node-apn should work perfectly with the the new certificate scheme, the only change being that it's not necessary to switch certificates depending on your environment. Everything else stays the same

—A
