### ISSUE TITLE
transmissionError

### ISSUE THREAD

**Issue by EverChris** [argon/node-apn#411]
anyone got this problem??

why does `transmissionError` occured ?

BTW,  I use another pusher written by php and `ck.pem`, sent ok.

> connected { '0': 1 }
transmitted { '0':
   { encoding: 'utf8',
     payload: { messageFrom: 'Caroline', aps: [Object] },
     expiry: 1469702357,
     priority: 10,
     retryLimit: -1,
     device: undefined,
     compiled: '{"messageFrom":"Caroline","aps":{"badge":3,"sound":"ping.aiff","alert":"📧 ✉ You have a new message"}}',
     truncateAtWordEnd: false,
     _badge: 3,
     _sound: 'ping.aiff',
     _alert: '📧 ✉ You have a new message' },
  '1':
   Device {
     token: <Buffer cc 42 dc db f1 cf 8a 20 ca 7f bd ea a1 1b a6 f2 04 d5 ca 15 0c 9c 4d 29 d5 d9 60 6a 3e a2 59 b6> } }
completed {}
transmissionError { '0': 8,
  '1':
   { encoding: 'utf8',
     payload: { messageFrom: 'Caroline', aps: [Object] },
     expiry: 1469702357,
     priority: 10,
     retryLimit: -1,
     device: undefined,
     compiled: '{"messageFrom":"Caroline","aps":{"badge":3,"sound":"ping.aiff","alert":"📧 ✉ You have a new message"}}',
     truncateAtWordEnd: false,
     _badge: 3,
     _sound: 'ping.aiff',
     _alert: '📧 ✉ You have a new message' },
  '2':
   Device {
     token: <Buffer cc 42 dc db f1 cf 8a 20 ca 7f bd ea a1 1b a6 f2 04 d5 ca 15 0c 9c 4d 29 d5 d9 60 6a 3e a2 59 b6> } }
disconnected { '0': 0 }
connected { '0': 1 }

**Comment by argon** [comment]
if you're using the feedback service ensure that you're passing the passphrase to that also.

**Comment by EverChris** [comment]
@argon you're right, I update the issue, another problem.

thank you.

**Comment by argon** [comment]
Judging by the output there, you're getting error `8`. This means you're sending it to an invalid device token. Ensure you're using the correct environment Prod / Sandbox as the device tokens differ between the environments.

**Comment by EverChris** [comment]
@argon device_token is ok, cuz I used it in another program which written by PHP and it works, and both `development`  environment.

**Comment by EverChris** [comment]
@argon 
more info:

I used this same nodejs program a few hours ago, it worked several times, but later it doesnt worked with error "disconnected by apn", then I regenerated my appid and certificate again,

now, this error occured.

**Comment by EverChris** [comment]
it's my mistake!
