### ISSUE TITLE
Push notification reaches APNS, not delivered to an iOS device

### ISSUE THREAD

**Issue by DamodarSojka** [argon/node-apn#412]
I assume that notifications are successfully delivered to APNS, feedback is always empty and library emits "transmitted" event. Notification looks like:

```
var pushMessage = new apn.Notification({
        contentAvailable: 1,
        alert: {
            title: chatName,
            body: text
        },
        payload: {
            chatID: chatID,
            username: username
        }
});
```

Cert.pem and key.pem are correct, it was checked with the openssl command.

App is an Ionic project. Phonegap-push-plugin is used to integrate native SDK, which works for Android, but not for the iOS.

I am using AdobePhoneGap build to build my app. I have followed countless tutorials and checked every step many times, if someone has any idea what could be wrong please let me know. If any more information is needed let me know.

I am aware that this might not be an node-apn issue, but maybe it is, or someone has an idea. Close it if you think it is not the case. 
Thanks

**Comment by argon** [comment]
Which version of the module are you using?

**Comment by argon** [comment]
```javascript
var pushMessage = new apn.Notification({
    aps: {
        contentAvailable: 1,
        alert: {
            title: chatName,
            body: text
        },
    },
    chatID: chatID,
    username: username
});
```

Try that ☝️

**Comment by DamodarSojka** [comment]
Worked! Thanks! Can be closed.
