### ISSUE TITLE
Support for apns identifier in iOS 10

### ISSUE THREAD

**Issue by dannypier** [argon/node-apn#414]
iOS 10 allows for the updating of notifications through an identifier. For remote notifications, this identifier is `apns-collapse-id` in the header of the notification.

Documentation is sparse on this feature, but you can see it explained at the WWDC session here: https://developer.apple.com/videos/play/wwdc2016/707/ (about 18:05 into the video).

Would be a great addition to this already awesome library.

**Comment by argon** [comment]
This will need to be added after (or with) #278
