### ISSUE TITLE
connection.shutdown() should immediately retire all socket when there notificationBuffer is empty

### ISSUE THREAD

**Issue by garylai** [argon/node-apn#415]
I created a apn.connection and sent only 1 message. After the push notification has been successfully received, I Crtl-C my node service. In my SIGINT event handler, connection.shutdown() is called. But my node service won't stop because the sockets are not closed.

I think if the notificationBuffer is empty when shutdown() is called, apn.connection should close all socket immediately.

**Comment by maa105** [comment]
hello thx for awesome work!
i have an issue too that might be related to shutsdown.
I'm calling it then i'm creating a new connection all together but the old event handlers are still being called.

    apn = new APN.Connection(config.apn.connection);
    start();//hooks event hanlers
    apn.shutdown();
    apn = new APN.Connection(config.apn.connection);
    start();//hooks event hanlers

event handlers are being called twice

**Comment by argon** [comment]
This should be resolved with 2.0.0
