### ISSUE TITLE
iOS device does not received notification after reconnect internet access

### ISSUE THREAD

**Issue by mangacu** [argon/node-apn#416]
I have built app with ionic framework, I used node-apn on server and phonegap-plugin-push for client. Push notification working as well if iOS device has internet acess but cannot received any notification after reconnect internet access. Here is steps for reproduce this:
1. Disconnect device with internet
2. Use another device to send notification
3. Wait few minutes then reconnect device with internet => nothing happens
Push notification should received by iOS device after reconnect internet. Can you give me some solution? Thanks

**Comment by argon** [comment]
You must set an `expiry` time on the notification

> Expiry—A fixed UNIX epoch date expressed in seconds (UTC) that identifies when the notification is no longer valid and can be discarded. The expiry value uses network byte order (big endian). If the expiry value is non-zero, APNs tries to deliver the notification at least once. Specify zero to request that APNs not store the notification at all.

[Legacy Notification Format doc](https://developer.apple.com/library/ios/documentation/NetworkingInternet/Conceptual/RemoteNotificationsPG/Appendixes/LegacyFormat.html#//apple_ref/doc/uid/TP40008194-CH105-SW5)

**Comment by mangacu** [comment]
@argon Thanks for reply, here is my code:

        var userDevice = new apn.Device(id);

        var note = new apn.Notification();
        note.expiry = Math.floor(Date.now() / 1000) + 3600; // Expires 1 hour from now.
        note.badge = params.notification.badge || 0;
        note.sound = 'ping.aiff';
        note.alert = params.notification.text;

        apnConnection.pushNotification(note, userDevice);

I think expiry is set to 1 hour. I don't know why it's not working with my app. Thanks for your support.
