### ISSUE TITLE
1.x branch suggestion

### ISSUE THREAD

**Issue by ide** [argon/node-apn#417]
I noticed the HTTP/2 PR was getting pretty big and it seems like there are also some tasks like writing docs that could use help from contributors. Also it works well anyway, we use it in production. @argon what do you think about cutting a `1.x` branch and then merging the HTTP/2 PR to master so that people see it front-and-center and can contribute to it?

**Comment by argon** [comment]
Yeah that's my plan for the next few days. Need to sort out error handling then the main tasks will be documentation

**Comment by argon** [comment]
v2.0.0 has been released

**Comment by ide** [comment]
😮😮😮

![200_s](https://cloud.githubusercontent.com/assets/379606/18733825/1f595aa6-8023-11e6-8aea-8c42be6eb0ae.gif)
