### ISSUE TITLE
20bit emoji ?!

### ISSUE THREAD

**Issue by arhi** [argon/node-apn#419]
Hi,
I see that this works: \uD83D\uDCE7

but for e.g. here: http://unicode.org/emoji/charts/full-emoji-list.html
I see bunch of 20bit chars, for e.g. no 977 U+1F5BC "frame with picture"
how to convert the U+1F5BC to add to APN alert ?! I tried
\u1F5BC and \u0001\uF5BC and it does not work so a hint how to write these 20bit ones would be appreciated :D

**Comment by erikstrottmann** [comment]
Hi @arhi, are you still having this issue? You should try `\uD83D\uDDBC`. I got that string from [this online converter](https://r12a.github.io/apps/conversion/) I found on Google, so you should test it out before putting it into production. Good luck!

**Comment by arhi** [comment]
thanks big time :D
