### ISSUE TITLE
No Response code in Feedback Service

### ISSUE THREAD

**Issue by shahmanthan9** [argon/node-apn#421]
Hi
I wanted to handle various device-token in my system depending response code sent in feedback, I couldn't find response code, can you please guide me getting the same.
Following are response code on mentioned in documentation [here](https://developer.apple.com/library/ios/documentation/NetworkingInternet/Conceptual/RemoteNotificationsPG/Appendixes/BinaryProviderAPI.html#//apple_ref/doc/uid/TP40008194-CH106-SW4)

<table class="graybox" border="0" cellspacing="0" cellpadding="5"><caption class="tablecaption"><strong class="caption_number">Table A-4</strong>&nbsp;&nbsp;Codes in error-response packet</caption><tbody><tr><th scope="col" class="TableHeading_TableRow_TableCell"><p>Status code</p></th><th scope="col" class="TableHeading_TableRow_TableCell"><p>Description</p></th></tr><tr><td scope="row"><p>0</p></td><td><p>No errors encountered</p></td></tr><tr><td scope="row"><p>1</p></td><td><p>Processing error</p></td></tr><tr><td scope="row"><p>2</p></td><td><p>Missing device token</p></td></tr><tr><td scope="row"><p>3</p></td><td><p>Missing topic</p></td></tr><tr><td scope="row"><p>4</p></td><td><p>Missing payload</p></td></tr><tr><td scope="row"><p>5</p></td><td><p>Invalid token size</p></td></tr><tr><td scope="row"><p>6</p></td><td><p>Invalid topic size</p></td></tr><tr><td scope="row"><p>7</p></td><td><p>Invalid payload size</p></td></tr><tr><td scope="row"><p>8</p></td><td><p>Invalid token</p></td></tr><tr><td scope="row"><p>10</p></td><td><p>Shutdown</p></td></tr><tr><td scope="row"><p>128</p></td><td><p>Protocol error (APNs could not parse the notification)</p></td></tr><tr><td scope="row"><p>255</p></td><td><p>None (unknown)</p></td></tr></tbody></table>

**Comment by argon** [comment]
The feedback service does not provide codes, only device token and timestamp.

The codes above  are sent in response to an error when _sending_ a notification using an `apn.Connection`.
