### ISSUE TITLE
UserInfo not adding to the request

### ISSUE THREAD

**Issue by yurypaleev** [argon/node-apn#424]
Why UserInfo not adding to the request?
In logs I see:
`Could not register user for website identifier web.***.***.***, received response 500`

**Comment by argon** [comment]
I do not understand your question. Please add more context.

**Comment by yurypaleev** [comment]
When I send request to access device token, I add userInfo:

`safari.pushNotification.requestPermission(location.origin + '/api/notifications', safariPushId, USERINFO, function(data) {});`

And when I look at the logs from request `/api/notifications/v1/log`, I see:
`{ logs: [ 'Could not register user for website identifier web.***.***.***, received response 500' ] }`

**Comment by argon** [comment]
What you have described is not related to `node-apn`. I would suggest you ask the question on StackOverflow or similar.

**Comment by yurypaleev** [comment]
I thought you could help me

**Comment by argon** [comment]
This is not the right venue. If the issues on this project are not related to the project then it becomes confusing for other developers.

Also I do not have any insight into your problem and by asking somewhere like StackOverflow you will be much more likely to find someone who can help
